/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequest
 */
export interface AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequest {
    /**
     * 
     */
    email: string;
}

/**
 * Check if a given object implements the AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequest interface.
 */
export function instanceOfAuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequest(value: object): value is AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    return true;
}

export function AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequestFromJSON(json: any): AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequest {
    return AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequestFromJSONTyped(json, false);
}

export function AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequestToJSON(json: any): AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequest {
    return AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequestToJSONTyped(json, false);
}

export function AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequestToJSONTyped(value?: AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

