/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationGetMeApiV1AuthMeGetResponse
 */
export interface AuthenticationGetMeApiV1AuthMeGetResponse {
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    role: AuthenticationGetMeApiV1AuthMeGetResponseRoleEnum;
    /**
     * 
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const AuthenticationGetMeApiV1AuthMeGetResponseRoleEnum = {
    User: 'user',
    Admin: 'admin',
} as const;
export type AuthenticationGetMeApiV1AuthMeGetResponseRoleEnum = typeof AuthenticationGetMeApiV1AuthMeGetResponseRoleEnum[keyof typeof AuthenticationGetMeApiV1AuthMeGetResponseRoleEnum];


/**
 * Check if a given object implements the AuthenticationGetMeApiV1AuthMeGetResponse interface.
 */
export function instanceOfAuthenticationGetMeApiV1AuthMeGetResponse(value: object): value is AuthenticationGetMeApiV1AuthMeGetResponse {
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('role' in value) || value['role'] === undefined) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function AuthenticationGetMeApiV1AuthMeGetResponseFromJSON(json: any): AuthenticationGetMeApiV1AuthMeGetResponse {
    return AuthenticationGetMeApiV1AuthMeGetResponseFromJSONTyped(json, false);
}

export function AuthenticationGetMeApiV1AuthMeGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationGetMeApiV1AuthMeGetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'email': json['email'],
        'id': json['id'],
        'name': json['name'],
        'role': json['role'],
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
    };
}

export function AuthenticationGetMeApiV1AuthMeGetResponseToJSON(json: any): AuthenticationGetMeApiV1AuthMeGetResponse {
    return AuthenticationGetMeApiV1AuthMeGetResponseToJSONTyped(json, false);
}

export function AuthenticationGetMeApiV1AuthMeGetResponseToJSONTyped(value?: AuthenticationGetMeApiV1AuthMeGetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'email': value['email'],
        'id': value['id'],
        'name': value['name'],
        'role': value['role'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}

