/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationLogoutApiV1AuthLogoutPostRequest
 */
export interface AuthenticationLogoutApiV1AuthLogoutPostRequest {
    /**
     * 
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the AuthenticationLogoutApiV1AuthLogoutPostRequest interface.
 */
export function instanceOfAuthenticationLogoutApiV1AuthLogoutPostRequest(value: object): value is AuthenticationLogoutApiV1AuthLogoutPostRequest {
    if ((!('refreshToken' in (value as Record<string, any>)) && !('refresh_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['refreshToken'] === undefined && (value as Record<string, any>)['refresh_token'] === undefined)) return false;
    return true;
}

export function AuthenticationLogoutApiV1AuthLogoutPostRequestFromJSON(json: any): AuthenticationLogoutApiV1AuthLogoutPostRequest {
    return AuthenticationLogoutApiV1AuthLogoutPostRequestFromJSONTyped(json, false);
}

export function AuthenticationLogoutApiV1AuthLogoutPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationLogoutApiV1AuthLogoutPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'refreshToken': json['refresh_token'],
    };
}

export function AuthenticationLogoutApiV1AuthLogoutPostRequestToJSON(json: any): AuthenticationLogoutApiV1AuthLogoutPostRequest {
    return AuthenticationLogoutApiV1AuthLogoutPostRequestToJSONTyped(json, false);
}

export function AuthenticationLogoutApiV1AuthLogoutPostRequestToJSONTyped(value?: AuthenticationLogoutApiV1AuthLogoutPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refresh_token': value['refreshToken'],
    };
}

