/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationChangePasswordApiV1AuthChangePasswordPostRequest
 */
export interface AuthenticationChangePasswordApiV1AuthChangePasswordPostRequest {
    /**
     * 
     */
    currentPassword: string;
    /**
     * 
     */
    newPassword: string;
}

/**
 * Check if a given object implements the AuthenticationChangePasswordApiV1AuthChangePasswordPostRequest interface.
 */
export function instanceOfAuthenticationChangePasswordApiV1AuthChangePasswordPostRequest(value: object): value is AuthenticationChangePasswordApiV1AuthChangePasswordPostRequest {
    if ((!('currentPassword' in (value as Record<string, any>)) && !('current_password' in (value as Record<string, any>))) || ((value as Record<string, any>)['currentPassword'] === undefined && (value as Record<string, any>)['current_password'] === undefined)) return false;
    if ((!('newPassword' in (value as Record<string, any>)) && !('new_password' in (value as Record<string, any>))) || ((value as Record<string, any>)['newPassword'] === undefined && (value as Record<string, any>)['new_password'] === undefined)) return false;
    return true;
}

export function AuthenticationChangePasswordApiV1AuthChangePasswordPostRequestFromJSON(json: any): AuthenticationChangePasswordApiV1AuthChangePasswordPostRequest {
    return AuthenticationChangePasswordApiV1AuthChangePasswordPostRequestFromJSONTyped(json, false);
}

export function AuthenticationChangePasswordApiV1AuthChangePasswordPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationChangePasswordApiV1AuthChangePasswordPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'currentPassword': json['current_password'],
        'newPassword': json['new_password'],
    };
}

export function AuthenticationChangePasswordApiV1AuthChangePasswordPostRequestToJSON(json: any): AuthenticationChangePasswordApiV1AuthChangePasswordPostRequest {
    return AuthenticationChangePasswordApiV1AuthChangePasswordPostRequestToJSONTyped(json, false);
}

export function AuthenticationChangePasswordApiV1AuthChangePasswordPostRequestToJSONTyped(value?: AuthenticationChangePasswordApiV1AuthChangePasswordPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'current_password': value['currentPassword'],
        'new_password': value['newPassword'],
    };
}

