/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AuthenticationGetMeApiV1AuthMeGetResponse } from './AuthenticationGetMeApiV1AuthMeGetResponse';
import {
    AuthenticationGetMeApiV1AuthMeGetResponseFromJSON,
    AuthenticationGetMeApiV1AuthMeGetResponseFromJSONTyped,
    AuthenticationGetMeApiV1AuthMeGetResponseToJSON,
    AuthenticationGetMeApiV1AuthMeGetResponseToJSONTyped,
} from './AuthenticationGetMeApiV1AuthMeGetResponse';

/**
 * 
 * @export
 * @interface AuthenticationLoginApiV1AuthLoginPostResponse
 */
export interface AuthenticationLoginApiV1AuthLoginPostResponse {
    /**
     * 
     */
    accessToken: string;
    /**
     * 
     */
    expiresIn: number;
    /**
     * 
     */
    refreshToken: string;
    /**
     * 
     */
    tokenType?: string;
    /**
     * 
     */
    user: AuthenticationGetMeApiV1AuthMeGetResponse;
}

/**
 * Check if a given object implements the AuthenticationLoginApiV1AuthLoginPostResponse interface.
 */
export function instanceOfAuthenticationLoginApiV1AuthLoginPostResponse(value: object): value is AuthenticationLoginApiV1AuthLoginPostResponse {
    if ((!('accessToken' in (value as Record<string, any>)) && !('access_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['accessToken'] === undefined && (value as Record<string, any>)['access_token'] === undefined)) return false;
    if ((!('expiresIn' in (value as Record<string, any>)) && !('expires_in' in (value as Record<string, any>))) || ((value as Record<string, any>)['expiresIn'] === undefined && (value as Record<string, any>)['expires_in'] === undefined)) return false;
    if ((!('refreshToken' in (value as Record<string, any>)) && !('refresh_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['refreshToken'] === undefined && (value as Record<string, any>)['refresh_token'] === undefined)) return false;
    if (!('user' in value) || value['user'] === undefined) return false;
    return true;
}

export function AuthenticationLoginApiV1AuthLoginPostResponseFromJSON(json: any): AuthenticationLoginApiV1AuthLoginPostResponse {
    return AuthenticationLoginApiV1AuthLoginPostResponseFromJSONTyped(json, false);
}

export function AuthenticationLoginApiV1AuthLoginPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationLoginApiV1AuthLoginPostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['access_token'],
        'expiresIn': json['expires_in'],
        'refreshToken': json['refresh_token'],
        'tokenType': json['token_type'] == null ? undefined : json['token_type'],
        'user': AuthenticationGetMeApiV1AuthMeGetResponseFromJSON(json['user']),
    };
}

export function AuthenticationLoginApiV1AuthLoginPostResponseToJSON(json: any): AuthenticationLoginApiV1AuthLoginPostResponse {
    return AuthenticationLoginApiV1AuthLoginPostResponseToJSONTyped(json, false);
}

export function AuthenticationLoginApiV1AuthLoginPostResponseToJSONTyped(value?: AuthenticationLoginApiV1AuthLoginPostResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'access_token': value['accessToken'],
        'expires_in': value['expiresIn'],
        'refresh_token': value['refreshToken'],
        'token_type': value['tokenType'],
        'user': AuthenticationGetMeApiV1AuthMeGetResponseToJSON(value['user']),
    };
}

