/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationRegisterApiV1AuthRegisterPostRequest
 */
export interface AuthenticationRegisterApiV1AuthRegisterPostRequest {
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    password: string;
}

/**
 * Check if a given object implements the AuthenticationRegisterApiV1AuthRegisterPostRequest interface.
 */
export function instanceOfAuthenticationRegisterApiV1AuthRegisterPostRequest(value: object): value is AuthenticationRegisterApiV1AuthRegisterPostRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AuthenticationRegisterApiV1AuthRegisterPostRequestFromJSON(json: any): AuthenticationRegisterApiV1AuthRegisterPostRequest {
    return AuthenticationRegisterApiV1AuthRegisterPostRequestFromJSONTyped(json, false);
}

export function AuthenticationRegisterApiV1AuthRegisterPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationRegisterApiV1AuthRegisterPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'name': json['name'],
        'password': json['password'],
    };
}

export function AuthenticationRegisterApiV1AuthRegisterPostRequestToJSON(json: any): AuthenticationRegisterApiV1AuthRegisterPostRequest {
    return AuthenticationRegisterApiV1AuthRegisterPostRequestToJSONTyped(json, false);
}

export function AuthenticationRegisterApiV1AuthRegisterPostRequestToJSONTyped(value?: AuthenticationRegisterApiV1AuthRegisterPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'name': value['name'],
        'password': value['password'],
    };
}

