/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationChangePasswordApiV1AuthChangePasswordPostResponse
 */
export interface AuthenticationChangePasswordApiV1AuthChangePasswordPostResponse {
    /**
     * 
     */
    message: string;
}

/**
 * Check if a given object implements the AuthenticationChangePasswordApiV1AuthChangePasswordPostResponse interface.
 */
export function instanceOfAuthenticationChangePasswordApiV1AuthChangePasswordPostResponse(value: object): value is AuthenticationChangePasswordApiV1AuthChangePasswordPostResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function AuthenticationChangePasswordApiV1AuthChangePasswordPostResponseFromJSON(json: any): AuthenticationChangePasswordApiV1AuthChangePasswordPostResponse {
    return AuthenticationChangePasswordApiV1AuthChangePasswordPostResponseFromJSONTyped(json, false);
}

export function AuthenticationChangePasswordApiV1AuthChangePasswordPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationChangePasswordApiV1AuthChangePasswordPostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
    };
}

export function AuthenticationChangePasswordApiV1AuthChangePasswordPostResponseToJSON(json: any): AuthenticationChangePasswordApiV1AuthChangePasswordPostResponse {
    return AuthenticationChangePasswordApiV1AuthChangePasswordPostResponseToJSONTyped(json, false);
}

export function AuthenticationChangePasswordApiV1AuthChangePasswordPostResponseToJSONTyped(value?: AuthenticationChangePasswordApiV1AuthChangePasswordPostResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
    };
}

