/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationLoginApiV1AuthLoginPostRequest
 */
export interface AuthenticationLoginApiV1AuthLoginPostRequest {
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    password: string;
}

/**
 * Check if a given object implements the AuthenticationLoginApiV1AuthLoginPostRequest interface.
 */
export function instanceOfAuthenticationLoginApiV1AuthLoginPostRequest(value: object): value is AuthenticationLoginApiV1AuthLoginPostRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function AuthenticationLoginApiV1AuthLoginPostRequestFromJSON(json: any): AuthenticationLoginApiV1AuthLoginPostRequest {
    return AuthenticationLoginApiV1AuthLoginPostRequestFromJSONTyped(json, false);
}

export function AuthenticationLoginApiV1AuthLoginPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationLoginApiV1AuthLoginPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
    };
}

export function AuthenticationLoginApiV1AuthLoginPostRequestToJSON(json: any): AuthenticationLoginApiV1AuthLoginPostRequest {
    return AuthenticationLoginApiV1AuthLoginPostRequestToJSONTyped(json, false);
}

export function AuthenticationLoginApiV1AuthLoginPostRequestToJSONTyped(value?: AuthenticationLoginApiV1AuthLoginPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'password': value['password'],
    };
}

