/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationResetPasswordApiV1AuthResetPasswordPostRequest
 */
export interface AuthenticationResetPasswordApiV1AuthResetPasswordPostRequest {
    /**
     * 
     */
    newPassword: string;
    /**
     * 
     */
    resetToken: string;
}

/**
 * Check if a given object implements the AuthenticationResetPasswordApiV1AuthResetPasswordPostRequest interface.
 */
export function instanceOfAuthenticationResetPasswordApiV1AuthResetPasswordPostRequest(value: object): value is AuthenticationResetPasswordApiV1AuthResetPasswordPostRequest {
    if ((!('newPassword' in (value as Record<string, any>)) && !('new_password' in (value as Record<string, any>))) || ((value as Record<string, any>)['newPassword'] === undefined && (value as Record<string, any>)['new_password'] === undefined)) return false;
    if ((!('resetToken' in (value as Record<string, any>)) && !('reset_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['resetToken'] === undefined && (value as Record<string, any>)['reset_token'] === undefined)) return false;
    return true;
}

export function AuthenticationResetPasswordApiV1AuthResetPasswordPostRequestFromJSON(json: any): AuthenticationResetPasswordApiV1AuthResetPasswordPostRequest {
    return AuthenticationResetPasswordApiV1AuthResetPasswordPostRequestFromJSONTyped(json, false);
}

export function AuthenticationResetPasswordApiV1AuthResetPasswordPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationResetPasswordApiV1AuthResetPasswordPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'newPassword': json['new_password'],
        'resetToken': json['reset_token'],
    };
}

export function AuthenticationResetPasswordApiV1AuthResetPasswordPostRequestToJSON(json: any): AuthenticationResetPasswordApiV1AuthResetPasswordPostRequest {
    return AuthenticationResetPasswordApiV1AuthResetPasswordPostRequestToJSONTyped(json, false);
}

export function AuthenticationResetPasswordApiV1AuthResetPasswordPostRequestToJSONTyped(value?: AuthenticationResetPasswordApiV1AuthResetPasswordPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'new_password': value['newPassword'],
        'reset_token': value['resetToken'],
    };
}

