/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponse
 */
export interface AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponse {
    /**
     * 
     */
    message: string;
    /**
     * 
     */
    resetToken?: string | null;
}

/**
 * Check if a given object implements the AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponse interface.
 */
export function instanceOfAuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponse(value: object): value is AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponse {
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponseFromJSON(json: any): AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponse {
    return AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponseFromJSONTyped(json, false);
}

export function AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'message': json['message'],
        'resetToken': json['reset_token'] === undefined ? undefined : json['reset_token'] === null ? null : json['reset_token'],
    };
}

export function AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponseToJSON(json: any): AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponse {
    return AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponseToJSONTyped(json, false);
}

export function AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponseToJSONTyped(value?: AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'message': value['message'],
        'reset_token': value['resetToken'],
    };
}

