/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationUpdateMeApiV1AuthMePatchRequest
 */
export interface AuthenticationUpdateMeApiV1AuthMePatchRequest {
    /**
     * 
     */
    name?: string | null;
}

/**
 * Check if a given object implements the AuthenticationUpdateMeApiV1AuthMePatchRequest interface.
 */
export function instanceOfAuthenticationUpdateMeApiV1AuthMePatchRequest(value: object): value is AuthenticationUpdateMeApiV1AuthMePatchRequest {
    return true;
}

export function AuthenticationUpdateMeApiV1AuthMePatchRequestFromJSON(json: any): AuthenticationUpdateMeApiV1AuthMePatchRequest {
    return AuthenticationUpdateMeApiV1AuthMePatchRequestFromJSONTyped(json, false);
}

export function AuthenticationUpdateMeApiV1AuthMePatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationUpdateMeApiV1AuthMePatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
    };
}

export function AuthenticationUpdateMeApiV1AuthMePatchRequestToJSON(json: any): AuthenticationUpdateMeApiV1AuthMePatchRequest {
    return AuthenticationUpdateMeApiV1AuthMePatchRequestToJSONTyped(json, false);
}

export function AuthenticationUpdateMeApiV1AuthMePatchRequestToJSONTyped(value?: AuthenticationUpdateMeApiV1AuthMePatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

