/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthenticationRefreshApiV1AuthRefreshPostRequest
 */
export interface AuthenticationRefreshApiV1AuthRefreshPostRequest {
    /**
     * 
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the AuthenticationRefreshApiV1AuthRefreshPostRequest interface.
 */
export function instanceOfAuthenticationRefreshApiV1AuthRefreshPostRequest(value: object): value is AuthenticationRefreshApiV1AuthRefreshPostRequest {
    if ((!('refreshToken' in (value as Record<string, any>)) && !('refresh_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['refreshToken'] === undefined && (value as Record<string, any>)['refresh_token'] === undefined)) return false;
    return true;
}

export function AuthenticationRefreshApiV1AuthRefreshPostRequestFromJSON(json: any): AuthenticationRefreshApiV1AuthRefreshPostRequest {
    return AuthenticationRefreshApiV1AuthRefreshPostRequestFromJSONTyped(json, false);
}

export function AuthenticationRefreshApiV1AuthRefreshPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthenticationRefreshApiV1AuthRefreshPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'refreshToken': json['refresh_token'],
    };
}

export function AuthenticationRefreshApiV1AuthRefreshPostRequestToJSON(json: any): AuthenticationRefreshApiV1AuthRefreshPostRequest {
    return AuthenticationRefreshApiV1AuthRefreshPostRequestToJSONTyped(json, false);
}

export function AuthenticationRefreshApiV1AuthRefreshPostRequestToJSONTyped(value?: AuthenticationRefreshApiV1AuthRefreshPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'refresh_token': value['refreshToken'],
    };
}

