/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DefaultRootResponse
 */
export interface DefaultRootResponse {
    /**
     * 
     */
    documentation: string;
    /**
     * 
     */
    health: string;
    /**
     * 
     */
    mockDocumentation: string;
    /**
     * 
     */
    mockOpenapi: string;
    /**
     * 
     */
    mockSchemas: string;
    /**
     * 
     */
    mockTestUi: string;
    /**
     * 
     */
    name: any | null;
    /**
     * 
     */
    openapi: string;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    version: string;
}

/**
 * Check if a given object implements the DefaultRootResponse interface.
 */
export function instanceOfDefaultRootResponse(value: object): value is DefaultRootResponse {
    if (!('documentation' in value) || value['documentation'] === undefined) return false;
    if (!('health' in value) || value['health'] === undefined) return false;
    if ((!('mockDocumentation' in (value as Record<string, any>)) && !('mock_documentation' in (value as Record<string, any>))) || ((value as Record<string, any>)['mockDocumentation'] === undefined && (value as Record<string, any>)['mock_documentation'] === undefined)) return false;
    if ((!('mockOpenapi' in (value as Record<string, any>)) && !('mock_openapi' in (value as Record<string, any>))) || ((value as Record<string, any>)['mockOpenapi'] === undefined && (value as Record<string, any>)['mock_openapi'] === undefined)) return false;
    if ((!('mockSchemas' in (value as Record<string, any>)) && !('mock_schemas' in (value as Record<string, any>))) || ((value as Record<string, any>)['mockSchemas'] === undefined && (value as Record<string, any>)['mock_schemas'] === undefined)) return false;
    if ((!('mockTestUi' in (value as Record<string, any>)) && !('mock_test_ui' in (value as Record<string, any>))) || ((value as Record<string, any>)['mockTestUi'] === undefined && (value as Record<string, any>)['mock_test_ui'] === undefined)) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('openapi' in value) || value['openapi'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function DefaultRootResponseFromJSON(json: any): DefaultRootResponse {
    return DefaultRootResponseFromJSONTyped(json, false);
}

export function DefaultRootResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): DefaultRootResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'documentation': json['documentation'],
        'health': json['health'],
        'mockDocumentation': json['mock_documentation'],
        'mockOpenapi': json['mock_openapi'],
        'mockSchemas': json['mock_schemas'],
        'mockTestUi': json['mock_test_ui'],
        'name': json['name'],
        'openapi': json['openapi'],
        'status': json['status'],
        'version': json['version'],
    };
}

export function DefaultRootResponseToJSON(json: any): DefaultRootResponse {
    return DefaultRootResponseToJSONTyped(json, false);
}

export function DefaultRootResponseToJSONTyped(value?: DefaultRootResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'documentation': value['documentation'],
        'health': value['health'],
        'mock_documentation': value['mockDocumentation'],
        'mock_openapi': value['mockOpenapi'],
        'mock_schemas': value['mockSchemas'],
        'mock_test_ui': value['mockTestUi'],
        'name': value['name'],
        'openapi': value['openapi'],
        'status': value['status'],
        'version': value['version'],
    };
}

