/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderItem } from './OrderItem';
import {
    OrderItemFromJSON,
    OrderItemFromJSONTyped,
    OrderItemToJSON,
    OrderItemToJSONTyped,
} from './OrderItem';

/**
 * 
 * @export
 * @interface MockOrdersMockUpdateOrderRequest
 */
export interface MockOrdersMockUpdateOrderRequest {
    /**
     * 
     */
    customerId?: string;
    /**
     * 
     */
    items?: Array<OrderItem>;
    /**
     * 
     */
    notes?: string;
    /**
     * 
     */
    shippingAddress?: string;
    /**
     * 
     */
    status?: MockOrdersMockUpdateOrderRequestStatusEnum;
}


/**
 * @export
 */
export const MockOrdersMockUpdateOrderRequestStatusEnum = {
    Pending: 'pending',
    Paid: 'paid',
    Shipped: 'shipped',
    Delivered: 'delivered',
    Cancelled: 'cancelled',
} as const;
export type MockOrdersMockUpdateOrderRequestStatusEnum = typeof MockOrdersMockUpdateOrderRequestStatusEnum[keyof typeof MockOrdersMockUpdateOrderRequestStatusEnum];


/**
 * Check if a given object implements the MockOrdersMockUpdateOrderRequest interface.
 */
export function instanceOfMockOrdersMockUpdateOrderRequest(value: object): value is MockOrdersMockUpdateOrderRequest {
    return true;
}

export function MockOrdersMockUpdateOrderRequestFromJSON(json: any): MockOrdersMockUpdateOrderRequest {
    return MockOrdersMockUpdateOrderRequestFromJSONTyped(json, false);
}

export function MockOrdersMockUpdateOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockOrdersMockUpdateOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'customerId': json['customer_id'] == null ? undefined : json['customer_id'],
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(OrderItemFromJSON)),
        'notes': json['notes'] == null ? undefined : json['notes'],
        'shippingAddress': json['shipping_address'] == null ? undefined : json['shipping_address'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function MockOrdersMockUpdateOrderRequestToJSON(json: any): MockOrdersMockUpdateOrderRequest {
    return MockOrdersMockUpdateOrderRequestToJSONTyped(json, false);
}

export function MockOrdersMockUpdateOrderRequestToJSONTyped(value?: MockOrdersMockUpdateOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customer_id': value['customerId'],
        'items': value['items'] == null ? undefined : ((value['items'] as Array<any>).map(OrderItemToJSON)),
        'notes': value['notes'],
        'shipping_address': value['shippingAddress'],
        'status': value['status'],
    };
}

