/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MockReviewsMockUpdateReviewRequest
 */
export interface MockReviewsMockUpdateReviewRequest {
    /**
     * 
     */
    body?: string;
    /**
     * 
     */
    customerId?: string;
    /**
     * 
     */
    productId?: string;
    /**
     * 
     */
    rating?: number;
    /**
     * 
     */
    title?: string;
}

/**
 * Check if a given object implements the MockReviewsMockUpdateReviewRequest interface.
 */
export function instanceOfMockReviewsMockUpdateReviewRequest(value: object): value is MockReviewsMockUpdateReviewRequest {
    return true;
}

export function MockReviewsMockUpdateReviewRequestFromJSON(json: any): MockReviewsMockUpdateReviewRequest {
    return MockReviewsMockUpdateReviewRequestFromJSONTyped(json, false);
}

export function MockReviewsMockUpdateReviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockReviewsMockUpdateReviewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'] == null ? undefined : json['body'],
        'customerId': json['customer_id'] == null ? undefined : json['customer_id'],
        'productId': json['product_id'] == null ? undefined : json['product_id'],
        'rating': json['rating'] == null ? undefined : json['rating'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function MockReviewsMockUpdateReviewRequestToJSON(json: any): MockReviewsMockUpdateReviewRequest {
    return MockReviewsMockUpdateReviewRequestToJSONTyped(json, false);
}

export function MockReviewsMockUpdateReviewRequestToJSONTyped(value?: MockReviewsMockUpdateReviewRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
        'customer_id': value['customerId'],
        'product_id': value['productId'],
        'rating': value['rating'],
        'title': value['title'],
    };
}

