/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface MockCustomersMockCreateCustomerResponse
 */
export interface MockCustomersMockCreateCustomerResponse {
    /**
     * 
     */
    company?: string;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    phone?: string;
    /**
     * 
     */
    status?: MockCustomersMockCreateCustomerResponseStatusEnum;
    /**
     * 
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const MockCustomersMockCreateCustomerResponseStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Lead: 'lead',
} as const;
export type MockCustomersMockCreateCustomerResponseStatusEnum = typeof MockCustomersMockCreateCustomerResponseStatusEnum[keyof typeof MockCustomersMockCreateCustomerResponseStatusEnum];


/**
 * Check if a given object implements the MockCustomersMockCreateCustomerResponse interface.
 */
export function instanceOfMockCustomersMockCreateCustomerResponse(value: object): value is MockCustomersMockCreateCustomerResponse {
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function MockCustomersMockCreateCustomerResponseFromJSON(json: any): MockCustomersMockCreateCustomerResponse {
    return MockCustomersMockCreateCustomerResponseFromJSONTyped(json, false);
}

export function MockCustomersMockCreateCustomerResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockCustomersMockCreateCustomerResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'company': json['company'] == null ? undefined : json['company'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'email': json['email'],
        'id': json['id'],
        'name': json['name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'status': json['status'] == null ? undefined : json['status'],
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
    };
}

export function MockCustomersMockCreateCustomerResponseToJSON(json: any): MockCustomersMockCreateCustomerResponse {
    return MockCustomersMockCreateCustomerResponseToJSONTyped(json, false);
}

export function MockCustomersMockCreateCustomerResponseToJSONTyped(value?: MockCustomersMockCreateCustomerResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company': value['company'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'email': value['email'],
        'id': value['id'],
        'name': value['name'],
        'phone': value['phone'],
        'status': value['status'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}

