/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MockReviewsMockCreateReviewResponse } from './MockReviewsMockCreateReviewResponse';
import {
    MockReviewsMockCreateReviewResponseFromJSON,
    MockReviewsMockCreateReviewResponseFromJSONTyped,
    MockReviewsMockCreateReviewResponseToJSON,
    MockReviewsMockCreateReviewResponseToJSONTyped,
} from './MockReviewsMockCreateReviewResponse';

/**
 * 
 * @export
 * @interface MockReviewsMockListReviewsResponse
 */
export interface MockReviewsMockListReviewsResponse {
    /**
     * 
     */
    items: Array<MockReviewsMockCreateReviewResponse>;
    /**
     * 
     */
    limit: number;
    /**
     * 
     */
    offset: number;
    /**
     * 
     */
    total: number;
}

/**
 * Check if a given object implements the MockReviewsMockListReviewsResponse interface.
 */
export function instanceOfMockReviewsMockListReviewsResponse(value: object): value is MockReviewsMockListReviewsResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function MockReviewsMockListReviewsResponseFromJSON(json: any): MockReviewsMockListReviewsResponse {
    return MockReviewsMockListReviewsResponseFromJSONTyped(json, false);
}

export function MockReviewsMockListReviewsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockReviewsMockListReviewsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(MockReviewsMockCreateReviewResponseFromJSON)),
        'limit': json['limit'],
        'offset': json['offset'],
        'total': json['total'],
    };
}

export function MockReviewsMockListReviewsResponseToJSON(json: any): MockReviewsMockListReviewsResponse {
    return MockReviewsMockListReviewsResponseToJSONTyped(json, false);
}

export function MockReviewsMockListReviewsResponseToJSONTyped(value?: MockReviewsMockListReviewsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(MockReviewsMockCreateReviewResponseToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

