/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MockProductsMockUpdateProductRequest
 */
export interface MockProductsMockUpdateProductRequest {
    /**
     * 
     */
    active?: boolean;
    /**
     * 
     */
    category?: string;
    /**
     * 
     */
    description?: string;
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    priceCents?: number;
    /**
     * 
     */
    sku?: string;
    /**
     * 
     */
    stockQuantity?: number;
}

/**
 * Check if a given object implements the MockProductsMockUpdateProductRequest interface.
 */
export function instanceOfMockProductsMockUpdateProductRequest(value: object): value is MockProductsMockUpdateProductRequest {
    return true;
}

export function MockProductsMockUpdateProductRequestFromJSON(json: any): MockProductsMockUpdateProductRequest {
    return MockProductsMockUpdateProductRequestFromJSONTyped(json, false);
}

export function MockProductsMockUpdateProductRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockProductsMockUpdateProductRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'] == null ? undefined : json['active'],
        'category': json['category'] == null ? undefined : json['category'],
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
        'priceCents': json['price_cents'] == null ? undefined : json['price_cents'],
        'sku': json['sku'] == null ? undefined : json['sku'],
        'stockQuantity': json['stock_quantity'] == null ? undefined : json['stock_quantity'],
    };
}

export function MockProductsMockUpdateProductRequestToJSON(json: any): MockProductsMockUpdateProductRequest {
    return MockProductsMockUpdateProductRequestToJSONTyped(json, false);
}

export function MockProductsMockUpdateProductRequestToJSONTyped(value?: MockProductsMockUpdateProductRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'category': value['category'],
        'description': value['description'],
        'name': value['name'],
        'price_cents': value['priceCents'],
        'sku': value['sku'],
        'stock_quantity': value['stockQuantity'],
    };
}

