/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MockReviewsMockReplaceReviewRequest
 */
export interface MockReviewsMockReplaceReviewRequest {
    /**
     * 
     */
    body: string;
    /**
     * 
     */
    customerId: string;
    /**
     * 
     */
    productId: string;
    /**
     * 
     */
    rating: number;
    /**
     * 
     */
    title: string;
}

/**
 * Check if a given object implements the MockReviewsMockReplaceReviewRequest interface.
 */
export function instanceOfMockReviewsMockReplaceReviewRequest(value: object): value is MockReviewsMockReplaceReviewRequest {
    if (!('body' in value) || value['body'] === undefined) return false;
    if ((!('customerId' in (value as Record<string, any>)) && !('customer_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['customerId'] === undefined && (value as Record<string, any>)['customer_id'] === undefined)) return false;
    if ((!('productId' in (value as Record<string, any>)) && !('product_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['productId'] === undefined && (value as Record<string, any>)['product_id'] === undefined)) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function MockReviewsMockReplaceReviewRequestFromJSON(json: any): MockReviewsMockReplaceReviewRequest {
    return MockReviewsMockReplaceReviewRequestFromJSONTyped(json, false);
}

export function MockReviewsMockReplaceReviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockReviewsMockReplaceReviewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'],
        'customerId': json['customer_id'],
        'productId': json['product_id'],
        'rating': json['rating'],
        'title': json['title'],
    };
}

export function MockReviewsMockReplaceReviewRequestToJSON(json: any): MockReviewsMockReplaceReviewRequest {
    return MockReviewsMockReplaceReviewRequestToJSONTyped(json, false);
}

export function MockReviewsMockReplaceReviewRequestToJSONTyped(value?: MockReviewsMockReplaceReviewRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
        'customer_id': value['customerId'],
        'product_id': value['productId'],
        'rating': value['rating'],
        'title': value['title'],
    };
}

