/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MockCustomersMockReplaceCustomerRequest
 */
export interface MockCustomersMockReplaceCustomerRequest {
    /**
     * 
     */
    company: string;
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    phone: string;
    /**
     * 
     */
    status: MockCustomersMockReplaceCustomerRequestStatusEnum;
}


/**
 * @export
 */
export const MockCustomersMockReplaceCustomerRequestStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Lead: 'lead',
} as const;
export type MockCustomersMockReplaceCustomerRequestStatusEnum = typeof MockCustomersMockReplaceCustomerRequestStatusEnum[keyof typeof MockCustomersMockReplaceCustomerRequestStatusEnum];


/**
 * Check if a given object implements the MockCustomersMockReplaceCustomerRequest interface.
 */
export function instanceOfMockCustomersMockReplaceCustomerRequest(value: object): value is MockCustomersMockReplaceCustomerRequest {
    if (!('company' in value) || value['company'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function MockCustomersMockReplaceCustomerRequestFromJSON(json: any): MockCustomersMockReplaceCustomerRequest {
    return MockCustomersMockReplaceCustomerRequestFromJSONTyped(json, false);
}

export function MockCustomersMockReplaceCustomerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockCustomersMockReplaceCustomerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'company': json['company'],
        'email': json['email'],
        'name': json['name'],
        'phone': json['phone'],
        'status': json['status'],
    };
}

export function MockCustomersMockReplaceCustomerRequestToJSON(json: any): MockCustomersMockReplaceCustomerRequest {
    return MockCustomersMockReplaceCustomerRequestToJSONTyped(json, false);
}

export function MockCustomersMockReplaceCustomerRequestToJSONTyped(value?: MockCustomersMockReplaceCustomerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company': value['company'],
        'email': value['email'],
        'name': value['name'],
        'phone': value['phone'],
        'status': value['status'],
    };
}

