/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { OrderItem } from './OrderItem';
import {
    OrderItemFromJSON,
    OrderItemFromJSONTyped,
    OrderItemToJSON,
    OrderItemToJSONTyped,
} from './OrderItem';

/**
 * 
 * @export
 * @interface MockOrdersMockCreateOrderResponse
 */
export interface MockOrdersMockCreateOrderResponse {
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    customerId: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    items: Array<OrderItem>;
    /**
     * 
     */
    notes?: string;
    /**
     * 
     */
    shippingAddress: string;
    /**
     * 
     */
    status?: MockOrdersMockCreateOrderResponseStatusEnum;
    /**
     * 
     */
    totalCents: number;
    /**
     * 
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const MockOrdersMockCreateOrderResponseStatusEnum = {
    Pending: 'pending',
    Paid: 'paid',
    Shipped: 'shipped',
    Delivered: 'delivered',
    Cancelled: 'cancelled',
} as const;
export type MockOrdersMockCreateOrderResponseStatusEnum = typeof MockOrdersMockCreateOrderResponseStatusEnum[keyof typeof MockOrdersMockCreateOrderResponseStatusEnum];


/**
 * Check if a given object implements the MockOrdersMockCreateOrderResponse interface.
 */
export function instanceOfMockOrdersMockCreateOrderResponse(value: object): value is MockOrdersMockCreateOrderResponse {
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('customerId' in (value as Record<string, any>)) && !('customer_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['customerId'] === undefined && (value as Record<string, any>)['customer_id'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if ((!('shippingAddress' in (value as Record<string, any>)) && !('shipping_address' in (value as Record<string, any>))) || ((value as Record<string, any>)['shippingAddress'] === undefined && (value as Record<string, any>)['shipping_address'] === undefined)) return false;
    if ((!('totalCents' in (value as Record<string, any>)) && !('total_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['totalCents'] === undefined && (value as Record<string, any>)['total_cents'] === undefined)) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function MockOrdersMockCreateOrderResponseFromJSON(json: any): MockOrdersMockCreateOrderResponse {
    return MockOrdersMockCreateOrderResponseFromJSONTyped(json, false);
}

export function MockOrdersMockCreateOrderResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockOrdersMockCreateOrderResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'customerId': json['customer_id'],
        'id': json['id'],
        'items': ((json['items'] as Array<any>).map(OrderItemFromJSON)),
        'notes': json['notes'] == null ? undefined : json['notes'],
        'shippingAddress': json['shipping_address'],
        'status': json['status'] == null ? undefined : json['status'],
        'totalCents': json['total_cents'],
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
    };
}

export function MockOrdersMockCreateOrderResponseToJSON(json: any): MockOrdersMockCreateOrderResponse {
    return MockOrdersMockCreateOrderResponseToJSONTyped(json, false);
}

export function MockOrdersMockCreateOrderResponseToJSONTyped(value?: MockOrdersMockCreateOrderResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'customer_id': value['customerId'],
        'id': value['id'],
        'items': ((value['items'] as Array<any>).map(OrderItemToJSON)),
        'notes': value['notes'],
        'shipping_address': value['shippingAddress'],
        'status': value['status'],
        'total_cents': value['totalCents'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}

