/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MockCustomersMockCreateCustomerResponse } from './MockCustomersMockCreateCustomerResponse';
import {
    MockCustomersMockCreateCustomerResponseFromJSON,
    MockCustomersMockCreateCustomerResponseFromJSONTyped,
    MockCustomersMockCreateCustomerResponseToJSON,
    MockCustomersMockCreateCustomerResponseToJSONTyped,
} from './MockCustomersMockCreateCustomerResponse';

/**
 * 
 * @export
 * @interface MockCustomersMockListCustomersResponse
 */
export interface MockCustomersMockListCustomersResponse {
    /**
     * 
     */
    items: Array<MockCustomersMockCreateCustomerResponse>;
    /**
     * 
     */
    limit: number;
    /**
     * 
     */
    offset: number;
    /**
     * 
     */
    total: number;
}

/**
 * Check if a given object implements the MockCustomersMockListCustomersResponse interface.
 */
export function instanceOfMockCustomersMockListCustomersResponse(value: object): value is MockCustomersMockListCustomersResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function MockCustomersMockListCustomersResponseFromJSON(json: any): MockCustomersMockListCustomersResponse {
    return MockCustomersMockListCustomersResponseFromJSONTyped(json, false);
}

export function MockCustomersMockListCustomersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockCustomersMockListCustomersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(MockCustomersMockCreateCustomerResponseFromJSON)),
        'limit': json['limit'],
        'offset': json['offset'],
        'total': json['total'],
    };
}

export function MockCustomersMockListCustomersResponseToJSON(json: any): MockCustomersMockListCustomersResponse {
    return MockCustomersMockListCustomersResponseToJSONTyped(json, false);
}

export function MockCustomersMockListCustomersResponseToJSONTyped(value?: MockCustomersMockListCustomersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(MockCustomersMockCreateCustomerResponseToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

