/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MockProductsMockCreateProductResponse } from './MockProductsMockCreateProductResponse';
import {
    MockProductsMockCreateProductResponseFromJSON,
    MockProductsMockCreateProductResponseFromJSONTyped,
    MockProductsMockCreateProductResponseToJSON,
    MockProductsMockCreateProductResponseToJSONTyped,
} from './MockProductsMockCreateProductResponse';

/**
 * 
 * @export
 * @interface MockProductsMockListProductsResponse
 */
export interface MockProductsMockListProductsResponse {
    /**
     * 
     */
    items: Array<MockProductsMockCreateProductResponse>;
    /**
     * 
     */
    limit: number;
    /**
     * 
     */
    offset: number;
    /**
     * 
     */
    total: number;
}

/**
 * Check if a given object implements the MockProductsMockListProductsResponse interface.
 */
export function instanceOfMockProductsMockListProductsResponse(value: object): value is MockProductsMockListProductsResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function MockProductsMockListProductsResponseFromJSON(json: any): MockProductsMockListProductsResponse {
    return MockProductsMockListProductsResponseFromJSONTyped(json, false);
}

export function MockProductsMockListProductsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockProductsMockListProductsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(MockProductsMockCreateProductResponseFromJSON)),
        'limit': json['limit'],
        'offset': json['offset'],
        'total': json['total'],
    };
}

export function MockProductsMockListProductsResponseToJSON(json: any): MockProductsMockListProductsResponse {
    return MockProductsMockListProductsResponseToJSONTyped(json, false);
}

export function MockProductsMockListProductsResponseToJSONTyped(value?: MockProductsMockListProductsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(MockProductsMockCreateProductResponseToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

