/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OrderItem } from './OrderItem';
import {
    OrderItemFromJSON,
    OrderItemFromJSONTyped,
    OrderItemToJSON,
    OrderItemToJSONTyped,
} from './OrderItem';

/**
 * 
 * @export
 * @interface MockOrdersMockCreateOrderRequest
 */
export interface MockOrdersMockCreateOrderRequest {
    /**
     * 
     */
    customerId: string;
    /**
     * 
     */
    items: Array<OrderItem>;
    /**
     * 
     */
    notes?: string;
    /**
     * 
     */
    shippingAddress: string;
    /**
     * 
     */
    status?: MockOrdersMockCreateOrderRequestStatusEnum;
}


/**
 * @export
 */
export const MockOrdersMockCreateOrderRequestStatusEnum = {
    Pending: 'pending',
    Paid: 'paid',
    Shipped: 'shipped',
    Delivered: 'delivered',
    Cancelled: 'cancelled',
} as const;
export type MockOrdersMockCreateOrderRequestStatusEnum = typeof MockOrdersMockCreateOrderRequestStatusEnum[keyof typeof MockOrdersMockCreateOrderRequestStatusEnum];


/**
 * Check if a given object implements the MockOrdersMockCreateOrderRequest interface.
 */
export function instanceOfMockOrdersMockCreateOrderRequest(value: object): value is MockOrdersMockCreateOrderRequest {
    if ((!('customerId' in (value as Record<string, any>)) && !('customer_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['customerId'] === undefined && (value as Record<string, any>)['customer_id'] === undefined)) return false;
    if (!('items' in value) || value['items'] === undefined) return false;
    if ((!('shippingAddress' in (value as Record<string, any>)) && !('shipping_address' in (value as Record<string, any>))) || ((value as Record<string, any>)['shippingAddress'] === undefined && (value as Record<string, any>)['shipping_address'] === undefined)) return false;
    return true;
}

export function MockOrdersMockCreateOrderRequestFromJSON(json: any): MockOrdersMockCreateOrderRequest {
    return MockOrdersMockCreateOrderRequestFromJSONTyped(json, false);
}

export function MockOrdersMockCreateOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockOrdersMockCreateOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'customerId': json['customer_id'],
        'items': ((json['items'] as Array<any>).map(OrderItemFromJSON)),
        'notes': json['notes'] == null ? undefined : json['notes'],
        'shippingAddress': json['shipping_address'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function MockOrdersMockCreateOrderRequestToJSON(json: any): MockOrdersMockCreateOrderRequest {
    return MockOrdersMockCreateOrderRequestToJSONTyped(json, false);
}

export function MockOrdersMockCreateOrderRequestToJSONTyped(value?: MockOrdersMockCreateOrderRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'customer_id': value['customerId'],
        'items': ((value['items'] as Array<any>).map(OrderItemToJSON)),
        'notes': value['notes'],
        'shipping_address': value['shippingAddress'],
        'status': value['status'],
    };
}

