/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface MockProductsMockCreateProductResponse
 */
export interface MockProductsMockCreateProductResponse {
    /**
     * 
     */
    active?: boolean;
    /**
     * 
     */
    category?: string;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    description?: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    priceCents: number;
    /**
     * 
     */
    sku: string;
    /**
     * 
     */
    stockQuantity?: number;
    /**
     * 
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the MockProductsMockCreateProductResponse interface.
 */
export function instanceOfMockProductsMockCreateProductResponse(value: object): value is MockProductsMockCreateProductResponse {
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('priceCents' in (value as Record<string, any>)) && !('price_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['priceCents'] === undefined && (value as Record<string, any>)['price_cents'] === undefined)) return false;
    if (!('sku' in value) || value['sku'] === undefined) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function MockProductsMockCreateProductResponseFromJSON(json: any): MockProductsMockCreateProductResponse {
    return MockProductsMockCreateProductResponseFromJSONTyped(json, false);
}

export function MockProductsMockCreateProductResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockProductsMockCreateProductResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'] == null ? undefined : json['active'],
        'category': json['category'] == null ? undefined : json['category'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'],
        'name': json['name'],
        'priceCents': json['price_cents'],
        'sku': json['sku'],
        'stockQuantity': json['stock_quantity'] == null ? undefined : json['stock_quantity'],
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
    };
}

export function MockProductsMockCreateProductResponseToJSON(json: any): MockProductsMockCreateProductResponse {
    return MockProductsMockCreateProductResponseToJSONTyped(json, false);
}

export function MockProductsMockCreateProductResponseToJSONTyped(value?: MockProductsMockCreateProductResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'category': value['category'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
        'price_cents': value['priceCents'],
        'sku': value['sku'],
        'stock_quantity': value['stockQuantity'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}

