/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MockProductsMockReplaceProductRequest
 */
export interface MockProductsMockReplaceProductRequest {
    /**
     * 
     */
    active: boolean;
    /**
     * 
     */
    category: string;
    /**
     * 
     */
    description: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    priceCents: number;
    /**
     * 
     */
    sku: string;
    /**
     * 
     */
    stockQuantity: number;
}

/**
 * Check if a given object implements the MockProductsMockReplaceProductRequest interface.
 */
export function instanceOfMockProductsMockReplaceProductRequest(value: object): value is MockProductsMockReplaceProductRequest {
    if (!('active' in value) || value['active'] === undefined) return false;
    if (!('category' in value) || value['category'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('priceCents' in (value as Record<string, any>)) && !('price_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['priceCents'] === undefined && (value as Record<string, any>)['price_cents'] === undefined)) return false;
    if (!('sku' in value) || value['sku'] === undefined) return false;
    if ((!('stockQuantity' in (value as Record<string, any>)) && !('stock_quantity' in (value as Record<string, any>))) || ((value as Record<string, any>)['stockQuantity'] === undefined && (value as Record<string, any>)['stock_quantity'] === undefined)) return false;
    return true;
}

export function MockProductsMockReplaceProductRequestFromJSON(json: any): MockProductsMockReplaceProductRequest {
    return MockProductsMockReplaceProductRequestFromJSONTyped(json, false);
}

export function MockProductsMockReplaceProductRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockProductsMockReplaceProductRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'],
        'category': json['category'],
        'description': json['description'],
        'name': json['name'],
        'priceCents': json['price_cents'],
        'sku': json['sku'],
        'stockQuantity': json['stock_quantity'],
    };
}

export function MockProductsMockReplaceProductRequestToJSON(json: any): MockProductsMockReplaceProductRequest {
    return MockProductsMockReplaceProductRequestToJSONTyped(json, false);
}

export function MockProductsMockReplaceProductRequestToJSONTyped(value?: MockProductsMockReplaceProductRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'category': value['category'],
        'description': value['description'],
        'name': value['name'],
        'price_cents': value['priceCents'],
        'sku': value['sku'],
        'stock_quantity': value['stockQuantity'],
    };
}

