/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MockTicketsMockReplaceTicketRequest
 */
export interface MockTicketsMockReplaceTicketRequest {
    /**
     * 
     */
    assignee: string;
    /**
     * 
     */
    customerId: string;
    /**
     * 
     */
    description: string;
    /**
     * 
     */
    priority: MockTicketsMockReplaceTicketRequestPriorityEnum;
    /**
     * 
     */
    status: MockTicketsMockReplaceTicketRequestStatusEnum;
    /**
     * 
     */
    subject: string;
}


/**
 * @export
 */
export const MockTicketsMockReplaceTicketRequestPriorityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Urgent: 'urgent',
} as const;
export type MockTicketsMockReplaceTicketRequestPriorityEnum = typeof MockTicketsMockReplaceTicketRequestPriorityEnum[keyof typeof MockTicketsMockReplaceTicketRequestPriorityEnum];

/**
 * @export
 */
export const MockTicketsMockReplaceTicketRequestStatusEnum = {
    Open: 'open',
    InProgress: 'in_progress',
    Resolved: 'resolved',
    Closed: 'closed',
} as const;
export type MockTicketsMockReplaceTicketRequestStatusEnum = typeof MockTicketsMockReplaceTicketRequestStatusEnum[keyof typeof MockTicketsMockReplaceTicketRequestStatusEnum];


/**
 * Check if a given object implements the MockTicketsMockReplaceTicketRequest interface.
 */
export function instanceOfMockTicketsMockReplaceTicketRequest(value: object): value is MockTicketsMockReplaceTicketRequest {
    if (!('assignee' in value) || value['assignee'] === undefined) return false;
    if ((!('customerId' in (value as Record<string, any>)) && !('customer_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['customerId'] === undefined && (value as Record<string, any>)['customer_id'] === undefined)) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    return true;
}

export function MockTicketsMockReplaceTicketRequestFromJSON(json: any): MockTicketsMockReplaceTicketRequest {
    return MockTicketsMockReplaceTicketRequestFromJSONTyped(json, false);
}

export function MockTicketsMockReplaceTicketRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockTicketsMockReplaceTicketRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'assignee': json['assignee'],
        'customerId': json['customer_id'],
        'description': json['description'],
        'priority': json['priority'],
        'status': json['status'],
        'subject': json['subject'],
    };
}

export function MockTicketsMockReplaceTicketRequestToJSON(json: any): MockTicketsMockReplaceTicketRequest {
    return MockTicketsMockReplaceTicketRequestToJSONTyped(json, false);
}

export function MockTicketsMockReplaceTicketRequestToJSONTyped(value?: MockTicketsMockReplaceTicketRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assignee': value['assignee'],
        'customer_id': value['customerId'],
        'description': value['description'],
        'priority': value['priority'],
        'status': value['status'],
        'subject': value['subject'],
    };
}

