/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MockCustomersMockUpdateCustomerRequest
 */
export interface MockCustomersMockUpdateCustomerRequest {
    /**
     * 
     */
    company?: string;
    /**
     * 
     */
    email?: string;
    /**
     * 
     */
    name?: string;
    /**
     * 
     */
    phone?: string;
    /**
     * 
     */
    status?: MockCustomersMockUpdateCustomerRequestStatusEnum;
}


/**
 * @export
 */
export const MockCustomersMockUpdateCustomerRequestStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Lead: 'lead',
} as const;
export type MockCustomersMockUpdateCustomerRequestStatusEnum = typeof MockCustomersMockUpdateCustomerRequestStatusEnum[keyof typeof MockCustomersMockUpdateCustomerRequestStatusEnum];


/**
 * Check if a given object implements the MockCustomersMockUpdateCustomerRequest interface.
 */
export function instanceOfMockCustomersMockUpdateCustomerRequest(value: object): value is MockCustomersMockUpdateCustomerRequest {
    return true;
}

export function MockCustomersMockUpdateCustomerRequestFromJSON(json: any): MockCustomersMockUpdateCustomerRequest {
    return MockCustomersMockUpdateCustomerRequestFromJSONTyped(json, false);
}

export function MockCustomersMockUpdateCustomerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockCustomersMockUpdateCustomerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'company': json['company'] == null ? undefined : json['company'],
        'email': json['email'] == null ? undefined : json['email'],
        'name': json['name'] == null ? undefined : json['name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function MockCustomersMockUpdateCustomerRequestToJSON(json: any): MockCustomersMockUpdateCustomerRequest {
    return MockCustomersMockUpdateCustomerRequestToJSONTyped(json, false);
}

export function MockCustomersMockUpdateCustomerRequestToJSONTyped(value?: MockCustomersMockUpdateCustomerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company': value['company'],
        'email': value['email'],
        'name': value['name'],
        'phone': value['phone'],
        'status': value['status'],
    };
}

