/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MockTicketsMockCreateTicketResponse } from './MockTicketsMockCreateTicketResponse';
import {
    MockTicketsMockCreateTicketResponseFromJSON,
    MockTicketsMockCreateTicketResponseFromJSONTyped,
    MockTicketsMockCreateTicketResponseToJSON,
    MockTicketsMockCreateTicketResponseToJSONTyped,
} from './MockTicketsMockCreateTicketResponse';

/**
 * 
 * @export
 * @interface MockTicketsMockListTicketsResponse
 */
export interface MockTicketsMockListTicketsResponse {
    /**
     * 
     */
    items: Array<MockTicketsMockCreateTicketResponse>;
    /**
     * 
     */
    limit: number;
    /**
     * 
     */
    offset: number;
    /**
     * 
     */
    total: number;
}

/**
 * Check if a given object implements the MockTicketsMockListTicketsResponse interface.
 */
export function instanceOfMockTicketsMockListTicketsResponse(value: object): value is MockTicketsMockListTicketsResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function MockTicketsMockListTicketsResponseFromJSON(json: any): MockTicketsMockListTicketsResponse {
    return MockTicketsMockListTicketsResponseFromJSONTyped(json, false);
}

export function MockTicketsMockListTicketsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockTicketsMockListTicketsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(MockTicketsMockCreateTicketResponseFromJSON)),
        'limit': json['limit'],
        'offset': json['offset'],
        'total': json['total'],
    };
}

export function MockTicketsMockListTicketsResponseToJSON(json: any): MockTicketsMockListTicketsResponse {
    return MockTicketsMockListTicketsResponseToJSONTyped(json, false);
}

export function MockTicketsMockListTicketsResponseToJSONTyped(value?: MockTicketsMockListTicketsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(MockTicketsMockCreateTicketResponseToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

