/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface MockReviewsMockCreateReviewResponse
 */
export interface MockReviewsMockCreateReviewResponse {
    /**
     * 
     */
    body: string;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    customerId: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    productId: string;
    /**
     * 
     */
    rating: number;
    /**
     * 
     */
    title: string;
    /**
     * 
     */
    updatedAt: Date;
}

/**
 * Check if a given object implements the MockReviewsMockCreateReviewResponse interface.
 */
export function instanceOfMockReviewsMockCreateReviewResponse(value: object): value is MockReviewsMockCreateReviewResponse {
    if (!('body' in value) || value['body'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('customerId' in (value as Record<string, any>)) && !('customer_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['customerId'] === undefined && (value as Record<string, any>)['customer_id'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('productId' in (value as Record<string, any>)) && !('product_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['productId'] === undefined && (value as Record<string, any>)['product_id'] === undefined)) return false;
    if (!('rating' in value) || value['rating'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function MockReviewsMockCreateReviewResponseFromJSON(json: any): MockReviewsMockCreateReviewResponse {
    return MockReviewsMockCreateReviewResponseFromJSONTyped(json, false);
}

export function MockReviewsMockCreateReviewResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockReviewsMockCreateReviewResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'body': json['body'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'customerId': json['customer_id'],
        'id': json['id'],
        'productId': json['product_id'],
        'rating': json['rating'],
        'title': json['title'],
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
    };
}

export function MockReviewsMockCreateReviewResponseToJSON(json: any): MockReviewsMockCreateReviewResponse {
    return MockReviewsMockCreateReviewResponseToJSONTyped(json, false);
}

export function MockReviewsMockCreateReviewResponseToJSONTyped(value?: MockReviewsMockCreateReviewResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'body': value['body'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'customer_id': value['customerId'],
        'id': value['id'],
        'product_id': value['productId'],
        'rating': value['rating'],
        'title': value['title'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}

