/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MockTicketsMockUpdateTicketRequest
 */
export interface MockTicketsMockUpdateTicketRequest {
    /**
     * 
     */
    assignee?: string;
    /**
     * 
     */
    customerId?: string;
    /**
     * 
     */
    description?: string;
    /**
     * 
     */
    priority?: MockTicketsMockUpdateTicketRequestPriorityEnum;
    /**
     * 
     */
    status?: MockTicketsMockUpdateTicketRequestStatusEnum;
    /**
     * 
     */
    subject?: string;
}


/**
 * @export
 */
export const MockTicketsMockUpdateTicketRequestPriorityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Urgent: 'urgent',
} as const;
export type MockTicketsMockUpdateTicketRequestPriorityEnum = typeof MockTicketsMockUpdateTicketRequestPriorityEnum[keyof typeof MockTicketsMockUpdateTicketRequestPriorityEnum];

/**
 * @export
 */
export const MockTicketsMockUpdateTicketRequestStatusEnum = {
    Open: 'open',
    InProgress: 'in_progress',
    Resolved: 'resolved',
    Closed: 'closed',
} as const;
export type MockTicketsMockUpdateTicketRequestStatusEnum = typeof MockTicketsMockUpdateTicketRequestStatusEnum[keyof typeof MockTicketsMockUpdateTicketRequestStatusEnum];


/**
 * Check if a given object implements the MockTicketsMockUpdateTicketRequest interface.
 */
export function instanceOfMockTicketsMockUpdateTicketRequest(value: object): value is MockTicketsMockUpdateTicketRequest {
    return true;
}

export function MockTicketsMockUpdateTicketRequestFromJSON(json: any): MockTicketsMockUpdateTicketRequest {
    return MockTicketsMockUpdateTicketRequestFromJSONTyped(json, false);
}

export function MockTicketsMockUpdateTicketRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockTicketsMockUpdateTicketRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'assignee': json['assignee'] == null ? undefined : json['assignee'],
        'customerId': json['customer_id'] == null ? undefined : json['customer_id'],
        'description': json['description'] == null ? undefined : json['description'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'status': json['status'] == null ? undefined : json['status'],
        'subject': json['subject'] == null ? undefined : json['subject'],
    };
}

export function MockTicketsMockUpdateTicketRequestToJSON(json: any): MockTicketsMockUpdateTicketRequest {
    return MockTicketsMockUpdateTicketRequestToJSONTyped(json, false);
}

export function MockTicketsMockUpdateTicketRequestToJSONTyped(value?: MockTicketsMockUpdateTicketRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assignee': value['assignee'],
        'customer_id': value['customerId'],
        'description': value['description'],
        'priority': value['priority'],
        'status': value['status'],
        'subject': value['subject'],
    };
}

