/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MockOrdersMockCreateOrderResponse } from './MockOrdersMockCreateOrderResponse';
import {
    MockOrdersMockCreateOrderResponseFromJSON,
    MockOrdersMockCreateOrderResponseFromJSONTyped,
    MockOrdersMockCreateOrderResponseToJSON,
    MockOrdersMockCreateOrderResponseToJSONTyped,
} from './MockOrdersMockCreateOrderResponse';

/**
 * 
 * @export
 * @interface MockOrdersMockListOrdersResponse
 */
export interface MockOrdersMockListOrdersResponse {
    /**
     * 
     */
    items: Array<MockOrdersMockCreateOrderResponse>;
    /**
     * 
     */
    limit: number;
    /**
     * 
     */
    offset: number;
    /**
     * 
     */
    total: number;
}

/**
 * Check if a given object implements the MockOrdersMockListOrdersResponse interface.
 */
export function instanceOfMockOrdersMockListOrdersResponse(value: object): value is MockOrdersMockListOrdersResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function MockOrdersMockListOrdersResponseFromJSON(json: any): MockOrdersMockListOrdersResponse {
    return MockOrdersMockListOrdersResponseFromJSONTyped(json, false);
}

export function MockOrdersMockListOrdersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockOrdersMockListOrdersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(MockOrdersMockCreateOrderResponseFromJSON)),
        'limit': json['limit'],
        'offset': json['offset'],
        'total': json['total'],
    };
}

export function MockOrdersMockListOrdersResponseToJSON(json: any): MockOrdersMockListOrdersResponse {
    return MockOrdersMockListOrdersResponseToJSONTyped(json, false);
}

export function MockOrdersMockListOrdersResponseToJSONTyped(value?: MockOrdersMockListOrdersResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(MockOrdersMockCreateOrderResponseToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

