/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface MockTicketsMockCreateTicketResponse
 */
export interface MockTicketsMockCreateTicketResponse {
    /**
     * 
     */
    assignee?: string;
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    customerId: string;
    /**
     * 
     */
    description: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    priority?: MockTicketsMockCreateTicketResponsePriorityEnum;
    /**
     * 
     */
    status?: MockTicketsMockCreateTicketResponseStatusEnum;
    /**
     * 
     */
    subject: string;
    /**
     * 
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const MockTicketsMockCreateTicketResponsePriorityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Urgent: 'urgent',
} as const;
export type MockTicketsMockCreateTicketResponsePriorityEnum = typeof MockTicketsMockCreateTicketResponsePriorityEnum[keyof typeof MockTicketsMockCreateTicketResponsePriorityEnum];

/**
 * @export
 */
export const MockTicketsMockCreateTicketResponseStatusEnum = {
    Open: 'open',
    InProgress: 'in_progress',
    Resolved: 'resolved',
    Closed: 'closed',
} as const;
export type MockTicketsMockCreateTicketResponseStatusEnum = typeof MockTicketsMockCreateTicketResponseStatusEnum[keyof typeof MockTicketsMockCreateTicketResponseStatusEnum];


/**
 * Check if a given object implements the MockTicketsMockCreateTicketResponse interface.
 */
export function instanceOfMockTicketsMockCreateTicketResponse(value: object): value is MockTicketsMockCreateTicketResponse {
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('customerId' in (value as Record<string, any>)) && !('customer_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['customerId'] === undefined && (value as Record<string, any>)['customer_id'] === undefined)) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function MockTicketsMockCreateTicketResponseFromJSON(json: any): MockTicketsMockCreateTicketResponse {
    return MockTicketsMockCreateTicketResponseFromJSONTyped(json, false);
}

export function MockTicketsMockCreateTicketResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockTicketsMockCreateTicketResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'assignee': json['assignee'] == null ? undefined : json['assignee'],
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'customerId': json['customer_id'],
        'description': json['description'],
        'id': json['id'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'status': json['status'] == null ? undefined : json['status'],
        'subject': json['subject'],
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
    };
}

export function MockTicketsMockCreateTicketResponseToJSON(json: any): MockTicketsMockCreateTicketResponse {
    return MockTicketsMockCreateTicketResponseToJSONTyped(json, false);
}

export function MockTicketsMockCreateTicketResponseToJSONTyped(value?: MockTicketsMockCreateTicketResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assignee': value['assignee'],
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'customer_id': value['customerId'],
        'description': value['description'],
        'id': value['id'],
        'priority': value['priority'],
        'status': value['status'],
        'subject': value['subject'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}

