/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MockProductsMockCreateProductRequest
 */
export interface MockProductsMockCreateProductRequest {
    /**
     * 
     */
    active?: boolean;
    /**
     * 
     */
    category?: string;
    /**
     * 
     */
    description?: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    priceCents: number;
    /**
     * 
     */
    sku: string;
    /**
     * 
     */
    stockQuantity?: number;
}

/**
 * Check if a given object implements the MockProductsMockCreateProductRequest interface.
 */
export function instanceOfMockProductsMockCreateProductRequest(value: object): value is MockProductsMockCreateProductRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('priceCents' in (value as Record<string, any>)) && !('price_cents' in (value as Record<string, any>))) || ((value as Record<string, any>)['priceCents'] === undefined && (value as Record<string, any>)['price_cents'] === undefined)) return false;
    if (!('sku' in value) || value['sku'] === undefined) return false;
    return true;
}

export function MockProductsMockCreateProductRequestFromJSON(json: any): MockProductsMockCreateProductRequest {
    return MockProductsMockCreateProductRequestFromJSONTyped(json, false);
}

export function MockProductsMockCreateProductRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockProductsMockCreateProductRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'active': json['active'] == null ? undefined : json['active'],
        'category': json['category'] == null ? undefined : json['category'],
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'],
        'priceCents': json['price_cents'],
        'sku': json['sku'],
        'stockQuantity': json['stock_quantity'] == null ? undefined : json['stock_quantity'],
    };
}

export function MockProductsMockCreateProductRequestToJSON(json: any): MockProductsMockCreateProductRequest {
    return MockProductsMockCreateProductRequestToJSONTyped(json, false);
}

export function MockProductsMockCreateProductRequestToJSONTyped(value?: MockProductsMockCreateProductRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'active': value['active'],
        'category': value['category'],
        'description': value['description'],
        'name': value['name'],
        'price_cents': value['priceCents'],
        'sku': value['sku'],
        'stock_quantity': value['stockQuantity'],
    };
}

