/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MockTicketsMockCreateTicketRequest
 */
export interface MockTicketsMockCreateTicketRequest {
    /**
     * 
     */
    assignee?: string;
    /**
     * 
     */
    customerId: string;
    /**
     * 
     */
    description: string;
    /**
     * 
     */
    priority?: MockTicketsMockCreateTicketRequestPriorityEnum;
    /**
     * 
     */
    status?: MockTicketsMockCreateTicketRequestStatusEnum;
    /**
     * 
     */
    subject: string;
}


/**
 * @export
 */
export const MockTicketsMockCreateTicketRequestPriorityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Urgent: 'urgent',
} as const;
export type MockTicketsMockCreateTicketRequestPriorityEnum = typeof MockTicketsMockCreateTicketRequestPriorityEnum[keyof typeof MockTicketsMockCreateTicketRequestPriorityEnum];

/**
 * @export
 */
export const MockTicketsMockCreateTicketRequestStatusEnum = {
    Open: 'open',
    InProgress: 'in_progress',
    Resolved: 'resolved',
    Closed: 'closed',
} as const;
export type MockTicketsMockCreateTicketRequestStatusEnum = typeof MockTicketsMockCreateTicketRequestStatusEnum[keyof typeof MockTicketsMockCreateTicketRequestStatusEnum];


/**
 * Check if a given object implements the MockTicketsMockCreateTicketRequest interface.
 */
export function instanceOfMockTicketsMockCreateTicketRequest(value: object): value is MockTicketsMockCreateTicketRequest {
    if ((!('customerId' in (value as Record<string, any>)) && !('customer_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['customerId'] === undefined && (value as Record<string, any>)['customer_id'] === undefined)) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('subject' in value) || value['subject'] === undefined) return false;
    return true;
}

export function MockTicketsMockCreateTicketRequestFromJSON(json: any): MockTicketsMockCreateTicketRequest {
    return MockTicketsMockCreateTicketRequestFromJSONTyped(json, false);
}

export function MockTicketsMockCreateTicketRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockTicketsMockCreateTicketRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'assignee': json['assignee'] == null ? undefined : json['assignee'],
        'customerId': json['customer_id'],
        'description': json['description'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'status': json['status'] == null ? undefined : json['status'],
        'subject': json['subject'],
    };
}

export function MockTicketsMockCreateTicketRequestToJSON(json: any): MockTicketsMockCreateTicketRequest {
    return MockTicketsMockCreateTicketRequestToJSONTyped(json, false);
}

export function MockTicketsMockCreateTicketRequestToJSONTyped(value?: MockTicketsMockCreateTicketRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assignee': value['assignee'],
        'customer_id': value['customerId'],
        'description': value['description'],
        'priority': value['priority'],
        'status': value['status'],
        'subject': value['subject'],
    };
}

