/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MockCustomersMockCreateCustomerRequest
 */
export interface MockCustomersMockCreateCustomerRequest {
    /**
     * 
     */
    company?: string;
    /**
     * 
     */
    email: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    phone?: string;
    /**
     * 
     */
    status?: MockCustomersMockCreateCustomerRequestStatusEnum;
}


/**
 * @export
 */
export const MockCustomersMockCreateCustomerRequestStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Lead: 'lead',
} as const;
export type MockCustomersMockCreateCustomerRequestStatusEnum = typeof MockCustomersMockCreateCustomerRequestStatusEnum[keyof typeof MockCustomersMockCreateCustomerRequestStatusEnum];


/**
 * Check if a given object implements the MockCustomersMockCreateCustomerRequest interface.
 */
export function instanceOfMockCustomersMockCreateCustomerRequest(value: object): value is MockCustomersMockCreateCustomerRequest {
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function MockCustomersMockCreateCustomerRequestFromJSON(json: any): MockCustomersMockCreateCustomerRequest {
    return MockCustomersMockCreateCustomerRequestFromJSONTyped(json, false);
}

export function MockCustomersMockCreateCustomerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MockCustomersMockCreateCustomerRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'company': json['company'] == null ? undefined : json['company'],
        'email': json['email'],
        'name': json['name'],
        'phone': json['phone'] == null ? undefined : json['phone'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function MockCustomersMockCreateCustomerRequestToJSON(json: any): MockCustomersMockCreateCustomerRequest {
    return MockCustomersMockCreateCustomerRequestToJSONTyped(json, false);
}

export function MockCustomersMockCreateCustomerRequestToJSONTyped(value?: MockCustomersMockCreateCustomerRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'company': value['company'],
        'email': value['email'],
        'name': value['name'],
        'phone': value['phone'],
        'status': value['status'],
    };
}

