/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderItem
 */
export interface OrderItem {
    /**
     * 
     */
    productId: string;
    /**
     * 
     */
    quantity: number;
}

/**
 * Check if a given object implements the OrderItem interface.
 */
export function instanceOfOrderItem(value: object): value is OrderItem {
    if ((!('productId' in (value as Record<string, any>)) && !('product_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['productId'] === undefined && (value as Record<string, any>)['product_id'] === undefined)) return false;
    if (!('quantity' in value) || value['quantity'] === undefined) return false;
    return true;
}

export function OrderItemFromJSON(json: any): OrderItem {
    return OrderItemFromJSONTyped(json, false);
}

export function OrderItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderItem {
    if (json == null) {
        return json;
    }
    return {
        
        'productId': json['product_id'],
        'quantity': json['quantity'],
    };
}

export function OrderItemToJSON(json: any): OrderItem {
    return OrderItemToJSONTyped(json, false);
}

export function OrderItemToJSONTyped(value?: OrderItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'product_id': value['productId'],
        'quantity': value['quantity'],
    };
}

