/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * What a consumer reads before calling, and what the handler now ships.
 * @export
 * @interface PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponse
 */
export interface PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponse {
    /**
     * Amount returned to the customer, in whole currency units.
     */
    amountRefunded: number;
    /**
     * ISO 4217 code that `amount_refunded` is denominated in.
     */
    currency?: string;
    /**
     * Identifier of the refunded order.
     */
    orderId: string;
    /**
     * When the refund settled, as an RFC 3339 timestamp in UTC.
     */
    refundedAt: string;
    /**
     * Where the refund has got to: `pending` or `settled`.
     */
    state: string;
}

/**
 * Check if a given object implements the PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponse interface.
 */
export function instanceOfPremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponse(value: object): value is PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponse {
    if ((!('amountRefunded' in (value as Record<string, any>)) && !('amount_refunded' in (value as Record<string, any>))) || ((value as Record<string, any>)['amountRefunded'] === undefined && (value as Record<string, any>)['amount_refunded'] === undefined)) return false;
    if ((!('orderId' in (value as Record<string, any>)) && !('order_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orderId'] === undefined && (value as Record<string, any>)['order_id'] === undefined)) return false;
    if ((!('refundedAt' in (value as Record<string, any>)) && !('refunded_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['refundedAt'] === undefined && (value as Record<string, any>)['refunded_at'] === undefined)) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    return true;
}

export function PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponseFromJSON(json: any): PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponse {
    return PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponseFromJSONTyped(json, false);
}

export function PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'amountRefunded': json['amount_refunded'],
        'currency': json['currency'] == null ? undefined : json['currency'],
        'orderId': json['order_id'],
        'refundedAt': json['refunded_at'],
        'state': json['state'],
    };
}

export function PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponseToJSON(json: any): PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponse {
    return PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponseToJSONTyped(json, false);
}

export function PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponseToJSONTyped(value?: PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'amount_refunded': value['amountRefunded'],
        'currency': value['currency'],
        'order_id': value['orderId'],
        'refunded_at': value['refundedAt'],
        'state': value['state'],
    };
}

