/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * An honest contract, unlike ``OrderTotal`` above.
 * @export
 * @interface PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponse
 */
export interface PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponse {
    /**
     * 
     */
    businessDays: number;
    /**
     * 
     */
    carrier: string;
    /**
     * 
     */
    orderId: string;
}

/**
 * Check if a given object implements the PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponse interface.
 */
export function instanceOfPremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponse(value: object): value is PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponse {
    if ((!('businessDays' in (value as Record<string, any>)) && !('business_days' in (value as Record<string, any>))) || ((value as Record<string, any>)['businessDays'] === undefined && (value as Record<string, any>)['business_days'] === undefined)) return false;
    if (!('carrier' in value) || value['carrier'] === undefined) return false;
    if ((!('orderId' in (value as Record<string, any>)) && !('order_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orderId'] === undefined && (value as Record<string, any>)['order_id'] === undefined)) return false;
    return true;
}

export function PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponseFromJSON(json: any): PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponse {
    return PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponseFromJSONTyped(json, false);
}

export function PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'businessDays': json['business_days'],
        'carrier': json['carrier'],
        'orderId': json['order_id'],
    };
}

export function PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponseToJSON(json: any): PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponse {
    return PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponseToJSONTyped(json, false);
}

export function PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponseToJSONTyped(value?: PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'business_days': value['businessDays'],
        'carrier': value['carrier'],
        'order_id': value['orderId'],
    };
}

