/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * What the endpoint promises, and what the handler now serves.
 * @export
 * @interface PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponse
 */
export interface PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponse {
    /**
     * ISO 4217 code that `total` is denominated in.
     */
    currency: string;
    /**
     * Identifier of the order being totalled.
     */
    orderId: string;
    /**
     * Whether the order has been settled in full, not in part.
     */
    paid: boolean;
    /**
     * Order total, in whole currency units rather than minor units.
     */
    total: number;
}

/**
 * Check if a given object implements the PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponse interface.
 */
export function instanceOfPremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponse(value: object): value is PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponse {
    if (!('currency' in value) || value['currency'] === undefined) return false;
    if ((!('orderId' in (value as Record<string, any>)) && !('order_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orderId'] === undefined && (value as Record<string, any>)['order_id'] === undefined)) return false;
    if (!('paid' in value) || value['paid'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponseFromJSON(json: any): PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponse {
    return PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponseFromJSONTyped(json, false);
}

export function PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'currency': json['currency'],
        'orderId': json['order_id'],
        'paid': json['paid'],
        'total': json['total'],
    };
}

export function PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponseToJSON(json: any): PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponse {
    return PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponseToJSONTyped(json, false);
}

export function PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponseToJSONTyped(value?: PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'currency': value['currency'],
        'order_id': value['orderId'],
        'paid': value['paid'],
        'total': value['total'],
    };
}

