/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A discounted total. The bound on ``percent_off`` is published, not kept.
 * @export
 * @interface PremanProbeDiscountApiV1PremanProbeDiscountGetResponse
 */
export interface PremanProbeDiscountApiV1PremanProbeDiscountGetResponse {
    /**
     * 
     */
    orderId: string;
    /**
     * 
     */
    percentOff: number;
    /**
     * 
     */
    total: number;
}

/**
 * Check if a given object implements the PremanProbeDiscountApiV1PremanProbeDiscountGetResponse interface.
 */
export function instanceOfPremanProbeDiscountApiV1PremanProbeDiscountGetResponse(value: object): value is PremanProbeDiscountApiV1PremanProbeDiscountGetResponse {
    if ((!('orderId' in (value as Record<string, any>)) && !('order_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['orderId'] === undefined && (value as Record<string, any>)['order_id'] === undefined)) return false;
    if ((!('percentOff' in (value as Record<string, any>)) && !('percent_off' in (value as Record<string, any>))) || ((value as Record<string, any>)['percentOff'] === undefined && (value as Record<string, any>)['percent_off'] === undefined)) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function PremanProbeDiscountApiV1PremanProbeDiscountGetResponseFromJSON(json: any): PremanProbeDiscountApiV1PremanProbeDiscountGetResponse {
    return PremanProbeDiscountApiV1PremanProbeDiscountGetResponseFromJSONTyped(json, false);
}

export function PremanProbeDiscountApiV1PremanProbeDiscountGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PremanProbeDiscountApiV1PremanProbeDiscountGetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'orderId': json['order_id'],
        'percentOff': json['percent_off'],
        'total': json['total'],
    };
}

export function PremanProbeDiscountApiV1PremanProbeDiscountGetResponseToJSON(json: any): PremanProbeDiscountApiV1PremanProbeDiscountGetResponse {
    return PremanProbeDiscountApiV1PremanProbeDiscountGetResponseToJSONTyped(json, false);
}

export function PremanProbeDiscountApiV1PremanProbeDiscountGetResponseToJSONTyped(value?: PremanProbeDiscountApiV1PremanProbeDiscountGetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'order_id': value['orderId'],
        'percent_off': value['percentOff'],
        'total': value['total'],
    };
}

