/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequest
 */
export interface ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequest {
    /**
     * 
     */
    description?: string | null;
    /**
     * 
     */
    name?: string | null;
    /**
     * 
     */
    status?: ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequestStatusEnum | null;
}


/**
 * @export
 */
export const ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequestStatusEnum = {
    Active: 'active',
    Archived: 'archived',
} as const;
export type ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequestStatusEnum = typeof ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequestStatusEnum[keyof typeof ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequestStatusEnum];


/**
 * Check if a given object implements the ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequest interface.
 */
export function instanceOfProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequest(value: object): value is ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequest {
    return true;
}

export function ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequestFromJSON(json: any): ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequest {
    return ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequestFromJSONTyped(json, false);
}

export function ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] === undefined ? undefined : json['description'] === null ? null : json['description'],
        'name': json['name'] === undefined ? undefined : json['name'] === null ? null : json['name'],
        'status': json['status'] === undefined ? undefined : json['status'] === null ? null : json['status'],
    };
}

export function ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequestToJSON(json: any): ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequest {
    return ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequestToJSONTyped(json, false);
}

export function ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequestToJSONTyped(value?: ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'name': value['name'],
        'status': value['status'],
    };
}

