/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectsCreateProjectApiV1ProjectsPostResponse
 */
export interface ProjectsCreateProjectApiV1ProjectsPostResponse {
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    description: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    ownerId: string;
    /**
     * 
     */
    status: ProjectsCreateProjectApiV1ProjectsPostResponseStatusEnum;
    /**
     * 
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const ProjectsCreateProjectApiV1ProjectsPostResponseStatusEnum = {
    Active: 'active',
    Archived: 'archived',
} as const;
export type ProjectsCreateProjectApiV1ProjectsPostResponseStatusEnum = typeof ProjectsCreateProjectApiV1ProjectsPostResponseStatusEnum[keyof typeof ProjectsCreateProjectApiV1ProjectsPostResponseStatusEnum];


/**
 * Check if a given object implements the ProjectsCreateProjectApiV1ProjectsPostResponse interface.
 */
export function instanceOfProjectsCreateProjectApiV1ProjectsPostResponse(value: object): value is ProjectsCreateProjectApiV1ProjectsPostResponse {
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('ownerId' in (value as Record<string, any>)) && !('owner_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['ownerId'] === undefined && (value as Record<string, any>)['owner_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function ProjectsCreateProjectApiV1ProjectsPostResponseFromJSON(json: any): ProjectsCreateProjectApiV1ProjectsPostResponse {
    return ProjectsCreateProjectApiV1ProjectsPostResponseFromJSONTyped(json, false);
}

export function ProjectsCreateProjectApiV1ProjectsPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectsCreateProjectApiV1ProjectsPostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'description': json['description'],
        'id': json['id'],
        'name': json['name'],
        'ownerId': json['owner_id'],
        'status': json['status'],
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
    };
}

export function ProjectsCreateProjectApiV1ProjectsPostResponseToJSON(json: any): ProjectsCreateProjectApiV1ProjectsPostResponse {
    return ProjectsCreateProjectApiV1ProjectsPostResponseToJSONTyped(json, false);
}

export function ProjectsCreateProjectApiV1ProjectsPostResponseToJSONTyped(value?: ProjectsCreateProjectApiV1ProjectsPostResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
        'owner_id': value['ownerId'],
        'status': value['status'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}

