/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequest
 */
export interface ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequest {
    /**
     * 
     */
    description: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    status: ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequestStatusEnum;
}


/**
 * @export
 */
export const ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequestStatusEnum = {
    Active: 'active',
    Archived: 'archived',
} as const;
export type ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequestStatusEnum = typeof ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequestStatusEnum[keyof typeof ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequestStatusEnum];


/**
 * Check if a given object implements the ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequest interface.
 */
export function instanceOfProjectsReplaceProjectApiV1ProjectsProjectIdPutRequest(value: object): value is ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequest {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequestFromJSON(json: any): ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequest {
    return ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequestFromJSONTyped(json, false);
}

export function ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'name': json['name'],
        'status': json['status'],
    };
}

export function ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequestToJSON(json: any): ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequest {
    return ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequestToJSONTyped(json, false);
}

export function ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequestToJSONTyped(value?: ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'name': value['name'],
        'status': value['status'],
    };
}

