/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectsCreateProjectApiV1ProjectsPostRequest
 */
export interface ProjectsCreateProjectApiV1ProjectsPostRequest {
    /**
     * 
     */
    description?: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    status?: ProjectsCreateProjectApiV1ProjectsPostRequestStatusEnum;
}


/**
 * @export
 */
export const ProjectsCreateProjectApiV1ProjectsPostRequestStatusEnum = {
    Active: 'active',
    Archived: 'archived',
} as const;
export type ProjectsCreateProjectApiV1ProjectsPostRequestStatusEnum = typeof ProjectsCreateProjectApiV1ProjectsPostRequestStatusEnum[keyof typeof ProjectsCreateProjectApiV1ProjectsPostRequestStatusEnum];


/**
 * Check if a given object implements the ProjectsCreateProjectApiV1ProjectsPostRequest interface.
 */
export function instanceOfProjectsCreateProjectApiV1ProjectsPostRequest(value: object): value is ProjectsCreateProjectApiV1ProjectsPostRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function ProjectsCreateProjectApiV1ProjectsPostRequestFromJSON(json: any): ProjectsCreateProjectApiV1ProjectsPostRequest {
    return ProjectsCreateProjectApiV1ProjectsPostRequestFromJSONTyped(json, false);
}

export function ProjectsCreateProjectApiV1ProjectsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectsCreateProjectApiV1ProjectsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function ProjectsCreateProjectApiV1ProjectsPostRequestToJSON(json: any): ProjectsCreateProjectApiV1ProjectsPostRequest {
    return ProjectsCreateProjectApiV1ProjectsPostRequestToJSONTyped(json, false);
}

export function ProjectsCreateProjectApiV1ProjectsPostRequestToJSONTyped(value?: ProjectsCreateProjectApiV1ProjectsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'name': value['name'],
        'status': value['status'],
    };
}

