/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ProjectsCreateProjectApiV1ProjectsPostResponse } from './ProjectsCreateProjectApiV1ProjectsPostResponse';
import {
    ProjectsCreateProjectApiV1ProjectsPostResponseFromJSON,
    ProjectsCreateProjectApiV1ProjectsPostResponseFromJSONTyped,
    ProjectsCreateProjectApiV1ProjectsPostResponseToJSON,
    ProjectsCreateProjectApiV1ProjectsPostResponseToJSONTyped,
} from './ProjectsCreateProjectApiV1ProjectsPostResponse';

/**
 * 
 * @export
 * @interface ProjectsListProjectsApiV1ProjectsGetResponse
 */
export interface ProjectsListProjectsApiV1ProjectsGetResponse {
    /**
     * 
     */
    items: Array<ProjectsCreateProjectApiV1ProjectsPostResponse>;
    /**
     * 
     */
    limit: number;
    /**
     * 
     */
    offset: number;
    /**
     * 
     */
    total: number;
}

/**
 * Check if a given object implements the ProjectsListProjectsApiV1ProjectsGetResponse interface.
 */
export function instanceOfProjectsListProjectsApiV1ProjectsGetResponse(value: object): value is ProjectsListProjectsApiV1ProjectsGetResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function ProjectsListProjectsApiV1ProjectsGetResponseFromJSON(json: any): ProjectsListProjectsApiV1ProjectsGetResponse {
    return ProjectsListProjectsApiV1ProjectsGetResponseFromJSONTyped(json, false);
}

export function ProjectsListProjectsApiV1ProjectsGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectsListProjectsApiV1ProjectsGetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(ProjectsCreateProjectApiV1ProjectsPostResponseFromJSON)),
        'limit': json['limit'],
        'offset': json['offset'],
        'total': json['total'],
    };
}

export function ProjectsListProjectsApiV1ProjectsGetResponseToJSON(json: any): ProjectsListProjectsApiV1ProjectsGetResponse {
    return ProjectsListProjectsApiV1ProjectsGetResponseToJSONTyped(json, false);
}

export function ProjectsListProjectsApiV1ProjectsGetResponseToJSONTyped(value?: ProjectsListProjectsApiV1ProjectsGetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(ProjectsCreateProjectApiV1ProjectsPostResponseToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

