/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReadyReadinessResponse
 */
export interface ReadyReadinessResponse {
    /**
     * 
     */
    mockStorage: any | null;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    storage: any | null;
}

/**
 * Check if a given object implements the ReadyReadinessResponse interface.
 */
export function instanceOfReadyReadinessResponse(value: object): value is ReadyReadinessResponse {
    if ((!('mockStorage' in (value as Record<string, any>)) && !('mock_storage' in (value as Record<string, any>))) || ((value as Record<string, any>)['mockStorage'] === undefined && (value as Record<string, any>)['mock_storage'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('storage' in value) || value['storage'] === undefined) return false;
    return true;
}

export function ReadyReadinessResponseFromJSON(json: any): ReadyReadinessResponse {
    return ReadyReadinessResponseFromJSONTyped(json, false);
}

export function ReadyReadinessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReadyReadinessResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'mockStorage': json['mock_storage'],
        'status': json['status'],
        'storage': json['storage'],
    };
}

export function ReadyReadinessResponseToJSON(json: any): ReadyReadinessResponse {
    return ReadyReadinessResponseToJSONTyped(json, false);
}

export function ReadyReadinessResponseToJSONTyped(value?: ReadyReadinessResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mock_storage': value['mockStorage'],
        'status': value['status'],
        'storage': value['storage'],
    };
}

