/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResourceConfig
 */
export interface ResourceConfig {
    /**
     * 
     */
    createModel: string;
    /**
     * 
     */
    plural: string;
    /**
     * 
     */
    regionScoped?: boolean;
    /**
     * 
     */
    replaceModel: string;
    /**
     * 
     */
    responseModel: string;
    /**
     * 
     */
    singular: string;
    /**
     * 
     */
    updateModel: string;
}

/**
 * Check if a given object implements the ResourceConfig interface.
 */
export function instanceOfResourceConfig(value: object): value is ResourceConfig {
    if ((!('createModel' in (value as Record<string, any>)) && !('create_model' in (value as Record<string, any>))) || ((value as Record<string, any>)['createModel'] === undefined && (value as Record<string, any>)['create_model'] === undefined)) return false;
    if (!('plural' in value) || value['plural'] === undefined) return false;
    if ((!('replaceModel' in (value as Record<string, any>)) && !('replace_model' in (value as Record<string, any>))) || ((value as Record<string, any>)['replaceModel'] === undefined && (value as Record<string, any>)['replace_model'] === undefined)) return false;
    if ((!('responseModel' in (value as Record<string, any>)) && !('response_model' in (value as Record<string, any>))) || ((value as Record<string, any>)['responseModel'] === undefined && (value as Record<string, any>)['response_model'] === undefined)) return false;
    if (!('singular' in value) || value['singular'] === undefined) return false;
    if ((!('updateModel' in (value as Record<string, any>)) && !('update_model' in (value as Record<string, any>))) || ((value as Record<string, any>)['updateModel'] === undefined && (value as Record<string, any>)['update_model'] === undefined)) return false;
    return true;
}

export function ResourceConfigFromJSON(json: any): ResourceConfig {
    return ResourceConfigFromJSONTyped(json, false);
}

export function ResourceConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResourceConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'createModel': json['create_model'],
        'plural': json['plural'],
        'regionScoped': json['region_scoped'] == null ? undefined : json['region_scoped'],
        'replaceModel': json['replace_model'],
        'responseModel': json['response_model'],
        'singular': json['singular'],
        'updateModel': json['update_model'],
    };
}

export function ResourceConfigToJSON(json: any): ResourceConfig {
    return ResourceConfigToJSONTyped(json, false);
}

export function ResourceConfigToJSONTyped(value?: ResourceConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'create_model': value['createModel'],
        'plural': value['plural'],
        'region_scoped': value['regionScoped'],
        'replace_model': value['replaceModel'],
        'response_model': value['responseModel'],
        'singular': value['singular'],
        'update_model': value['updateModel'],
    };
}

