/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface SystemHealthHealthGetResponse
 */
export interface SystemHealthHealthGetResponse {
    /**
     * Which deployment answered: development, demo or production.
     */
    environment: string;
    /**
     * The service's own name, for multi-service dashboards.
     */
    service: string;
    /**
     * `ok` when the service is serving traffic, `degraded` otherwise.
     */
    status: SystemHealthHealthGetResponseStatusEnum;
    /**
     * The storage backend currently in use.
     */
    storage: string;
    /**
     * When this answer was produced, in UTC.
     */
    timestamp: Date;
    /**
     * The running application version.
     */
    version: string;
}


/**
 * @export
 */
export const SystemHealthHealthGetResponseStatusEnum = {
    Ok: 'ok',
    Degraded: 'degraded',
} as const;
export type SystemHealthHealthGetResponseStatusEnum = typeof SystemHealthHealthGetResponseStatusEnum[keyof typeof SystemHealthHealthGetResponseStatusEnum];


/**
 * Check if a given object implements the SystemHealthHealthGetResponse interface.
 */
export function instanceOfSystemHealthHealthGetResponse(value: object): value is SystemHealthHealthGetResponse {
    if (!('environment' in value) || value['environment'] === undefined) return false;
    if (!('service' in value) || value['service'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('storage' in value) || value['storage'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function SystemHealthHealthGetResponseFromJSON(json: any): SystemHealthHealthGetResponse {
    return SystemHealthHealthGetResponseFromJSONTyped(json, false);
}

export function SystemHealthHealthGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SystemHealthHealthGetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'environment': json['environment'],
        'service': json['service'],
        'status': json['status'],
        'storage': json['storage'],
        'timestamp': (json['timestamp'] == null ? json['timestamp'] : parseDateTime(json['timestamp'])),
        'version': json['version'],
    };
}

export function SystemHealthHealthGetResponseToJSON(json: any): SystemHealthHealthGetResponse {
    return SystemHealthHealthGetResponseToJSONTyped(json, false);
}

export function SystemHealthHealthGetResponseToJSONTyped(value?: SystemHealthHealthGetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'environment': value['environment'],
        'service': value['service'],
        'status': value['status'],
        'storage': value['storage'],
        'timestamp': value['timestamp'] == null ? value['timestamp'] : serializeDateTime(value['timestamp']),
        'version': value['version'],
    };
}

