/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface TasksReplaceTaskApiV1TasksTaskIdPutRequest
 */
export interface TasksReplaceTaskApiV1TasksTaskIdPutRequest {
    /**
     * 
     */
    description: string;
    /**
     * 
     */
    dueAt: Date | null;
    /**
     * 
     */
    priority: TasksReplaceTaskApiV1TasksTaskIdPutRequestPriorityEnum;
    /**
     * 
     */
    status: TasksReplaceTaskApiV1TasksTaskIdPutRequestStatusEnum;
    /**
     * 
     */
    title: string;
}


/**
 * @export
 */
export const TasksReplaceTaskApiV1TasksTaskIdPutRequestPriorityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Critical: 'critical',
} as const;
export type TasksReplaceTaskApiV1TasksTaskIdPutRequestPriorityEnum = typeof TasksReplaceTaskApiV1TasksTaskIdPutRequestPriorityEnum[keyof typeof TasksReplaceTaskApiV1TasksTaskIdPutRequestPriorityEnum];

/**
 * @export
 */
export const TasksReplaceTaskApiV1TasksTaskIdPutRequestStatusEnum = {
    Todo: 'todo',
    InProgress: 'in_progress',
    Done: 'done',
} as const;
export type TasksReplaceTaskApiV1TasksTaskIdPutRequestStatusEnum = typeof TasksReplaceTaskApiV1TasksTaskIdPutRequestStatusEnum[keyof typeof TasksReplaceTaskApiV1TasksTaskIdPutRequestStatusEnum];


/**
 * Check if a given object implements the TasksReplaceTaskApiV1TasksTaskIdPutRequest interface.
 */
export function instanceOfTasksReplaceTaskApiV1TasksTaskIdPutRequest(value: object): value is TasksReplaceTaskApiV1TasksTaskIdPutRequest {
    if (!('description' in value) || value['description'] === undefined) return false;
    if ((!('dueAt' in (value as Record<string, any>)) && !('due_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['dueAt'] === undefined && (value as Record<string, any>)['due_at'] === undefined)) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function TasksReplaceTaskApiV1TasksTaskIdPutRequestFromJSON(json: any): TasksReplaceTaskApiV1TasksTaskIdPutRequest {
    return TasksReplaceTaskApiV1TasksTaskIdPutRequestFromJSONTyped(json, false);
}

export function TasksReplaceTaskApiV1TasksTaskIdPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksReplaceTaskApiV1TasksTaskIdPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'dueAt': (json['due_at'] == null ? null : parseDateTime(json['due_at'])),
        'priority': json['priority'],
        'status': json['status'],
        'title': json['title'],
    };
}

export function TasksReplaceTaskApiV1TasksTaskIdPutRequestToJSON(json: any): TasksReplaceTaskApiV1TasksTaskIdPutRequest {
    return TasksReplaceTaskApiV1TasksTaskIdPutRequestToJSONTyped(json, false);
}

export function TasksReplaceTaskApiV1TasksTaskIdPutRequestToJSONTyped(value?: TasksReplaceTaskApiV1TasksTaskIdPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'due_at': value['dueAt'] == null ? value['dueAt'] : serializeDateTime(value['dueAt']),
        'priority': value['priority'],
        'status': value['status'],
        'title': value['title'],
    };
}

