/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse
 */
export interface TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse {
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    description: string;
    /**
     * 
     */
    dueAt: Date | null;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    ownerId: string;
    /**
     * 
     */
    priority: TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponsePriorityEnum;
    /**
     * 
     */
    projectId: string;
    /**
     * 
     */
    status: TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseStatusEnum;
    /**
     * 
     */
    title: string;
    /**
     * 
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponsePriorityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Critical: 'critical',
} as const;
export type TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponsePriorityEnum = typeof TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponsePriorityEnum[keyof typeof TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponsePriorityEnum];

/**
 * @export
 */
export const TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseStatusEnum = {
    Todo: 'todo',
    InProgress: 'in_progress',
    Done: 'done',
} as const;
export type TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseStatusEnum = typeof TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseStatusEnum[keyof typeof TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseStatusEnum];


/**
 * Check if a given object implements the TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse interface.
 */
export function instanceOfTasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse(value: object): value is TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse {
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if ((!('dueAt' in (value as Record<string, any>)) && !('due_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['dueAt'] === undefined && (value as Record<string, any>)['due_at'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('ownerId' in (value as Record<string, any>)) && !('owner_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['ownerId'] === undefined && (value as Record<string, any>)['owner_id'] === undefined)) return false;
    if (!('priority' in value) || value['priority'] === undefined) return false;
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseFromJSON(json: any): TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse {
    return TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseFromJSONTyped(json, false);
}

export function TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'description': json['description'],
        'dueAt': (json['due_at'] == null ? null : parseDateTime(json['due_at'])),
        'id': json['id'],
        'ownerId': json['owner_id'],
        'priority': json['priority'],
        'projectId': json['project_id'],
        'status': json['status'],
        'title': json['title'],
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
    };
}

export function TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseToJSON(json: any): TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse {
    return TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseToJSONTyped(json, false);
}

export function TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseToJSONTyped(value?: TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'description': value['description'],
        'due_at': value['dueAt'] == null ? value['dueAt'] : serializeDateTime(value['dueAt']),
        'id': value['id'],
        'owner_id': value['ownerId'],
        'priority': value['priority'],
        'project_id': value['projectId'],
        'status': value['status'],
        'title': value['title'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}

