/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface TasksUpdateTaskApiV1TasksTaskIdPatchRequest
 */
export interface TasksUpdateTaskApiV1TasksTaskIdPatchRequest {
    /**
     * 
     */
    description?: string | null;
    /**
     * 
     */
    dueAt?: Date | null;
    /**
     * 
     */
    priority?: TasksUpdateTaskApiV1TasksTaskIdPatchRequestPriorityEnum | null;
    /**
     * 
     */
    status?: TasksUpdateTaskApiV1TasksTaskIdPatchRequestStatusEnum | null;
    /**
     * 
     */
    title?: string | null;
}


/**
 * @export
 */
export const TasksUpdateTaskApiV1TasksTaskIdPatchRequestPriorityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Critical: 'critical',
} as const;
export type TasksUpdateTaskApiV1TasksTaskIdPatchRequestPriorityEnum = typeof TasksUpdateTaskApiV1TasksTaskIdPatchRequestPriorityEnum[keyof typeof TasksUpdateTaskApiV1TasksTaskIdPatchRequestPriorityEnum];

/**
 * @export
 */
export const TasksUpdateTaskApiV1TasksTaskIdPatchRequestStatusEnum = {
    Todo: 'todo',
    InProgress: 'in_progress',
    Done: 'done',
} as const;
export type TasksUpdateTaskApiV1TasksTaskIdPatchRequestStatusEnum = typeof TasksUpdateTaskApiV1TasksTaskIdPatchRequestStatusEnum[keyof typeof TasksUpdateTaskApiV1TasksTaskIdPatchRequestStatusEnum];


/**
 * Check if a given object implements the TasksUpdateTaskApiV1TasksTaskIdPatchRequest interface.
 */
export function instanceOfTasksUpdateTaskApiV1TasksTaskIdPatchRequest(value: object): value is TasksUpdateTaskApiV1TasksTaskIdPatchRequest {
    return true;
}

export function TasksUpdateTaskApiV1TasksTaskIdPatchRequestFromJSON(json: any): TasksUpdateTaskApiV1TasksTaskIdPatchRequest {
    return TasksUpdateTaskApiV1TasksTaskIdPatchRequestFromJSONTyped(json, false);
}

export function TasksUpdateTaskApiV1TasksTaskIdPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksUpdateTaskApiV1TasksTaskIdPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] === undefined ? undefined : json['description'] === null ? null : json['description'],
        'dueAt': json['due_at'] === undefined ? undefined : json['due_at'] === null ? null : (parseDateTime(json['due_at'])),
        'priority': json['priority'] === undefined ? undefined : json['priority'] === null ? null : json['priority'],
        'status': json['status'] === undefined ? undefined : json['status'] === null ? null : json['status'],
        'title': json['title'] === undefined ? undefined : json['title'] === null ? null : json['title'],
    };
}

export function TasksUpdateTaskApiV1TasksTaskIdPatchRequestToJSON(json: any): TasksUpdateTaskApiV1TasksTaskIdPatchRequest {
    return TasksUpdateTaskApiV1TasksTaskIdPatchRequestToJSONTyped(json, false);
}

export function TasksUpdateTaskApiV1TasksTaskIdPatchRequestToJSONTyped(value?: TasksUpdateTaskApiV1TasksTaskIdPatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'due_at': value['dueAt'] == null ? value['dueAt'] : serializeDateTime(value['dueAt']),
        'priority': value['priority'],
        'status': value['status'],
        'title': value['title'],
    };
}

