/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequest
 */
export interface TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequest {
    /**
     * 
     */
    description?: string;
    /**
     * 
     */
    dueAt?: Date | null;
    /**
     * 
     */
    priority?: TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestPriorityEnum;
    /**
     * 
     */
    status?: TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestStatusEnum;
    /**
     * 
     */
    title: string;
}


/**
 * @export
 */
export const TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestPriorityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Critical: 'critical',
} as const;
export type TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestPriorityEnum = typeof TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestPriorityEnum[keyof typeof TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestPriorityEnum];

/**
 * @export
 */
export const TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestStatusEnum = {
    Todo: 'todo',
    InProgress: 'in_progress',
    Done: 'done',
} as const;
export type TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestStatusEnum = typeof TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestStatusEnum[keyof typeof TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestStatusEnum];


/**
 * Check if a given object implements the TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequest interface.
 */
export function instanceOfTasksCreateTaskApiV1ProjectsProjectIdTasksPostRequest(value: object): value is TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequest {
    if (!('title' in value) || value['title'] === undefined) return false;
    return true;
}

export function TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestFromJSON(json: any): TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequest {
    return TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestFromJSONTyped(json, false);
}

export function TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'dueAt': json['due_at'] === undefined ? undefined : json['due_at'] === null ? null : (parseDateTime(json['due_at'])),
        'priority': json['priority'] == null ? undefined : json['priority'],
        'status': json['status'] == null ? undefined : json['status'],
        'title': json['title'],
    };
}

export function TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestToJSON(json: any): TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequest {
    return TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestToJSONTyped(json, false);
}

export function TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestToJSONTyped(value?: TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'due_at': value['dueAt'] == null ? value['dueAt'] : serializeDateTime(value['dueAt']),
        'priority': value['priority'],
        'status': value['status'],
        'title': value['title'],
    };
}

