/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
/**
 * 
 * @export
 * @interface TasksDeleteTaskApiV1TasksTaskIdDeleteRequest
 */
export interface TasksDeleteTaskApiV1TasksTaskIdDeleteRequest {
    /**
     * 
     */
    createdAt: Date;
    /**
     * 
     */
    description?: string;
    /**
     * 
     */
    dueAt?: Date;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    ownerId: string;
    /**
     * 
     */
    priority?: TasksDeleteTaskApiV1TasksTaskIdDeleteRequestPriorityEnum;
    /**
     * 
     */
    projectId: string;
    /**
     * 
     */
    status?: TasksDeleteTaskApiV1TasksTaskIdDeleteRequestStatusEnum;
    /**
     * 
     */
    title: string;
    /**
     * 
     */
    updatedAt: Date;
}


/**
 * @export
 */
export const TasksDeleteTaskApiV1TasksTaskIdDeleteRequestPriorityEnum = {
    Low: 'low',
    Medium: 'medium',
    High: 'high',
    Critical: 'critical',
} as const;
export type TasksDeleteTaskApiV1TasksTaskIdDeleteRequestPriorityEnum = typeof TasksDeleteTaskApiV1TasksTaskIdDeleteRequestPriorityEnum[keyof typeof TasksDeleteTaskApiV1TasksTaskIdDeleteRequestPriorityEnum];

/**
 * @export
 */
export const TasksDeleteTaskApiV1TasksTaskIdDeleteRequestStatusEnum = {
    Todo: 'todo',
    InProgress: 'in_progress',
    Done: 'done',
} as const;
export type TasksDeleteTaskApiV1TasksTaskIdDeleteRequestStatusEnum = typeof TasksDeleteTaskApiV1TasksTaskIdDeleteRequestStatusEnum[keyof typeof TasksDeleteTaskApiV1TasksTaskIdDeleteRequestStatusEnum];


/**
 * Check if a given object implements the TasksDeleteTaskApiV1TasksTaskIdDeleteRequest interface.
 */
export function instanceOfTasksDeleteTaskApiV1TasksTaskIdDeleteRequest(value: object): value is TasksDeleteTaskApiV1TasksTaskIdDeleteRequest {
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('ownerId' in (value as Record<string, any>)) && !('owner_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['ownerId'] === undefined && (value as Record<string, any>)['owner_id'] === undefined)) return false;
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function TasksDeleteTaskApiV1TasksTaskIdDeleteRequestFromJSON(json: any): TasksDeleteTaskApiV1TasksTaskIdDeleteRequest {
    return TasksDeleteTaskApiV1TasksTaskIdDeleteRequestFromJSONTyped(json, false);
}

export function TasksDeleteTaskApiV1TasksTaskIdDeleteRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksDeleteTaskApiV1TasksTaskIdDeleteRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': (json['created_at'] == null ? json['created_at'] : parseDateTime(json['created_at'])),
        'description': json['description'] == null ? undefined : json['description'],
        'dueAt': json['due_at'] == null ? undefined : (parseDateTime(json['due_at'])),
        'id': json['id'],
        'ownerId': json['owner_id'],
        'priority': json['priority'] == null ? undefined : json['priority'],
        'projectId': json['project_id'],
        'status': json['status'] == null ? undefined : json['status'],
        'title': json['title'],
        'updatedAt': (json['updated_at'] == null ? json['updated_at'] : parseDateTime(json['updated_at'])),
    };
}

export function TasksDeleteTaskApiV1TasksTaskIdDeleteRequestToJSON(json: any): TasksDeleteTaskApiV1TasksTaskIdDeleteRequest {
    return TasksDeleteTaskApiV1TasksTaskIdDeleteRequestToJSONTyped(json, false);
}

export function TasksDeleteTaskApiV1TasksTaskIdDeleteRequestToJSONTyped(value?: TasksDeleteTaskApiV1TasksTaskIdDeleteRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'] == null ? value['createdAt'] : serializeDateTime(value['createdAt']),
        'description': value['description'],
        'due_at': value['dueAt'] == null ? value['dueAt'] : serializeDateTime(value['dueAt']),
        'id': value['id'],
        'owner_id': value['ownerId'],
        'priority': value['priority'],
        'project_id': value['projectId'],
        'status': value['status'],
        'title': value['title'],
        'updated_at': value['updatedAt'] == null ? value['updatedAt'] : serializeDateTime(value['updatedAt']),
    };
}

