/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse } from './TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse';
import {
    TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseFromJSON,
    TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseFromJSONTyped,
    TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseToJSON,
    TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseToJSONTyped,
} from './TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse';

/**
 * 
 * @export
 * @interface TasksListTasksApiV1ProjectsProjectIdTasksGetResponse
 */
export interface TasksListTasksApiV1ProjectsProjectIdTasksGetResponse {
    /**
     * 
     */
    items: Array<TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse>;
    /**
     * 
     */
    limit: number;
    /**
     * 
     */
    offset: number;
    /**
     * 
     */
    total: number;
}

/**
 * Check if a given object implements the TasksListTasksApiV1ProjectsProjectIdTasksGetResponse interface.
 */
export function instanceOfTasksListTasksApiV1ProjectsProjectIdTasksGetResponse(value: object): value is TasksListTasksApiV1ProjectsProjectIdTasksGetResponse {
    if (!('items' in value) || value['items'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function TasksListTasksApiV1ProjectsProjectIdTasksGetResponseFromJSON(json: any): TasksListTasksApiV1ProjectsProjectIdTasksGetResponse {
    return TasksListTasksApiV1ProjectsProjectIdTasksGetResponseFromJSONTyped(json, false);
}

export function TasksListTasksApiV1ProjectsProjectIdTasksGetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TasksListTasksApiV1ProjectsProjectIdTasksGetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'items': ((json['items'] as Array<any>).map(TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseFromJSON)),
        'limit': json['limit'],
        'offset': json['offset'],
        'total': json['total'],
    };
}

export function TasksListTasksApiV1ProjectsProjectIdTasksGetResponseToJSON(json: any): TasksListTasksApiV1ProjectsProjectIdTasksGetResponse {
    return TasksListTasksApiV1ProjectsProjectIdTasksGetResponseToJSONTyped(json, false);
}

export function TasksListTasksApiV1ProjectsProjectIdTasksGetResponseToJSONTyped(value?: TasksListTasksApiV1ProjectsProjectIdTasksGetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'items': ((value['items'] as Array<any>).map(TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

