/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AuthenticationChangePasswordApiV1AuthChangePasswordPostRequest,
    AuthenticationChangePasswordApiV1AuthChangePasswordPostRequestFromJSON,
    AuthenticationChangePasswordApiV1AuthChangePasswordPostRequestToJSON,
} from '../models/AuthenticationChangePasswordApiV1AuthChangePasswordPostRequest';
import {
    type AuthenticationChangePasswordApiV1AuthChangePasswordPostResponse,
    AuthenticationChangePasswordApiV1AuthChangePasswordPostResponseFromJSON,
    AuthenticationChangePasswordApiV1AuthChangePasswordPostResponseToJSON,
} from '../models/AuthenticationChangePasswordApiV1AuthChangePasswordPostResponse';
import {
    type AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequest,
    AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequestFromJSON,
    AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequestToJSON,
} from '../models/AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequest';
import {
    type AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponse,
    AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponseFromJSON,
    AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponseToJSON,
} from '../models/AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponse';
import {
    type AuthenticationGetMeApiV1AuthMeGetResponse,
    AuthenticationGetMeApiV1AuthMeGetResponseFromJSON,
    AuthenticationGetMeApiV1AuthMeGetResponseToJSON,
} from '../models/AuthenticationGetMeApiV1AuthMeGetResponse';
import {
    type AuthenticationLoginApiV1AuthLoginPostRequest,
    AuthenticationLoginApiV1AuthLoginPostRequestFromJSON,
    AuthenticationLoginApiV1AuthLoginPostRequestToJSON,
} from '../models/AuthenticationLoginApiV1AuthLoginPostRequest';
import {
    type AuthenticationLoginApiV1AuthLoginPostResponse,
    AuthenticationLoginApiV1AuthLoginPostResponseFromJSON,
    AuthenticationLoginApiV1AuthLoginPostResponseToJSON,
} from '../models/AuthenticationLoginApiV1AuthLoginPostResponse';
import {
    type AuthenticationLogoutApiV1AuthLogoutPostRequest,
    AuthenticationLogoutApiV1AuthLogoutPostRequestFromJSON,
    AuthenticationLogoutApiV1AuthLogoutPostRequestToJSON,
} from '../models/AuthenticationLogoutApiV1AuthLogoutPostRequest';
import {
    type AuthenticationRefreshApiV1AuthRefreshPostRequest,
    AuthenticationRefreshApiV1AuthRefreshPostRequestFromJSON,
    AuthenticationRefreshApiV1AuthRefreshPostRequestToJSON,
} from '../models/AuthenticationRefreshApiV1AuthRefreshPostRequest';
import {
    type AuthenticationRegisterApiV1AuthRegisterPostRequest,
    AuthenticationRegisterApiV1AuthRegisterPostRequestFromJSON,
    AuthenticationRegisterApiV1AuthRegisterPostRequestToJSON,
} from '../models/AuthenticationRegisterApiV1AuthRegisterPostRequest';
import {
    type AuthenticationResetPasswordApiV1AuthResetPasswordPostRequest,
    AuthenticationResetPasswordApiV1AuthResetPasswordPostRequestFromJSON,
    AuthenticationResetPasswordApiV1AuthResetPasswordPostRequestToJSON,
} from '../models/AuthenticationResetPasswordApiV1AuthResetPasswordPostRequest';
import {
    type AuthenticationUpdateMeApiV1AuthMePatchRequest,
    AuthenticationUpdateMeApiV1AuthMePatchRequestFromJSON,
    AuthenticationUpdateMeApiV1AuthMePatchRequestToJSON,
} from '../models/AuthenticationUpdateMeApiV1AuthMePatchRequest';

export interface AuthenticationChangePasswordApiV1AuthChangePasswordPostOperationRequest {
    /**
     * 
     */
    authenticationChangePasswordApiV1AuthChangePasswordPostRequest: AuthenticationChangePasswordApiV1AuthChangePasswordPostRequest;
}

export interface AuthenticationForgotPasswordApiV1AuthForgotPasswordPostOperationRequest {
    /**
     * 
     */
    authenticationForgotPasswordApiV1AuthForgotPasswordPostRequest: AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequest;
}

export interface AuthenticationLoginApiV1AuthLoginPostOperationRequest {
    /**
     * 
     */
    authenticationLoginApiV1AuthLoginPostRequest: AuthenticationLoginApiV1AuthLoginPostRequest;
}

export interface AuthenticationLogoutApiV1AuthLogoutPostOperationRequest {
    /**
     * 
     */
    authenticationLogoutApiV1AuthLogoutPostRequest: AuthenticationLogoutApiV1AuthLogoutPostRequest;
}

export interface AuthenticationRefreshApiV1AuthRefreshPostOperationRequest {
    /**
     * 
     */
    authenticationRefreshApiV1AuthRefreshPostRequest: AuthenticationRefreshApiV1AuthRefreshPostRequest;
}

export interface AuthenticationRegisterApiV1AuthRegisterPostOperationRequest {
    /**
     * 
     */
    authenticationRegisterApiV1AuthRegisterPostRequest: AuthenticationRegisterApiV1AuthRegisterPostRequest;
}

export interface AuthenticationResetPasswordApiV1AuthResetPasswordPostOperationRequest {
    /**
     * 
     */
    authenticationResetPasswordApiV1AuthResetPasswordPostRequest: AuthenticationResetPasswordApiV1AuthResetPasswordPostRequest;
}

export interface AuthenticationUpdateMeApiV1AuthMePatchOperationRequest {
    /**
     * 
     */
    authenticationUpdateMeApiV1AuthMePatchRequest: AuthenticationUpdateMeApiV1AuthMePatchRequest;
}

/**
 * 
 */
export class AuthenticationApi extends runtime.BaseAPI {

    /**
     * Creates request options for authenticationChangePasswordApiV1AuthChangePasswordPost without sending the request
     */
    async authenticationChangePasswordApiV1AuthChangePasswordPostRequestOpts(requestParameters: AuthenticationChangePasswordApiV1AuthChangePasswordPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authenticationChangePasswordApiV1AuthChangePasswordPostRequest'] == null) {
            throw new runtime.RequiredError(
                'authenticationChangePasswordApiV1AuthChangePasswordPostRequest',
                'Required parameter "authenticationChangePasswordApiV1AuthChangePasswordPostRequest" was null or undefined when calling authenticationChangePasswordApiV1AuthChangePasswordPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/change-password`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthenticationChangePasswordApiV1AuthChangePasswordPostRequestToJSON(requestParameters['authenticationChangePasswordApiV1AuthChangePasswordPostRequest']),
        };
    }

    /**
     * Changes the password for the authenticated user.
     * Change the current user\'s password
     */
    async authenticationChangePasswordApiV1AuthChangePasswordPostRaw(requestParameters: AuthenticationChangePasswordApiV1AuthChangePasswordPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthenticationChangePasswordApiV1AuthChangePasswordPostResponse>> {
        const requestOptions = await this.authenticationChangePasswordApiV1AuthChangePasswordPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthenticationChangePasswordApiV1AuthChangePasswordPostResponseFromJSON(jsonValue));
    }

    /**
     * Changes the password for the authenticated user.
     * Change the current user\'s password
     */
    async authenticationChangePasswordApiV1AuthChangePasswordPost(requestParameters: AuthenticationChangePasswordApiV1AuthChangePasswordPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthenticationChangePasswordApiV1AuthChangePasswordPostResponse> {
        const response = await this.authenticationChangePasswordApiV1AuthChangePasswordPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authenticationForgotPasswordApiV1AuthForgotPasswordPost without sending the request
     */
    async authenticationForgotPasswordApiV1AuthForgotPasswordPostRequestOpts(requestParameters: AuthenticationForgotPasswordApiV1AuthForgotPasswordPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authenticationForgotPasswordApiV1AuthForgotPasswordPostRequest'] == null) {
            throw new runtime.RequiredError(
                'authenticationForgotPasswordApiV1AuthForgotPasswordPostRequest',
                'Required parameter "authenticationForgotPasswordApiV1AuthForgotPasswordPostRequest" was null or undefined when calling authenticationForgotPasswordApiV1AuthForgotPasswordPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/forgot-password`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthenticationForgotPasswordApiV1AuthForgotPasswordPostRequestToJSON(requestParameters['authenticationForgotPasswordApiV1AuthForgotPasswordPostRequest']),
        };
    }

    /**
     * Starts the forgot-password process for a user.
     * Request a password reset
     */
    async authenticationForgotPasswordApiV1AuthForgotPasswordPostRaw(requestParameters: AuthenticationForgotPasswordApiV1AuthForgotPasswordPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponse>> {
        const requestOptions = await this.authenticationForgotPasswordApiV1AuthForgotPasswordPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponseFromJSON(jsonValue));
    }

    /**
     * Starts the forgot-password process for a user.
     * Request a password reset
     */
    async authenticationForgotPasswordApiV1AuthForgotPasswordPost(requestParameters: AuthenticationForgotPasswordApiV1AuthForgotPasswordPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthenticationForgotPasswordApiV1AuthForgotPasswordPostResponse> {
        const response = await this.authenticationForgotPasswordApiV1AuthForgotPasswordPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authenticationGetMeApiV1AuthMeGet without sending the request
     */
    async authenticationGetMeApiV1AuthMeGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/auth/me`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves information about the authenticated user.
     * Get the current user
     */
    async authenticationGetMeApiV1AuthMeGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthenticationGetMeApiV1AuthMeGetResponse>> {
        const requestOptions = await this.authenticationGetMeApiV1AuthMeGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthenticationGetMeApiV1AuthMeGetResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves information about the authenticated user.
     * Get the current user
     */
    async authenticationGetMeApiV1AuthMeGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthenticationGetMeApiV1AuthMeGetResponse> {
        const response = await this.authenticationGetMeApiV1AuthMeGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authenticationLoginApiV1AuthLoginPost without sending the request
     */
    async authenticationLoginApiV1AuthLoginPostRequestOpts(requestParameters: AuthenticationLoginApiV1AuthLoginPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authenticationLoginApiV1AuthLoginPostRequest'] == null) {
            throw new runtime.RequiredError(
                'authenticationLoginApiV1AuthLoginPostRequest',
                'Required parameter "authenticationLoginApiV1AuthLoginPostRequest" was null or undefined when calling authenticationLoginApiV1AuthLoginPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/login`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthenticationLoginApiV1AuthLoginPostRequestToJSON(requestParameters['authenticationLoginApiV1AuthLoginPostRequest']),
        };
    }

    /**
     * Authenticates a user.
     * Log in a user
     */
    async authenticationLoginApiV1AuthLoginPostRaw(requestParameters: AuthenticationLoginApiV1AuthLoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthenticationLoginApiV1AuthLoginPostResponse>> {
        const requestOptions = await this.authenticationLoginApiV1AuthLoginPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthenticationLoginApiV1AuthLoginPostResponseFromJSON(jsonValue));
    }

    /**
     * Authenticates a user.
     * Log in a user
     */
    async authenticationLoginApiV1AuthLoginPost(requestParameters: AuthenticationLoginApiV1AuthLoginPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthenticationLoginApiV1AuthLoginPostResponse> {
        const response = await this.authenticationLoginApiV1AuthLoginPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authenticationLogoutApiV1AuthLogoutPost without sending the request
     */
    async authenticationLogoutApiV1AuthLogoutPostRequestOpts(requestParameters: AuthenticationLogoutApiV1AuthLogoutPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authenticationLogoutApiV1AuthLogoutPostRequest'] == null) {
            throw new runtime.RequiredError(
                'authenticationLogoutApiV1AuthLogoutPostRequest',
                'Required parameter "authenticationLogoutApiV1AuthLogoutPostRequest" was null or undefined when calling authenticationLogoutApiV1AuthLogoutPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/logout`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthenticationLogoutApiV1AuthLogoutPostRequestToJSON(requestParameters['authenticationLogoutApiV1AuthLogoutPostRequest']),
        };
    }

    /**
     * Logs out the authenticated user.
     * Log out the current user
     */
    async authenticationLogoutApiV1AuthLogoutPostRaw(requestParameters: AuthenticationLogoutApiV1AuthLogoutPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.authenticationLogoutApiV1AuthLogoutPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Logs out the authenticated user.
     * Log out the current user
     */
    async authenticationLogoutApiV1AuthLogoutPost(requestParameters: AuthenticationLogoutApiV1AuthLogoutPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.authenticationLogoutApiV1AuthLogoutPostRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for authenticationRefreshApiV1AuthRefreshPost without sending the request
     */
    async authenticationRefreshApiV1AuthRefreshPostRequestOpts(requestParameters: AuthenticationRefreshApiV1AuthRefreshPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authenticationRefreshApiV1AuthRefreshPostRequest'] == null) {
            throw new runtime.RequiredError(
                'authenticationRefreshApiV1AuthRefreshPostRequest',
                'Required parameter "authenticationRefreshApiV1AuthRefreshPostRequest" was null or undefined when calling authenticationRefreshApiV1AuthRefreshPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/refresh`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthenticationRefreshApiV1AuthRefreshPostRequestToJSON(requestParameters['authenticationRefreshApiV1AuthRefreshPostRequest']),
        };
    }

    /**
     * Refreshes the current authentication session or credentials.
     * Refresh authentication
     */
    async authenticationRefreshApiV1AuthRefreshPostRaw(requestParameters: AuthenticationRefreshApiV1AuthRefreshPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthenticationLoginApiV1AuthLoginPostResponse>> {
        const requestOptions = await this.authenticationRefreshApiV1AuthRefreshPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthenticationLoginApiV1AuthLoginPostResponseFromJSON(jsonValue));
    }

    /**
     * Refreshes the current authentication session or credentials.
     * Refresh authentication
     */
    async authenticationRefreshApiV1AuthRefreshPost(requestParameters: AuthenticationRefreshApiV1AuthRefreshPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthenticationLoginApiV1AuthLoginPostResponse> {
        const response = await this.authenticationRefreshApiV1AuthRefreshPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authenticationRegisterApiV1AuthRegisterPost without sending the request
     */
    async authenticationRegisterApiV1AuthRegisterPostRequestOpts(requestParameters: AuthenticationRegisterApiV1AuthRegisterPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authenticationRegisterApiV1AuthRegisterPostRequest'] == null) {
            throw new runtime.RequiredError(
                'authenticationRegisterApiV1AuthRegisterPostRequest',
                'Required parameter "authenticationRegisterApiV1AuthRegisterPostRequest" was null or undefined when calling authenticationRegisterApiV1AuthRegisterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/register`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthenticationRegisterApiV1AuthRegisterPostRequestToJSON(requestParameters['authenticationRegisterApiV1AuthRegisterPostRequest']),
        };
    }

    /**
     * Creates a user account.
     * Register a user
     */
    async authenticationRegisterApiV1AuthRegisterPostRaw(requestParameters: AuthenticationRegisterApiV1AuthRegisterPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthenticationLoginApiV1AuthLoginPostResponse>> {
        const requestOptions = await this.authenticationRegisterApiV1AuthRegisterPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthenticationLoginApiV1AuthLoginPostResponseFromJSON(jsonValue));
    }

    /**
     * Creates a user account.
     * Register a user
     */
    async authenticationRegisterApiV1AuthRegisterPost(requestParameters: AuthenticationRegisterApiV1AuthRegisterPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthenticationLoginApiV1AuthLoginPostResponse> {
        const response = await this.authenticationRegisterApiV1AuthRegisterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authenticationResetPasswordApiV1AuthResetPasswordPost without sending the request
     */
    async authenticationResetPasswordApiV1AuthResetPasswordPostRequestOpts(requestParameters: AuthenticationResetPasswordApiV1AuthResetPasswordPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authenticationResetPasswordApiV1AuthResetPasswordPostRequest'] == null) {
            throw new runtime.RequiredError(
                'authenticationResetPasswordApiV1AuthResetPasswordPostRequest',
                'Required parameter "authenticationResetPasswordApiV1AuthResetPasswordPostRequest" was null or undefined when calling authenticationResetPasswordApiV1AuthResetPasswordPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/reset-password`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AuthenticationResetPasswordApiV1AuthResetPasswordPostRequestToJSON(requestParameters['authenticationResetPasswordApiV1AuthResetPasswordPostRequest']),
        };
    }

    /**
     * Resets a user\'s password.
     * Reset a password
     */
    async authenticationResetPasswordApiV1AuthResetPasswordPostRaw(requestParameters: AuthenticationResetPasswordApiV1AuthResetPasswordPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthenticationChangePasswordApiV1AuthChangePasswordPostResponse>> {
        const requestOptions = await this.authenticationResetPasswordApiV1AuthResetPasswordPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthenticationChangePasswordApiV1AuthChangePasswordPostResponseFromJSON(jsonValue));
    }

    /**
     * Resets a user\'s password.
     * Reset a password
     */
    async authenticationResetPasswordApiV1AuthResetPasswordPost(requestParameters: AuthenticationResetPasswordApiV1AuthResetPasswordPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthenticationChangePasswordApiV1AuthChangePasswordPostResponse> {
        const response = await this.authenticationResetPasswordApiV1AuthResetPasswordPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for authenticationUpdateMeApiV1AuthMePatch without sending the request
     */
    async authenticationUpdateMeApiV1AuthMePatchRequestOpts(requestParameters: AuthenticationUpdateMeApiV1AuthMePatchOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['authenticationUpdateMeApiV1AuthMePatchRequest'] == null) {
            throw new runtime.RequiredError(
                'authenticationUpdateMeApiV1AuthMePatchRequest',
                'Required parameter "authenticationUpdateMeApiV1AuthMePatchRequest" was null or undefined when calling authenticationUpdateMeApiV1AuthMePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/auth/me`;

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AuthenticationUpdateMeApiV1AuthMePatchRequestToJSON(requestParameters['authenticationUpdateMeApiV1AuthMePatchRequest']),
        };
    }

    /**
     * Updates information for the authenticated user.
     * Update the current user
     */
    async authenticationUpdateMeApiV1AuthMePatchRaw(requestParameters: AuthenticationUpdateMeApiV1AuthMePatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AuthenticationGetMeApiV1AuthMeGetResponse>> {
        const requestOptions = await this.authenticationUpdateMeApiV1AuthMePatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AuthenticationGetMeApiV1AuthMeGetResponseFromJSON(jsonValue));
    }

    /**
     * Updates information for the authenticated user.
     * Update the current user
     */
    async authenticationUpdateMeApiV1AuthMePatch(requestParameters: AuthenticationUpdateMeApiV1AuthMePatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AuthenticationGetMeApiV1AuthMeGetResponse> {
        const response = await this.authenticationUpdateMeApiV1AuthMePatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
