/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type DefaultRootResponse,
    DefaultRootResponseFromJSON,
    DefaultRootResponseToJSON,
} from '../models/DefaultRootResponse';

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Creates request options for defaultRoot without sending the request
     */
    async defaultRootRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the root API resource.
     * Get the API root
     */
    async defaultRootRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DefaultRootResponse>> {
        const requestOptions = await this.defaultRootRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DefaultRootResponseFromJSON(jsonValue));
    }

    /**
     * Returns the root API resource.
     * Get the API root
     */
    async defaultRoot(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DefaultRootResponse> {
        const response = await this.defaultRootRaw(initOverrides);
        return await response.value();
    }

}
