/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ResourceConfig,
    ResourceConfigFromJSON,
    ResourceConfigToJSON,
} from '../models/ResourceConfig';

export interface MockResetRequest {
    /**
     * 
     */
    resourceConfig: ResourceConfig;
}

/**
 * 
 */
export class MockApi extends runtime.BaseAPI {

    /**
     * Creates request options for mockReset without sending the request
     */
    async mockResetRequestOpts(requestParameters: MockResetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['resourceConfig'] == null) {
            throw new runtime.RequiredError(
                'resourceConfig',
                'Required parameter "resourceConfig" was null or undefined when calling mockReset().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/mock/reset`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ResourceConfigToJSON(requestParameters['resourceConfig']),
        };
    }

    /**
     * Resets the API\'s mock data.
     * Reset mock data
     */
    async mockResetRaw(requestParameters: MockResetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.mockResetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Resets the API\'s mock data.
     * Reset mock data
     */
    async mockReset(requestParameters: MockResetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.mockResetRaw(requestParameters, initOverrides);
    }

}
