/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type MockOrdersMockCreateOrderRequest,
    MockOrdersMockCreateOrderRequestFromJSON,
    MockOrdersMockCreateOrderRequestToJSON,
} from '../models/MockOrdersMockCreateOrderRequest';
import {
    type MockOrdersMockCreateOrderResponse,
    MockOrdersMockCreateOrderResponseFromJSON,
    MockOrdersMockCreateOrderResponseToJSON,
} from '../models/MockOrdersMockCreateOrderResponse';
import {
    type MockOrdersMockListOrdersResponse,
    MockOrdersMockListOrdersResponseFromJSON,
    MockOrdersMockListOrdersResponseToJSON,
} from '../models/MockOrdersMockListOrdersResponse';
import {
    type MockOrdersMockReplaceOrderRequest,
    MockOrdersMockReplaceOrderRequestFromJSON,
    MockOrdersMockReplaceOrderRequestToJSON,
} from '../models/MockOrdersMockReplaceOrderRequest';
import {
    type MockOrdersMockUpdateOrderRequest,
    MockOrdersMockUpdateOrderRequestFromJSON,
    MockOrdersMockUpdateOrderRequestToJSON,
} from '../models/MockOrdersMockUpdateOrderRequest';

export interface MockOrdersMockCreateOrderOperationRequest {
    /**
     * 
     */
    mockOrdersMockCreateOrderRequest: MockOrdersMockCreateOrderRequest;
}

export interface MockOrdersMockDeleteOrderRequest {
    /**
     * 
     */
    itemId: string;
}

export interface MockOrdersMockGetOrderRequest {
    /**
     * 
     */
    itemId: string;
}

export interface MockOrdersMockListOrdersRequest {
    /**
     * 
     */
    region: MockOrdersMockListOrdersRegionEnum;
    /**
     * 
     */
    limit?: number;
    /**
     * 
     */
    offset?: number;
    /**
     * 
     */
    q?: string | null;
    /**
     * 
     */
    sort?: MockOrdersMockListOrdersSortEnum;
}

export interface MockOrdersMockReplaceOrderOperationRequest {
    /**
     * 
     */
    itemId: string;
    /**
     * 
     */
    mockOrdersMockReplaceOrderRequest: MockOrdersMockReplaceOrderRequest;
}

export interface MockOrdersMockUpdateOrderOperationRequest {
    /**
     * 
     */
    itemId: string;
    /**
     * 
     */
    mockOrdersMockUpdateOrderRequest: MockOrdersMockUpdateOrderRequest;
}

/**
 * 
 */
export class MockOrdersApi extends runtime.BaseAPI {

    /**
     * Creates request options for mockOrdersMockCreateOrder without sending the request
     */
    async mockOrdersMockCreateOrderRequestOpts(requestParameters: MockOrdersMockCreateOrderOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['mockOrdersMockCreateOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'mockOrdersMockCreateOrderRequest',
                'Required parameter "mockOrdersMockCreateOrderRequest" was null or undefined when calling mockOrdersMockCreateOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/mock/orders`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MockOrdersMockCreateOrderRequestToJSON(requestParameters['mockOrdersMockCreateOrderRequest']),
        };
    }

    /**
     * Adds an order to the mock order collection.
     * Create a mock order
     */
    async mockOrdersMockCreateOrderRaw(requestParameters: MockOrdersMockCreateOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockOrdersMockCreateOrderResponse>> {
        const requestOptions = await this.mockOrdersMockCreateOrderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockOrdersMockCreateOrderResponseFromJSON(jsonValue));
    }

    /**
     * Adds an order to the mock order collection.
     * Create a mock order
     */
    async mockOrdersMockCreateOrder(requestParameters: MockOrdersMockCreateOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockOrdersMockCreateOrderResponse> {
        const response = await this.mockOrdersMockCreateOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockOrdersMockDeleteOrder without sending the request
     */
    async mockOrdersMockDeleteOrderRequestOpts(requestParameters: MockOrdersMockDeleteOrderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockOrdersMockDeleteOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/mock/orders/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes the mock order identified by the item ID.
     * Delete a mock order
     */
    async mockOrdersMockDeleteOrderRaw(requestParameters: MockOrdersMockDeleteOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.mockOrdersMockDeleteOrderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes the mock order identified by the item ID.
     * Delete a mock order
     */
    async mockOrdersMockDeleteOrder(requestParameters: MockOrdersMockDeleteOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.mockOrdersMockDeleteOrderRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for mockOrdersMockGetOrder without sending the request
     */
    async mockOrdersMockGetOrderRequestOpts(requestParameters: MockOrdersMockGetOrderRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockOrdersMockGetOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/mock/orders/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves the mock order identified by the item ID.
     * Get a mock order
     */
    async mockOrdersMockGetOrderRaw(requestParameters: MockOrdersMockGetOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockOrdersMockCreateOrderResponse>> {
        const requestOptions = await this.mockOrdersMockGetOrderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockOrdersMockCreateOrderResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the mock order identified by the item ID.
     * Get a mock order
     */
    async mockOrdersMockGetOrder(requestParameters: MockOrdersMockGetOrderRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockOrdersMockCreateOrderResponse> {
        const response = await this.mockOrdersMockGetOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockOrdersMockListOrders without sending the request
     */
    async mockOrdersMockListOrdersRequestOpts(requestParameters: MockOrdersMockListOrdersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['region'] == null) {
            throw new runtime.RequiredError(
                'region',
                'Required parameter "region" was null or undefined when calling mockOrdersMockListOrders().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['region'] != null) {
            queryParameters['region'] = requestParameters['region'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/mock/orders`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves the mock order collection.
     * List mock orders
     */
    async mockOrdersMockListOrdersRaw(requestParameters: MockOrdersMockListOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockOrdersMockListOrdersResponse>> {
        const requestOptions = await this.mockOrdersMockListOrdersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockOrdersMockListOrdersResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the mock order collection.
     * List mock orders
     */
    async mockOrdersMockListOrders(requestParameters: MockOrdersMockListOrdersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockOrdersMockListOrdersResponse> {
        const response = await this.mockOrdersMockListOrdersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockOrdersMockReplaceOrder without sending the request
     */
    async mockOrdersMockReplaceOrderRequestOpts(requestParameters: MockOrdersMockReplaceOrderOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockOrdersMockReplaceOrder().'
            );
        }

        if (requestParameters['mockOrdersMockReplaceOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'mockOrdersMockReplaceOrderRequest',
                'Required parameter "mockOrdersMockReplaceOrderRequest" was null or undefined when calling mockOrdersMockReplaceOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/mock/orders/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MockOrdersMockReplaceOrderRequestToJSON(requestParameters['mockOrdersMockReplaceOrderRequest']),
        };
    }

    /**
     * Replaces the mock order identified by the item ID.
     * Replace a mock order
     */
    async mockOrdersMockReplaceOrderRaw(requestParameters: MockOrdersMockReplaceOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockOrdersMockCreateOrderResponse>> {
        const requestOptions = await this.mockOrdersMockReplaceOrderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockOrdersMockCreateOrderResponseFromJSON(jsonValue));
    }

    /**
     * Replaces the mock order identified by the item ID.
     * Replace a mock order
     */
    async mockOrdersMockReplaceOrder(requestParameters: MockOrdersMockReplaceOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockOrdersMockCreateOrderResponse> {
        const response = await this.mockOrdersMockReplaceOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockOrdersMockUpdateOrder without sending the request
     */
    async mockOrdersMockUpdateOrderRequestOpts(requestParameters: MockOrdersMockUpdateOrderOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockOrdersMockUpdateOrder().'
            );
        }

        if (requestParameters['mockOrdersMockUpdateOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'mockOrdersMockUpdateOrderRequest',
                'Required parameter "mockOrdersMockUpdateOrderRequest" was null or undefined when calling mockOrdersMockUpdateOrder().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/mock/orders/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: MockOrdersMockUpdateOrderRequestToJSON(requestParameters['mockOrdersMockUpdateOrderRequest']),
        };
    }

    /**
     * Updates the mock order identified by the item ID.
     * Update a mock order
     */
    async mockOrdersMockUpdateOrderRaw(requestParameters: MockOrdersMockUpdateOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockOrdersMockCreateOrderResponse>> {
        const requestOptions = await this.mockOrdersMockUpdateOrderRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockOrdersMockCreateOrderResponseFromJSON(jsonValue));
    }

    /**
     * Updates the mock order identified by the item ID.
     * Update a mock order
     */
    async mockOrdersMockUpdateOrder(requestParameters: MockOrdersMockUpdateOrderOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockOrdersMockCreateOrderResponse> {
        const response = await this.mockOrdersMockUpdateOrderRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const MockOrdersMockListOrdersRegionEnum = {
    Emea: 'emea',
    Apac: 'apac',
    Amer: 'amer',
} as const;
export type MockOrdersMockListOrdersRegionEnum = typeof MockOrdersMockListOrdersRegionEnum[keyof typeof MockOrdersMockListOrdersRegionEnum];
/**
 * @export
 */
export const MockOrdersMockListOrdersSortEnum = {
    Id: 'id',
    Id2: '-id',
    CreatedAt: 'created_at',
    CreatedAt2: '-created_at',
    UpdatedAt: 'updated_at',
    UpdatedAt2: '-updated_at',
} as const;
export type MockOrdersMockListOrdersSortEnum = typeof MockOrdersMockListOrdersSortEnum[keyof typeof MockOrdersMockListOrdersSortEnum];
