/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type MockProductsMockCreateProductRequest,
    MockProductsMockCreateProductRequestFromJSON,
    MockProductsMockCreateProductRequestToJSON,
} from '../models/MockProductsMockCreateProductRequest';
import {
    type MockProductsMockCreateProductResponse,
    MockProductsMockCreateProductResponseFromJSON,
    MockProductsMockCreateProductResponseToJSON,
} from '../models/MockProductsMockCreateProductResponse';
import {
    type MockProductsMockListProductsResponse,
    MockProductsMockListProductsResponseFromJSON,
    MockProductsMockListProductsResponseToJSON,
} from '../models/MockProductsMockListProductsResponse';
import {
    type MockProductsMockReplaceProductRequest,
    MockProductsMockReplaceProductRequestFromJSON,
    MockProductsMockReplaceProductRequestToJSON,
} from '../models/MockProductsMockReplaceProductRequest';
import {
    type MockProductsMockUpdateProductRequest,
    MockProductsMockUpdateProductRequestFromJSON,
    MockProductsMockUpdateProductRequestToJSON,
} from '../models/MockProductsMockUpdateProductRequest';

export interface MockProductsMockCreateProductOperationRequest {
    /**
     * 
     */
    mockProductsMockCreateProductRequest: MockProductsMockCreateProductRequest;
}

export interface MockProductsMockDeleteProductRequest {
    /**
     * 
     */
    itemId: string;
}

export interface MockProductsMockGetProductRequest {
    /**
     * 
     */
    itemId: string;
}

export interface MockProductsMockListProductsRequest {
    /**
     * 
     */
    limit?: number;
    /**
     * 
     */
    offset?: number;
    /**
     * 
     */
    q?: string | null;
    /**
     * 
     */
    sort?: MockProductsMockListProductsSortEnum;
}

export interface MockProductsMockReplaceProductOperationRequest {
    /**
     * 
     */
    itemId: string;
    /**
     * 
     */
    mockProductsMockReplaceProductRequest: MockProductsMockReplaceProductRequest;
}

export interface MockProductsMockUpdateProductOperationRequest {
    /**
     * 
     */
    itemId: string;
    /**
     * 
     */
    mockProductsMockUpdateProductRequest: MockProductsMockUpdateProductRequest;
}

/**
 * 
 */
export class MockProductsApi extends runtime.BaseAPI {

    /**
     * Creates request options for mockProductsMockCreateProduct without sending the request
     */
    async mockProductsMockCreateProductRequestOpts(requestParameters: MockProductsMockCreateProductOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['mockProductsMockCreateProductRequest'] == null) {
            throw new runtime.RequiredError(
                'mockProductsMockCreateProductRequest',
                'Required parameter "mockProductsMockCreateProductRequest" was null or undefined when calling mockProductsMockCreateProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/mock/products`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MockProductsMockCreateProductRequestToJSON(requestParameters['mockProductsMockCreateProductRequest']),
        };
    }

    /**
     * Adds a product to the mock product collection.
     * Create a mock product
     */
    async mockProductsMockCreateProductRaw(requestParameters: MockProductsMockCreateProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockProductsMockCreateProductResponse>> {
        const requestOptions = await this.mockProductsMockCreateProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockProductsMockCreateProductResponseFromJSON(jsonValue));
    }

    /**
     * Adds a product to the mock product collection.
     * Create a mock product
     */
    async mockProductsMockCreateProduct(requestParameters: MockProductsMockCreateProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockProductsMockCreateProductResponse> {
        const response = await this.mockProductsMockCreateProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockProductsMockDeleteProduct without sending the request
     */
    async mockProductsMockDeleteProductRequestOpts(requestParameters: MockProductsMockDeleteProductRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockProductsMockDeleteProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/mock/products/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes the mock product identified by the item ID.
     * Delete a mock product
     */
    async mockProductsMockDeleteProductRaw(requestParameters: MockProductsMockDeleteProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.mockProductsMockDeleteProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes the mock product identified by the item ID.
     * Delete a mock product
     */
    async mockProductsMockDeleteProduct(requestParameters: MockProductsMockDeleteProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.mockProductsMockDeleteProductRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for mockProductsMockGetProduct without sending the request
     */
    async mockProductsMockGetProductRequestOpts(requestParameters: MockProductsMockGetProductRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockProductsMockGetProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/mock/products/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves the mock product identified by the item ID.
     * Get a mock product
     */
    async mockProductsMockGetProductRaw(requestParameters: MockProductsMockGetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockProductsMockCreateProductResponse>> {
        const requestOptions = await this.mockProductsMockGetProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockProductsMockCreateProductResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the mock product identified by the item ID.
     * Get a mock product
     */
    async mockProductsMockGetProduct(requestParameters: MockProductsMockGetProductRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockProductsMockCreateProductResponse> {
        const response = await this.mockProductsMockGetProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockProductsMockListProducts without sending the request
     */
    async mockProductsMockListProductsRequestOpts(requestParameters: MockProductsMockListProductsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/mock/products`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves the mock product collection.
     * List mock products
     */
    async mockProductsMockListProductsRaw(requestParameters: MockProductsMockListProductsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockProductsMockListProductsResponse>> {
        const requestOptions = await this.mockProductsMockListProductsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockProductsMockListProductsResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the mock product collection.
     * List mock products
     */
    async mockProductsMockListProducts(requestParameters: MockProductsMockListProductsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockProductsMockListProductsResponse> {
        const response = await this.mockProductsMockListProductsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockProductsMockReplaceProduct without sending the request
     */
    async mockProductsMockReplaceProductRequestOpts(requestParameters: MockProductsMockReplaceProductOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockProductsMockReplaceProduct().'
            );
        }

        if (requestParameters['mockProductsMockReplaceProductRequest'] == null) {
            throw new runtime.RequiredError(
                'mockProductsMockReplaceProductRequest',
                'Required parameter "mockProductsMockReplaceProductRequest" was null or undefined when calling mockProductsMockReplaceProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/mock/products/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MockProductsMockReplaceProductRequestToJSON(requestParameters['mockProductsMockReplaceProductRequest']),
        };
    }

    /**
     * Replaces the mock product identified by the item ID.
     * Replace a mock product
     */
    async mockProductsMockReplaceProductRaw(requestParameters: MockProductsMockReplaceProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockProductsMockCreateProductResponse>> {
        const requestOptions = await this.mockProductsMockReplaceProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockProductsMockCreateProductResponseFromJSON(jsonValue));
    }

    /**
     * Replaces the mock product identified by the item ID.
     * Replace a mock product
     */
    async mockProductsMockReplaceProduct(requestParameters: MockProductsMockReplaceProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockProductsMockCreateProductResponse> {
        const response = await this.mockProductsMockReplaceProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockProductsMockUpdateProduct without sending the request
     */
    async mockProductsMockUpdateProductRequestOpts(requestParameters: MockProductsMockUpdateProductOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockProductsMockUpdateProduct().'
            );
        }

        if (requestParameters['mockProductsMockUpdateProductRequest'] == null) {
            throw new runtime.RequiredError(
                'mockProductsMockUpdateProductRequest',
                'Required parameter "mockProductsMockUpdateProductRequest" was null or undefined when calling mockProductsMockUpdateProduct().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/mock/products/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: MockProductsMockUpdateProductRequestToJSON(requestParameters['mockProductsMockUpdateProductRequest']),
        };
    }

    /**
     * Updates the mock product identified by the item ID.
     * Update a mock product
     */
    async mockProductsMockUpdateProductRaw(requestParameters: MockProductsMockUpdateProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockProductsMockCreateProductResponse>> {
        const requestOptions = await this.mockProductsMockUpdateProductRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockProductsMockCreateProductResponseFromJSON(jsonValue));
    }

    /**
     * Updates the mock product identified by the item ID.
     * Update a mock product
     */
    async mockProductsMockUpdateProduct(requestParameters: MockProductsMockUpdateProductOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockProductsMockCreateProductResponse> {
        const response = await this.mockProductsMockUpdateProductRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const MockProductsMockListProductsSortEnum = {
    Id: 'id',
    Id2: '-id',
    CreatedAt: 'created_at',
    CreatedAt2: '-created_at',
    UpdatedAt: 'updated_at',
    UpdatedAt2: '-updated_at',
} as const;
export type MockProductsMockListProductsSortEnum = typeof MockProductsMockListProductsSortEnum[keyof typeof MockProductsMockListProductsSortEnum];
