/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type MockTicketsMockCreateTicketRequest,
    MockTicketsMockCreateTicketRequestFromJSON,
    MockTicketsMockCreateTicketRequestToJSON,
} from '../models/MockTicketsMockCreateTicketRequest';
import {
    type MockTicketsMockCreateTicketResponse,
    MockTicketsMockCreateTicketResponseFromJSON,
    MockTicketsMockCreateTicketResponseToJSON,
} from '../models/MockTicketsMockCreateTicketResponse';
import {
    type MockTicketsMockListTicketsResponse,
    MockTicketsMockListTicketsResponseFromJSON,
    MockTicketsMockListTicketsResponseToJSON,
} from '../models/MockTicketsMockListTicketsResponse';
import {
    type MockTicketsMockReplaceTicketRequest,
    MockTicketsMockReplaceTicketRequestFromJSON,
    MockTicketsMockReplaceTicketRequestToJSON,
} from '../models/MockTicketsMockReplaceTicketRequest';
import {
    type MockTicketsMockUpdateTicketRequest,
    MockTicketsMockUpdateTicketRequestFromJSON,
    MockTicketsMockUpdateTicketRequestToJSON,
} from '../models/MockTicketsMockUpdateTicketRequest';

export interface MockTicketsMockCreateTicketOperationRequest {
    /**
     * 
     */
    mockTicketsMockCreateTicketRequest: MockTicketsMockCreateTicketRequest;
}

export interface MockTicketsMockDeleteTicketRequest {
    /**
     * 
     */
    itemId: string;
}

export interface MockTicketsMockGetTicketRequest {
    /**
     * 
     */
    itemId: string;
}

export interface MockTicketsMockListTicketsRequest {
    /**
     * 
     */
    limit?: number;
    /**
     * 
     */
    offset?: number;
    /**
     * 
     */
    q?: string | null;
    /**
     * 
     */
    sort?: MockTicketsMockListTicketsSortEnum;
}

export interface MockTicketsMockReplaceTicketOperationRequest {
    /**
     * 
     */
    itemId: string;
    /**
     * 
     */
    mockTicketsMockReplaceTicketRequest: MockTicketsMockReplaceTicketRequest;
}

export interface MockTicketsMockUpdateTicketOperationRequest {
    /**
     * 
     */
    itemId: string;
    /**
     * 
     */
    mockTicketsMockUpdateTicketRequest: MockTicketsMockUpdateTicketRequest;
}

/**
 * 
 */
export class MockTicketsApi extends runtime.BaseAPI {

    /**
     * Creates request options for mockTicketsMockCreateTicket without sending the request
     */
    async mockTicketsMockCreateTicketRequestOpts(requestParameters: MockTicketsMockCreateTicketOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['mockTicketsMockCreateTicketRequest'] == null) {
            throw new runtime.RequiredError(
                'mockTicketsMockCreateTicketRequest',
                'Required parameter "mockTicketsMockCreateTicketRequest" was null or undefined when calling mockTicketsMockCreateTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/mock/tickets`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MockTicketsMockCreateTicketRequestToJSON(requestParameters['mockTicketsMockCreateTicketRequest']),
        };
    }

    /**
     * Creates a ticket in the mock ticket collection.
     * Create a mock ticket
     */
    async mockTicketsMockCreateTicketRaw(requestParameters: MockTicketsMockCreateTicketOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockTicketsMockCreateTicketResponse>> {
        const requestOptions = await this.mockTicketsMockCreateTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockTicketsMockCreateTicketResponseFromJSON(jsonValue));
    }

    /**
     * Creates a ticket in the mock ticket collection.
     * Create a mock ticket
     */
    async mockTicketsMockCreateTicket(requestParameters: MockTicketsMockCreateTicketOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockTicketsMockCreateTicketResponse> {
        const response = await this.mockTicketsMockCreateTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockTicketsMockDeleteTicket without sending the request
     */
    async mockTicketsMockDeleteTicketRequestOpts(requestParameters: MockTicketsMockDeleteTicketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockTicketsMockDeleteTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/mock/tickets/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes the mock ticket identified by the item ID.
     * Delete a mock ticket
     */
    async mockTicketsMockDeleteTicketRaw(requestParameters: MockTicketsMockDeleteTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.mockTicketsMockDeleteTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes the mock ticket identified by the item ID.
     * Delete a mock ticket
     */
    async mockTicketsMockDeleteTicket(requestParameters: MockTicketsMockDeleteTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.mockTicketsMockDeleteTicketRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for mockTicketsMockGetTicket without sending the request
     */
    async mockTicketsMockGetTicketRequestOpts(requestParameters: MockTicketsMockGetTicketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockTicketsMockGetTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/mock/tickets/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the mock ticket identified by the item ID.
     * Get a mock ticket
     */
    async mockTicketsMockGetTicketRaw(requestParameters: MockTicketsMockGetTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockTicketsMockCreateTicketResponse>> {
        const requestOptions = await this.mockTicketsMockGetTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockTicketsMockCreateTicketResponseFromJSON(jsonValue));
    }

    /**
     * Returns the mock ticket identified by the item ID.
     * Get a mock ticket
     */
    async mockTicketsMockGetTicket(requestParameters: MockTicketsMockGetTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockTicketsMockCreateTicketResponse> {
        const response = await this.mockTicketsMockGetTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockTicketsMockListTickets without sending the request
     */
    async mockTicketsMockListTicketsRequestOpts(requestParameters: MockTicketsMockListTicketsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/mock/tickets`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the mock ticket collection.
     * List mock tickets
     */
    async mockTicketsMockListTicketsRaw(requestParameters: MockTicketsMockListTicketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockTicketsMockListTicketsResponse>> {
        const requestOptions = await this.mockTicketsMockListTicketsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockTicketsMockListTicketsResponseFromJSON(jsonValue));
    }

    /**
     * Returns the mock ticket collection.
     * List mock tickets
     */
    async mockTicketsMockListTickets(requestParameters: MockTicketsMockListTicketsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockTicketsMockListTicketsResponse> {
        const response = await this.mockTicketsMockListTicketsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockTicketsMockReplaceTicket without sending the request
     */
    async mockTicketsMockReplaceTicketRequestOpts(requestParameters: MockTicketsMockReplaceTicketOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockTicketsMockReplaceTicket().'
            );
        }

        if (requestParameters['mockTicketsMockReplaceTicketRequest'] == null) {
            throw new runtime.RequiredError(
                'mockTicketsMockReplaceTicketRequest',
                'Required parameter "mockTicketsMockReplaceTicketRequest" was null or undefined when calling mockTicketsMockReplaceTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/mock/tickets/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MockTicketsMockReplaceTicketRequestToJSON(requestParameters['mockTicketsMockReplaceTicketRequest']),
        };
    }

    /**
     * Replaces the mock ticket identified by the item ID.
     * Replace a mock ticket
     */
    async mockTicketsMockReplaceTicketRaw(requestParameters: MockTicketsMockReplaceTicketOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockTicketsMockCreateTicketResponse>> {
        const requestOptions = await this.mockTicketsMockReplaceTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockTicketsMockCreateTicketResponseFromJSON(jsonValue));
    }

    /**
     * Replaces the mock ticket identified by the item ID.
     * Replace a mock ticket
     */
    async mockTicketsMockReplaceTicket(requestParameters: MockTicketsMockReplaceTicketOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockTicketsMockCreateTicketResponse> {
        const response = await this.mockTicketsMockReplaceTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockTicketsMockUpdateTicket without sending the request
     */
    async mockTicketsMockUpdateTicketRequestOpts(requestParameters: MockTicketsMockUpdateTicketOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockTicketsMockUpdateTicket().'
            );
        }

        if (requestParameters['mockTicketsMockUpdateTicketRequest'] == null) {
            throw new runtime.RequiredError(
                'mockTicketsMockUpdateTicketRequest',
                'Required parameter "mockTicketsMockUpdateTicketRequest" was null or undefined when calling mockTicketsMockUpdateTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/mock/tickets/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: MockTicketsMockUpdateTicketRequestToJSON(requestParameters['mockTicketsMockUpdateTicketRequest']),
        };
    }

    /**
     * Updates the mock ticket identified by the item ID.
     * Update a mock ticket
     */
    async mockTicketsMockUpdateTicketRaw(requestParameters: MockTicketsMockUpdateTicketOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockTicketsMockCreateTicketResponse>> {
        const requestOptions = await this.mockTicketsMockUpdateTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockTicketsMockCreateTicketResponseFromJSON(jsonValue));
    }

    /**
     * Updates the mock ticket identified by the item ID.
     * Update a mock ticket
     */
    async mockTicketsMockUpdateTicket(requestParameters: MockTicketsMockUpdateTicketOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockTicketsMockCreateTicketResponse> {
        const response = await this.mockTicketsMockUpdateTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const MockTicketsMockListTicketsSortEnum = {
    Id: 'id',
    Id2: '-id',
    CreatedAt: 'created_at',
    CreatedAt2: '-created_at',
    UpdatedAt: 'updated_at',
    UpdatedAt2: '-updated_at',
} as const;
export type MockTicketsMockListTicketsSortEnum = typeof MockTicketsMockListTicketsSortEnum[keyof typeof MockTicketsMockListTicketsSortEnum];
