/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

/**
 * 
 */
export class MockOpenapiJsonApi extends runtime.BaseAPI {

    /**
     * Creates request options for mockOpenapiJsonMockOpenapi without sending the request
     */
    async mockOpenapiJsonMockOpenapiRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/mock-openapi.json`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * GET /mock-openapi.json
     */
    async mockOpenapiJsonMockOpenapiRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.mockOpenapiJsonMockOpenapiRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * GET /mock-openapi.json
     */
    async mockOpenapiJsonMockOpenapi(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.mockOpenapiJsonMockOpenapiRaw(initOverrides);
    }

}
