/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type MockCustomersMockCreateCustomerRequest,
    MockCustomersMockCreateCustomerRequestFromJSON,
    MockCustomersMockCreateCustomerRequestToJSON,
} from '../models/MockCustomersMockCreateCustomerRequest';
import {
    type MockCustomersMockCreateCustomerResponse,
    MockCustomersMockCreateCustomerResponseFromJSON,
    MockCustomersMockCreateCustomerResponseToJSON,
} from '../models/MockCustomersMockCreateCustomerResponse';
import {
    type MockCustomersMockListCustomersResponse,
    MockCustomersMockListCustomersResponseFromJSON,
    MockCustomersMockListCustomersResponseToJSON,
} from '../models/MockCustomersMockListCustomersResponse';
import {
    type MockCustomersMockReplaceCustomerRequest,
    MockCustomersMockReplaceCustomerRequestFromJSON,
    MockCustomersMockReplaceCustomerRequestToJSON,
} from '../models/MockCustomersMockReplaceCustomerRequest';
import {
    type MockCustomersMockUpdateCustomerRequest,
    MockCustomersMockUpdateCustomerRequestFromJSON,
    MockCustomersMockUpdateCustomerRequestToJSON,
} from '../models/MockCustomersMockUpdateCustomerRequest';

export interface MockCustomersMockCreateCustomerOperationRequest {
    /**
     * 
     */
    mockCustomersMockCreateCustomerRequest: MockCustomersMockCreateCustomerRequest;
}

export interface MockCustomersMockDeleteCustomerRequest {
    /**
     * 
     */
    itemId: string;
}

export interface MockCustomersMockGetCustomerRequest {
    /**
     * 
     */
    itemId: string;
}

export interface MockCustomersMockListCustomersRequest {
    /**
     * 
     */
    region: MockCustomersMockListCustomersRegionEnum;
    /**
     * 
     */
    limit?: number;
    /**
     * 
     */
    offset?: number;
    /**
     * 
     */
    q?: string | null;
    /**
     * 
     */
    sort?: MockCustomersMockListCustomersSortEnum;
}

export interface MockCustomersMockReplaceCustomerOperationRequest {
    /**
     * 
     */
    itemId: string;
    /**
     * 
     */
    mockCustomersMockReplaceCustomerRequest: MockCustomersMockReplaceCustomerRequest;
}

export interface MockCustomersMockUpdateCustomerOperationRequest {
    /**
     * 
     */
    itemId: string;
    /**
     * 
     */
    mockCustomersMockUpdateCustomerRequest: MockCustomersMockUpdateCustomerRequest;
}

/**
 * 
 */
export class MockCustomersApi extends runtime.BaseAPI {

    /**
     * Creates request options for mockCustomersMockCreateCustomer without sending the request
     */
    async mockCustomersMockCreateCustomerRequestOpts(requestParameters: MockCustomersMockCreateCustomerOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['mockCustomersMockCreateCustomerRequest'] == null) {
            throw new runtime.RequiredError(
                'mockCustomersMockCreateCustomerRequest',
                'Required parameter "mockCustomersMockCreateCustomerRequest" was null or undefined when calling mockCustomersMockCreateCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/mock/customers`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MockCustomersMockCreateCustomerRequestToJSON(requestParameters['mockCustomersMockCreateCustomerRequest']),
        };
    }

    /**
     * Creates a customer in the mock customer collection.
     * Create a mock customer
     */
    async mockCustomersMockCreateCustomerRaw(requestParameters: MockCustomersMockCreateCustomerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockCustomersMockCreateCustomerResponse>> {
        const requestOptions = await this.mockCustomersMockCreateCustomerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockCustomersMockCreateCustomerResponseFromJSON(jsonValue));
    }

    /**
     * Creates a customer in the mock customer collection.
     * Create a mock customer
     */
    async mockCustomersMockCreateCustomer(requestParameters: MockCustomersMockCreateCustomerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockCustomersMockCreateCustomerResponse> {
        const response = await this.mockCustomersMockCreateCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockCustomersMockDeleteCustomer without sending the request
     */
    async mockCustomersMockDeleteCustomerRequestOpts(requestParameters: MockCustomersMockDeleteCustomerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockCustomersMockDeleteCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/mock/customers/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes the mock customer identified by the item ID.
     * Delete a mock customer
     */
    async mockCustomersMockDeleteCustomerRaw(requestParameters: MockCustomersMockDeleteCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.mockCustomersMockDeleteCustomerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes the mock customer identified by the item ID.
     * Delete a mock customer
     */
    async mockCustomersMockDeleteCustomer(requestParameters: MockCustomersMockDeleteCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.mockCustomersMockDeleteCustomerRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for mockCustomersMockGetCustomer without sending the request
     */
    async mockCustomersMockGetCustomerRequestOpts(requestParameters: MockCustomersMockGetCustomerRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockCustomersMockGetCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/mock/customers/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the mock customer identified by the item ID.
     * Get a mock customer
     */
    async mockCustomersMockGetCustomerRaw(requestParameters: MockCustomersMockGetCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockCustomersMockCreateCustomerResponse>> {
        const requestOptions = await this.mockCustomersMockGetCustomerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockCustomersMockCreateCustomerResponseFromJSON(jsonValue));
    }

    /**
     * Returns the mock customer identified by the item ID.
     * Get a mock customer
     */
    async mockCustomersMockGetCustomer(requestParameters: MockCustomersMockGetCustomerRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockCustomersMockCreateCustomerResponse> {
        const response = await this.mockCustomersMockGetCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockCustomersMockListCustomers without sending the request
     */
    async mockCustomersMockListCustomersRequestOpts(requestParameters: MockCustomersMockListCustomersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['region'] == null) {
            throw new runtime.RequiredError(
                'region',
                'Required parameter "region" was null or undefined when calling mockCustomersMockListCustomers().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['region'] != null) {
            queryParameters['region'] = requestParameters['region'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/mock/customers`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the mock customer collection.
     * List mock customers
     */
    async mockCustomersMockListCustomersRaw(requestParameters: MockCustomersMockListCustomersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockCustomersMockListCustomersResponse>> {
        const requestOptions = await this.mockCustomersMockListCustomersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockCustomersMockListCustomersResponseFromJSON(jsonValue));
    }

    /**
     * Returns the mock customer collection.
     * List mock customers
     */
    async mockCustomersMockListCustomers(requestParameters: MockCustomersMockListCustomersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockCustomersMockListCustomersResponse> {
        const response = await this.mockCustomersMockListCustomersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockCustomersMockReplaceCustomer without sending the request
     */
    async mockCustomersMockReplaceCustomerRequestOpts(requestParameters: MockCustomersMockReplaceCustomerOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockCustomersMockReplaceCustomer().'
            );
        }

        if (requestParameters['mockCustomersMockReplaceCustomerRequest'] == null) {
            throw new runtime.RequiredError(
                'mockCustomersMockReplaceCustomerRequest',
                'Required parameter "mockCustomersMockReplaceCustomerRequest" was null or undefined when calling mockCustomersMockReplaceCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/mock/customers/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MockCustomersMockReplaceCustomerRequestToJSON(requestParameters['mockCustomersMockReplaceCustomerRequest']),
        };
    }

    /**
     * Replaces the mock customer identified by the item ID.
     * Replace a mock customer
     */
    async mockCustomersMockReplaceCustomerRaw(requestParameters: MockCustomersMockReplaceCustomerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockCustomersMockCreateCustomerResponse>> {
        const requestOptions = await this.mockCustomersMockReplaceCustomerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockCustomersMockCreateCustomerResponseFromJSON(jsonValue));
    }

    /**
     * Replaces the mock customer identified by the item ID.
     * Replace a mock customer
     */
    async mockCustomersMockReplaceCustomer(requestParameters: MockCustomersMockReplaceCustomerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockCustomersMockCreateCustomerResponse> {
        const response = await this.mockCustomersMockReplaceCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockCustomersMockUpdateCustomer without sending the request
     */
    async mockCustomersMockUpdateCustomerRequestOpts(requestParameters: MockCustomersMockUpdateCustomerOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockCustomersMockUpdateCustomer().'
            );
        }

        if (requestParameters['mockCustomersMockUpdateCustomerRequest'] == null) {
            throw new runtime.RequiredError(
                'mockCustomersMockUpdateCustomerRequest',
                'Required parameter "mockCustomersMockUpdateCustomerRequest" was null or undefined when calling mockCustomersMockUpdateCustomer().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/mock/customers/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: MockCustomersMockUpdateCustomerRequestToJSON(requestParameters['mockCustomersMockUpdateCustomerRequest']),
        };
    }

    /**
     * Updates the mock customer identified by the item ID.
     * Update a mock customer
     */
    async mockCustomersMockUpdateCustomerRaw(requestParameters: MockCustomersMockUpdateCustomerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockCustomersMockCreateCustomerResponse>> {
        const requestOptions = await this.mockCustomersMockUpdateCustomerRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockCustomersMockCreateCustomerResponseFromJSON(jsonValue));
    }

    /**
     * Updates the mock customer identified by the item ID.
     * Update a mock customer
     */
    async mockCustomersMockUpdateCustomer(requestParameters: MockCustomersMockUpdateCustomerOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockCustomersMockCreateCustomerResponse> {
        const response = await this.mockCustomersMockUpdateCustomerRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const MockCustomersMockListCustomersRegionEnum = {
    Emea: 'emea',
    Apac: 'apac',
    Amer: 'amer',
} as const;
export type MockCustomersMockListCustomersRegionEnum = typeof MockCustomersMockListCustomersRegionEnum[keyof typeof MockCustomersMockListCustomersRegionEnum];
/**
 * @export
 */
export const MockCustomersMockListCustomersSortEnum = {
    Id: 'id',
    Id2: '-id',
    CreatedAt: 'created_at',
    CreatedAt2: '-created_at',
    UpdatedAt: 'updated_at',
    UpdatedAt2: '-updated_at',
} as const;
export type MockCustomersMockListCustomersSortEnum = typeof MockCustomersMockListCustomersSortEnum[keyof typeof MockCustomersMockListCustomersSortEnum];
