/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type MockReviewsMockCreateReviewRequest,
    MockReviewsMockCreateReviewRequestFromJSON,
    MockReviewsMockCreateReviewRequestToJSON,
} from '../models/MockReviewsMockCreateReviewRequest';
import {
    type MockReviewsMockCreateReviewResponse,
    MockReviewsMockCreateReviewResponseFromJSON,
    MockReviewsMockCreateReviewResponseToJSON,
} from '../models/MockReviewsMockCreateReviewResponse';
import {
    type MockReviewsMockListReviewsResponse,
    MockReviewsMockListReviewsResponseFromJSON,
    MockReviewsMockListReviewsResponseToJSON,
} from '../models/MockReviewsMockListReviewsResponse';
import {
    type MockReviewsMockReplaceReviewRequest,
    MockReviewsMockReplaceReviewRequestFromJSON,
    MockReviewsMockReplaceReviewRequestToJSON,
} from '../models/MockReviewsMockReplaceReviewRequest';
import {
    type MockReviewsMockUpdateReviewRequest,
    MockReviewsMockUpdateReviewRequestFromJSON,
    MockReviewsMockUpdateReviewRequestToJSON,
} from '../models/MockReviewsMockUpdateReviewRequest';

export interface MockReviewsMockCreateReviewOperationRequest {
    /**
     * 
     */
    mockReviewsMockCreateReviewRequest: MockReviewsMockCreateReviewRequest;
}

export interface MockReviewsMockDeleteReviewRequest {
    /**
     * 
     */
    itemId: string;
}

export interface MockReviewsMockGetReviewRequest {
    /**
     * 
     */
    itemId: string;
}

export interface MockReviewsMockListReviewsRequest {
    /**
     * 
     */
    limit?: number;
    /**
     * 
     */
    offset?: number;
    /**
     * 
     */
    q?: string | null;
    /**
     * 
     */
    sort?: MockReviewsMockListReviewsSortEnum;
}

export interface MockReviewsMockReplaceReviewOperationRequest {
    /**
     * 
     */
    itemId: string;
    /**
     * 
     */
    mockReviewsMockReplaceReviewRequest: MockReviewsMockReplaceReviewRequest;
}

export interface MockReviewsMockUpdateReviewOperationRequest {
    /**
     * 
     */
    itemId: string;
    /**
     * 
     */
    mockReviewsMockUpdateReviewRequest: MockReviewsMockUpdateReviewRequest;
}

/**
 * 
 */
export class MockReviewsApi extends runtime.BaseAPI {

    /**
     * Creates request options for mockReviewsMockCreateReview without sending the request
     */
    async mockReviewsMockCreateReviewRequestOpts(requestParameters: MockReviewsMockCreateReviewOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['mockReviewsMockCreateReviewRequest'] == null) {
            throw new runtime.RequiredError(
                'mockReviewsMockCreateReviewRequest',
                'Required parameter "mockReviewsMockCreateReviewRequest" was null or undefined when calling mockReviewsMockCreateReview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/mock/reviews`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MockReviewsMockCreateReviewRequestToJSON(requestParameters['mockReviewsMockCreateReviewRequest']),
        };
    }

    /**
     * Adds a review to the mock review collection.
     * Create a mock review
     */
    async mockReviewsMockCreateReviewRaw(requestParameters: MockReviewsMockCreateReviewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockReviewsMockCreateReviewResponse>> {
        const requestOptions = await this.mockReviewsMockCreateReviewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockReviewsMockCreateReviewResponseFromJSON(jsonValue));
    }

    /**
     * Adds a review to the mock review collection.
     * Create a mock review
     */
    async mockReviewsMockCreateReview(requestParameters: MockReviewsMockCreateReviewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockReviewsMockCreateReviewResponse> {
        const response = await this.mockReviewsMockCreateReviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockReviewsMockDeleteReview without sending the request
     */
    async mockReviewsMockDeleteReviewRequestOpts(requestParameters: MockReviewsMockDeleteReviewRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockReviewsMockDeleteReview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/mock/reviews/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Deletes the mock review identified by the item ID.
     * Delete a mock review
     */
    async mockReviewsMockDeleteReviewRaw(requestParameters: MockReviewsMockDeleteReviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.mockReviewsMockDeleteReviewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes the mock review identified by the item ID.
     * Delete a mock review
     */
    async mockReviewsMockDeleteReview(requestParameters: MockReviewsMockDeleteReviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.mockReviewsMockDeleteReviewRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for mockReviewsMockGetReview without sending the request
     */
    async mockReviewsMockGetReviewRequestOpts(requestParameters: MockReviewsMockGetReviewRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockReviewsMockGetReview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/mock/reviews/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves the mock review identified by the item ID.
     * Get a mock review
     */
    async mockReviewsMockGetReviewRaw(requestParameters: MockReviewsMockGetReviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockReviewsMockCreateReviewResponse>> {
        const requestOptions = await this.mockReviewsMockGetReviewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockReviewsMockCreateReviewResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the mock review identified by the item ID.
     * Get a mock review
     */
    async mockReviewsMockGetReview(requestParameters: MockReviewsMockGetReviewRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockReviewsMockCreateReviewResponse> {
        const response = await this.mockReviewsMockGetReviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockReviewsMockListReviews without sending the request
     */
    async mockReviewsMockListReviewsRequestOpts(requestParameters: MockReviewsMockListReviewsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['q'] != null) {
            queryParameters['q'] = requestParameters['q'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/mock/reviews`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieves the mock review collection.
     * List mock reviews
     */
    async mockReviewsMockListReviewsRaw(requestParameters: MockReviewsMockListReviewsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockReviewsMockListReviewsResponse>> {
        const requestOptions = await this.mockReviewsMockListReviewsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockReviewsMockListReviewsResponseFromJSON(jsonValue));
    }

    /**
     * Retrieves the mock review collection.
     * List mock reviews
     */
    async mockReviewsMockListReviews(requestParameters: MockReviewsMockListReviewsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockReviewsMockListReviewsResponse> {
        const response = await this.mockReviewsMockListReviewsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockReviewsMockReplaceReview without sending the request
     */
    async mockReviewsMockReplaceReviewRequestOpts(requestParameters: MockReviewsMockReplaceReviewOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockReviewsMockReplaceReview().'
            );
        }

        if (requestParameters['mockReviewsMockReplaceReviewRequest'] == null) {
            throw new runtime.RequiredError(
                'mockReviewsMockReplaceReviewRequest',
                'Required parameter "mockReviewsMockReplaceReviewRequest" was null or undefined when calling mockReviewsMockReplaceReview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/mock/reviews/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MockReviewsMockReplaceReviewRequestToJSON(requestParameters['mockReviewsMockReplaceReviewRequest']),
        };
    }

    /**
     * Replaces the mock review identified by the item ID.
     * Replace a mock review
     */
    async mockReviewsMockReplaceReviewRaw(requestParameters: MockReviewsMockReplaceReviewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockReviewsMockCreateReviewResponse>> {
        const requestOptions = await this.mockReviewsMockReplaceReviewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockReviewsMockCreateReviewResponseFromJSON(jsonValue));
    }

    /**
     * Replaces the mock review identified by the item ID.
     * Replace a mock review
     */
    async mockReviewsMockReplaceReview(requestParameters: MockReviewsMockReplaceReviewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockReviewsMockCreateReviewResponse> {
        const response = await this.mockReviewsMockReplaceReviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for mockReviewsMockUpdateReview without sending the request
     */
    async mockReviewsMockUpdateReviewRequestOpts(requestParameters: MockReviewsMockUpdateReviewOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['itemId'] == null) {
            throw new runtime.RequiredError(
                'itemId',
                'Required parameter "itemId" was null or undefined when calling mockReviewsMockUpdateReview().'
            );
        }

        if (requestParameters['mockReviewsMockUpdateReviewRequest'] == null) {
            throw new runtime.RequiredError(
                'mockReviewsMockUpdateReviewRequest',
                'Required parameter "mockReviewsMockUpdateReviewRequest" was null or undefined when calling mockReviewsMockUpdateReview().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/mock/reviews/{item_id}`;
        urlPath = urlPath.replace('{item_id}', encodeURIComponent(String(requestParameters['itemId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: MockReviewsMockUpdateReviewRequestToJSON(requestParameters['mockReviewsMockUpdateReviewRequest']),
        };
    }

    /**
     * Updates the mock review identified by the item ID.
     * Update a mock review
     */
    async mockReviewsMockUpdateReviewRaw(requestParameters: MockReviewsMockUpdateReviewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MockReviewsMockCreateReviewResponse>> {
        const requestOptions = await this.mockReviewsMockUpdateReviewRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MockReviewsMockCreateReviewResponseFromJSON(jsonValue));
    }

    /**
     * Updates the mock review identified by the item ID.
     * Update a mock review
     */
    async mockReviewsMockUpdateReview(requestParameters: MockReviewsMockUpdateReviewOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MockReviewsMockCreateReviewResponse> {
        const response = await this.mockReviewsMockUpdateReviewRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const MockReviewsMockListReviewsSortEnum = {
    Id: 'id',
    Id2: '-id',
    CreatedAt: 'created_at',
    CreatedAt2: '-created_at',
    UpdatedAt: 'updated_at',
    UpdatedAt2: '-updated_at',
} as const;
export type MockReviewsMockListReviewsSortEnum = typeof MockReviewsMockListReviewsSortEnum[keyof typeof MockReviewsMockListReviewsSortEnum];
