/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type PremanProbeDiscountApiV1PremanProbeDiscountGetResponse,
    PremanProbeDiscountApiV1PremanProbeDiscountGetResponseFromJSON,
    PremanProbeDiscountApiV1PremanProbeDiscountGetResponseToJSON,
} from '../models/PremanProbeDiscountApiV1PremanProbeDiscountGetResponse';
import {
    type PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponse,
    PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponseFromJSON,
    PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponseToJSON,
} from '../models/PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponse';
import {
    type PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponse,
    PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponseFromJSON,
    PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponseToJSON,
} from '../models/PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponse';
import {
    type PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponse,
    PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponseFromJSON,
    PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponseToJSON,
} from '../models/PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponse';

export interface PremanProbeDiscountApiV1PremanProbeDiscountGetRequest {
    /**
     * 
     */
    percentOff?: number;
}

/**
 * 
 */
export class PremanProbeApi extends runtime.BaseAPI {

    /**
     * Creates request options for premanProbeDiscountApiV1PremanProbeDiscountGet without sending the request
     */
    async premanProbeDiscountApiV1PremanProbeDiscountGetRequestOpts(requestParameters: PremanProbeDiscountApiV1PremanProbeDiscountGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['percentOff'] != null) {
            queryParameters['percent_off'] = requestParameters['percentOff'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/preman-probe/discount`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns discount information from the Preman probe.
     * Get a discount
     */
    async premanProbeDiscountApiV1PremanProbeDiscountGetRaw(requestParameters: PremanProbeDiscountApiV1PremanProbeDiscountGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PremanProbeDiscountApiV1PremanProbeDiscountGetResponse>> {
        const requestOptions = await this.premanProbeDiscountApiV1PremanProbeDiscountGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PremanProbeDiscountApiV1PremanProbeDiscountGetResponseFromJSON(jsonValue));
    }

    /**
     * Returns discount information from the Preman probe.
     * Get a discount
     */
    async premanProbeDiscountApiV1PremanProbeDiscountGet(requestParameters: PremanProbeDiscountApiV1PremanProbeDiscountGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PremanProbeDiscountApiV1PremanProbeDiscountGetResponse> {
        const response = await this.premanProbeDiscountApiV1PremanProbeDiscountGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for premanProbeOrderTotalApiV1PremanProbeOrderTotalGet without sending the request
     */
    async premanProbeOrderTotalApiV1PremanProbeOrderTotalGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/preman-probe/order-total`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns order total information from the Preman probe.
     * Get an order total
     */
    async premanProbeOrderTotalApiV1PremanProbeOrderTotalGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponse>> {
        const requestOptions = await this.premanProbeOrderTotalApiV1PremanProbeOrderTotalGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponseFromJSON(jsonValue));
    }

    /**
     * Returns order total information from the Preman probe.
     * Get an order total
     */
    async premanProbeOrderTotalApiV1PremanProbeOrderTotalGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PremanProbeOrderTotalApiV1PremanProbeOrderTotalGetResponse> {
        const response = await this.premanProbeOrderTotalApiV1PremanProbeOrderTotalGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for premanProbeRefundStatusApiV1PremanProbeRefundStatusGet without sending the request
     */
    async premanProbeRefundStatusApiV1PremanProbeRefundStatusGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/preman-probe/refund-status`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns refund status information from the Preman probe.
     * Get a refund status
     */
    async premanProbeRefundStatusApiV1PremanProbeRefundStatusGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponse>> {
        const requestOptions = await this.premanProbeRefundStatusApiV1PremanProbeRefundStatusGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponseFromJSON(jsonValue));
    }

    /**
     * Returns refund status information from the Preman probe.
     * Get a refund status
     */
    async premanProbeRefundStatusApiV1PremanProbeRefundStatusGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PremanProbeRefundStatusApiV1PremanProbeRefundStatusGetResponse> {
        const response = await this.premanProbeRefundStatusApiV1PremanProbeRefundStatusGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for premanProbeShippingEstimateApiV1PremanProbeShippingEstimateGet without sending the request
     */
    async premanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/preman-probe/shipping-estimate`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns shipping estimate information from the Preman probe.
     * Get a shipping estimate
     */
    async premanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponse>> {
        const requestOptions = await this.premanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponseFromJSON(jsonValue));
    }

    /**
     * Returns shipping estimate information from the Preman probe.
     * Get a shipping estimate
     */
    async premanProbeShippingEstimateApiV1PremanProbeShippingEstimateGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PremanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetResponse> {
        const response = await this.premanProbeShippingEstimateApiV1PremanProbeShippingEstimateGetRaw(initOverrides);
        return await response.value();
    }

}
