/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ProjectRecord,
    ProjectRecordFromJSON,
    ProjectRecordToJSON,
} from '../models/ProjectRecord';
import {
    type ProjectsCreateProjectApiV1ProjectsPostRequest,
    ProjectsCreateProjectApiV1ProjectsPostRequestFromJSON,
    ProjectsCreateProjectApiV1ProjectsPostRequestToJSON,
} from '../models/ProjectsCreateProjectApiV1ProjectsPostRequest';
import {
    type ProjectsCreateProjectApiV1ProjectsPostResponse,
    ProjectsCreateProjectApiV1ProjectsPostResponseFromJSON,
    ProjectsCreateProjectApiV1ProjectsPostResponseToJSON,
} from '../models/ProjectsCreateProjectApiV1ProjectsPostResponse';
import {
    type ProjectsDeleteProjectApiV1ProjectsProjectIdDeleteRequest,
    ProjectsDeleteProjectApiV1ProjectsProjectIdDeleteRequestFromJSON,
    ProjectsDeleteProjectApiV1ProjectsProjectIdDeleteRequestToJSON,
} from '../models/ProjectsDeleteProjectApiV1ProjectsProjectIdDeleteRequest';
import {
    type ProjectsListProjectsApiV1ProjectsGetResponse,
    ProjectsListProjectsApiV1ProjectsGetResponseFromJSON,
    ProjectsListProjectsApiV1ProjectsGetResponseToJSON,
} from '../models/ProjectsListProjectsApiV1ProjectsGetResponse';
import {
    type ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequest,
    ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequestFromJSON,
    ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequestToJSON,
} from '../models/ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequest';
import {
    type ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequest,
    ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequestFromJSON,
    ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequestToJSON,
} from '../models/ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequest';

export interface ProjectsCreateProjectRequest {
    /**
     * 
     */
    projectRecord: ProjectRecord;
}

export interface ProjectsCreateProjectApiV1ProjectsPostOperationRequest {
    /**
     * 
     */
    projectsCreateProjectApiV1ProjectsPostRequest: ProjectsCreateProjectApiV1ProjectsPostRequest;
}

export interface ProjectsDeleteProjectApiV1ProjectsProjectIdDeleteOperationRequest {
    /**
     * 
     */
    projectId: string;
    /**
     * 
     */
    projectsDeleteProjectApiV1ProjectsProjectIdDeleteRequest: ProjectsDeleteProjectApiV1ProjectsProjectIdDeleteRequest;
}

export interface ProjectsGetProjectApiV1ProjectsProjectIdGetRequest {
    /**
     * 
     */
    projectId: string;
}

export interface ProjectsListProjectsApiV1ProjectsGetRequest {
    /**
     * 
     */
    limit?: number;
    /**
     * 
     */
    offset?: number;
    /**
     * 
     */
    status?: ProjectsListProjectsApiV1ProjectsGetStatusEnum;
}

export interface ProjectsReplaceProjectApiV1ProjectsProjectIdPutOperationRequest {
    /**
     * 
     */
    projectId: string;
    /**
     * 
     */
    projectsReplaceProjectApiV1ProjectsProjectIdPutRequest: ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequest;
}

export interface ProjectsUpdateProjectApiV1ProjectsProjectIdPatchOperationRequest {
    /**
     * 
     */
    projectId: string;
    /**
     * 
     */
    projectsUpdateProjectApiV1ProjectsProjectIdPatchRequest: ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequest;
}

/**
 * 
 */
export class ProjectsApi extends runtime.BaseAPI {

    /**
     * Creates request options for projectsCreateProject without sending the request
     */
    async projectsCreateProjectRequestOpts(requestParameters: ProjectsCreateProjectRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectRecord'] == null) {
            throw new runtime.RequiredError(
                'projectRecord',
                'Required parameter "projectRecord" was null or undefined when calling projectsCreateProject().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/projects/`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectRecordToJSON(requestParameters['projectRecord']),
        };
    }

    /**
     * Creates a project.
     * Create a project
     */
    async projectsCreateProjectRaw(requestParameters: ProjectsCreateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.projectsCreateProjectRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Creates a project.
     * Create a project
     */
    async projectsCreateProject(requestParameters: ProjectsCreateProjectRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.projectsCreateProjectRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for projectsCreateProjectApiV1ProjectsPost without sending the request
     */
    async projectsCreateProjectApiV1ProjectsPostRequestOpts(requestParameters: ProjectsCreateProjectApiV1ProjectsPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectsCreateProjectApiV1ProjectsPostRequest'] == null) {
            throw new runtime.RequiredError(
                'projectsCreateProjectApiV1ProjectsPostRequest',
                'Required parameter "projectsCreateProjectApiV1ProjectsPostRequest" was null or undefined when calling projectsCreateProjectApiV1ProjectsPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/projects`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectsCreateProjectApiV1ProjectsPostRequestToJSON(requestParameters['projectsCreateProjectApiV1ProjectsPostRequest']),
        };
    }

    /**
     * Creates a project.
     * Create a project
     */
    async projectsCreateProjectApiV1ProjectsPostRaw(requestParameters: ProjectsCreateProjectApiV1ProjectsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectsCreateProjectApiV1ProjectsPostResponse>> {
        const requestOptions = await this.projectsCreateProjectApiV1ProjectsPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectsCreateProjectApiV1ProjectsPostResponseFromJSON(jsonValue));
    }

    /**
     * Creates a project.
     * Create a project
     */
    async projectsCreateProjectApiV1ProjectsPost(requestParameters: ProjectsCreateProjectApiV1ProjectsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectsCreateProjectApiV1ProjectsPostResponse> {
        const response = await this.projectsCreateProjectApiV1ProjectsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for projectsDeleteProjectApiV1ProjectsProjectIdDelete without sending the request
     */
    async projectsDeleteProjectApiV1ProjectsProjectIdDeleteRequestOpts(requestParameters: ProjectsDeleteProjectApiV1ProjectsProjectIdDeleteOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsDeleteProjectApiV1ProjectsProjectIdDelete().'
            );
        }

        if (requestParameters['projectsDeleteProjectApiV1ProjectsProjectIdDeleteRequest'] == null) {
            throw new runtime.RequiredError(
                'projectsDeleteProjectApiV1ProjectsProjectIdDeleteRequest',
                'Required parameter "projectsDeleteProjectApiV1ProjectsProjectIdDeleteRequest" was null or undefined when calling projectsDeleteProjectApiV1ProjectsProjectIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/projects/{project_id}`;
        urlPath = urlPath.replace('{project_id}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectsDeleteProjectApiV1ProjectsProjectIdDeleteRequestToJSON(requestParameters['projectsDeleteProjectApiV1ProjectsProjectIdDeleteRequest']),
        };
    }

    /**
     * Deletes the project identified by the project ID.
     * Delete a project
     */
    async projectsDeleteProjectApiV1ProjectsProjectIdDeleteRaw(requestParameters: ProjectsDeleteProjectApiV1ProjectsProjectIdDeleteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.projectsDeleteProjectApiV1ProjectsProjectIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes the project identified by the project ID.
     * Delete a project
     */
    async projectsDeleteProjectApiV1ProjectsProjectIdDelete(requestParameters: ProjectsDeleteProjectApiV1ProjectsProjectIdDeleteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.projectsDeleteProjectApiV1ProjectsProjectIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for projectsGetProjectApiV1ProjectsProjectIdGet without sending the request
     */
    async projectsGetProjectApiV1ProjectsProjectIdGetRequestOpts(requestParameters: ProjectsGetProjectApiV1ProjectsProjectIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsGetProjectApiV1ProjectsProjectIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/projects/{project_id}`;
        urlPath = urlPath.replace('{project_id}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the project identified by the project ID.
     * Get a project
     */
    async projectsGetProjectApiV1ProjectsProjectIdGetRaw(requestParameters: ProjectsGetProjectApiV1ProjectsProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectsCreateProjectApiV1ProjectsPostResponse>> {
        const requestOptions = await this.projectsGetProjectApiV1ProjectsProjectIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectsCreateProjectApiV1ProjectsPostResponseFromJSON(jsonValue));
    }

    /**
     * Returns the project identified by the project ID.
     * Get a project
     */
    async projectsGetProjectApiV1ProjectsProjectIdGet(requestParameters: ProjectsGetProjectApiV1ProjectsProjectIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectsCreateProjectApiV1ProjectsPostResponse> {
        const response = await this.projectsGetProjectApiV1ProjectsProjectIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for projectsListProjects without sending the request
     */
    async projectsListProjectsRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/projects/`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the project collection.
     * List projects
     */
    async projectsListProjectsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.projectsListProjectsRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Returns the project collection.
     * List projects
     */
    async projectsListProjects(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.projectsListProjectsRaw(initOverrides);
    }

    /**
     * Creates request options for projectsListProjectsApiV1ProjectsGet without sending the request
     */
    async projectsListProjectsApiV1ProjectsGetRequestOpts(requestParameters: ProjectsListProjectsApiV1ProjectsGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/projects`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the project collection.
     * List projects
     */
    async projectsListProjectsApiV1ProjectsGetRaw(requestParameters: ProjectsListProjectsApiV1ProjectsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectsListProjectsApiV1ProjectsGetResponse>> {
        const requestOptions = await this.projectsListProjectsApiV1ProjectsGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectsListProjectsApiV1ProjectsGetResponseFromJSON(jsonValue));
    }

    /**
     * Returns the project collection.
     * List projects
     */
    async projectsListProjectsApiV1ProjectsGet(requestParameters: ProjectsListProjectsApiV1ProjectsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectsListProjectsApiV1ProjectsGetResponse> {
        const response = await this.projectsListProjectsApiV1ProjectsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for projectsReplaceProjectApiV1ProjectsProjectIdPut without sending the request
     */
    async projectsReplaceProjectApiV1ProjectsProjectIdPutRequestOpts(requestParameters: ProjectsReplaceProjectApiV1ProjectsProjectIdPutOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsReplaceProjectApiV1ProjectsProjectIdPut().'
            );
        }

        if (requestParameters['projectsReplaceProjectApiV1ProjectsProjectIdPutRequest'] == null) {
            throw new runtime.RequiredError(
                'projectsReplaceProjectApiV1ProjectsProjectIdPutRequest',
                'Required parameter "projectsReplaceProjectApiV1ProjectsProjectIdPutRequest" was null or undefined when calling projectsReplaceProjectApiV1ProjectsProjectIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/projects/{project_id}`;
        urlPath = urlPath.replace('{project_id}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectsReplaceProjectApiV1ProjectsProjectIdPutRequestToJSON(requestParameters['projectsReplaceProjectApiV1ProjectsProjectIdPutRequest']),
        };
    }

    /**
     * Replaces the project identified by the project ID.
     * Replace a project
     */
    async projectsReplaceProjectApiV1ProjectsProjectIdPutRaw(requestParameters: ProjectsReplaceProjectApiV1ProjectsProjectIdPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectsCreateProjectApiV1ProjectsPostResponse>> {
        const requestOptions = await this.projectsReplaceProjectApiV1ProjectsProjectIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectsCreateProjectApiV1ProjectsPostResponseFromJSON(jsonValue));
    }

    /**
     * Replaces the project identified by the project ID.
     * Replace a project
     */
    async projectsReplaceProjectApiV1ProjectsProjectIdPut(requestParameters: ProjectsReplaceProjectApiV1ProjectsProjectIdPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectsCreateProjectApiV1ProjectsPostResponse> {
        const response = await this.projectsReplaceProjectApiV1ProjectsProjectIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for projectsUpdateProjectApiV1ProjectsProjectIdPatch without sending the request
     */
    async projectsUpdateProjectApiV1ProjectsProjectIdPatchRequestOpts(requestParameters: ProjectsUpdateProjectApiV1ProjectsProjectIdPatchOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling projectsUpdateProjectApiV1ProjectsProjectIdPatch().'
            );
        }

        if (requestParameters['projectsUpdateProjectApiV1ProjectsProjectIdPatchRequest'] == null) {
            throw new runtime.RequiredError(
                'projectsUpdateProjectApiV1ProjectsProjectIdPatchRequest',
                'Required parameter "projectsUpdateProjectApiV1ProjectsProjectIdPatchRequest" was null or undefined when calling projectsUpdateProjectApiV1ProjectsProjectIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/projects/{project_id}`;
        urlPath = urlPath.replace('{project_id}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: ProjectsUpdateProjectApiV1ProjectsProjectIdPatchRequestToJSON(requestParameters['projectsUpdateProjectApiV1ProjectsProjectIdPatchRequest']),
        };
    }

    /**
     * Updates the project identified by the project ID.
     * Update a project
     */
    async projectsUpdateProjectApiV1ProjectsProjectIdPatchRaw(requestParameters: ProjectsUpdateProjectApiV1ProjectsProjectIdPatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProjectsCreateProjectApiV1ProjectsPostResponse>> {
        const requestOptions = await this.projectsUpdateProjectApiV1ProjectsProjectIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProjectsCreateProjectApiV1ProjectsPostResponseFromJSON(jsonValue));
    }

    /**
     * Updates the project identified by the project ID.
     * Update a project
     */
    async projectsUpdateProjectApiV1ProjectsProjectIdPatch(requestParameters: ProjectsUpdateProjectApiV1ProjectsProjectIdPatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProjectsCreateProjectApiV1ProjectsPostResponse> {
        const response = await this.projectsUpdateProjectApiV1ProjectsProjectIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ProjectsListProjectsApiV1ProjectsGetStatusEnum = {
    Active: 'active',
    Archived: 'archived',
} as const;
export type ProjectsListProjectsApiV1ProjectsGetStatusEnum = typeof ProjectsListProjectsApiV1ProjectsGetStatusEnum[keyof typeof ProjectsListProjectsApiV1ProjectsGetStatusEnum];
