/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ReadyReadinessResponse,
    ReadyReadinessResponseFromJSON,
    ReadyReadinessResponseToJSON,
} from '../models/ReadyReadinessResponse';

/**
 * 
 */
export class ReadyApi extends runtime.BaseAPI {

    /**
     * Creates request options for readyReadiness without sending the request
     */
    async readyReadinessRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/ready`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * GET /ready
     */
    async readyReadinessRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReadyReadinessResponse>> {
        const requestOptions = await this.readyReadinessRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReadyReadinessResponseFromJSON(jsonValue));
    }

    /**
     * GET /ready
     */
    async readyReadiness(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReadyReadinessResponse> {
        const response = await this.readyReadinessRaw(initOverrides);
        return await response.value();
    }

}
