/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type SystemHealthHealthGetResponse,
    SystemHealthHealthGetResponseFromJSON,
    SystemHealthHealthGetResponseToJSON,
} from '../models/SystemHealthHealthGetResponse';

/**
 * 
 */
export class SystemApi extends runtime.BaseAPI {

    /**
     * Creates request options for systemHealthHealthGet without sending the request
     */
    async systemHealthHealthGetRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/health`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the system\'s health status.
     * Check system health
     */
    async systemHealthHealthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SystemHealthHealthGetResponse>> {
        const requestOptions = await this.systemHealthHealthGetRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SystemHealthHealthGetResponseFromJSON(jsonValue));
    }

    /**
     * Returns the system\'s health status.
     * Check system health
     */
    async systemHealthHealthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SystemHealthHealthGetResponse> {
        const response = await this.systemHealthHealthGetRaw(initOverrides);
        return await response.value();
    }

}
