/* tslint:disable */
/* eslint-disable */
/**
 * greptile-codex-backend
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequest,
    TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestFromJSON,
    TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestToJSON,
} from '../models/TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequest';
import {
    type TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse,
    TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseFromJSON,
    TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseToJSON,
} from '../models/TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse';
import {
    type TasksDeleteTaskApiV1TasksTaskIdDeleteRequest,
    TasksDeleteTaskApiV1TasksTaskIdDeleteRequestFromJSON,
    TasksDeleteTaskApiV1TasksTaskIdDeleteRequestToJSON,
} from '../models/TasksDeleteTaskApiV1TasksTaskIdDeleteRequest';
import {
    type TasksListTasksApiV1ProjectsProjectIdTasksGetResponse,
    TasksListTasksApiV1ProjectsProjectIdTasksGetResponseFromJSON,
    TasksListTasksApiV1ProjectsProjectIdTasksGetResponseToJSON,
} from '../models/TasksListTasksApiV1ProjectsProjectIdTasksGetResponse';
import {
    type TasksReplaceTaskApiV1TasksTaskIdPutRequest,
    TasksReplaceTaskApiV1TasksTaskIdPutRequestFromJSON,
    TasksReplaceTaskApiV1TasksTaskIdPutRequestToJSON,
} from '../models/TasksReplaceTaskApiV1TasksTaskIdPutRequest';
import {
    type TasksUpdateTaskApiV1TasksTaskIdPatchRequest,
    TasksUpdateTaskApiV1TasksTaskIdPatchRequestFromJSON,
    TasksUpdateTaskApiV1TasksTaskIdPatchRequestToJSON,
} from '../models/TasksUpdateTaskApiV1TasksTaskIdPatchRequest';

export interface TasksCreateTaskApiV1ProjectsProjectIdTasksPostOperationRequest {
    /**
     * 
     */
    projectId: string;
    /**
     * 
     */
    tasksCreateTaskApiV1ProjectsProjectIdTasksPostRequest: TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequest;
}

export interface TasksDeleteTaskApiV1TasksTaskIdDeleteOperationRequest {
    /**
     * 
     */
    taskId: string;
    /**
     * 
     */
    tasksDeleteTaskApiV1TasksTaskIdDeleteRequest: TasksDeleteTaskApiV1TasksTaskIdDeleteRequest;
}

export interface TasksGetTaskApiV1TasksTaskIdGetRequest {
    /**
     * 
     */
    taskId: string;
}

export interface TasksListTasksApiV1ProjectsProjectIdTasksGetRequest {
    /**
     * 
     */
    projectId: string;
    /**
     * 
     */
    limit?: number;
    /**
     * 
     */
    offset?: number;
    /**
     * 
     */
    status?: TasksListTasksApiV1ProjectsProjectIdTasksGetStatusEnum;
}

export interface TasksReplaceTaskApiV1TasksTaskIdPutOperationRequest {
    /**
     * 
     */
    taskId: string;
    /**
     * 
     */
    tasksReplaceTaskApiV1TasksTaskIdPutRequest: TasksReplaceTaskApiV1TasksTaskIdPutRequest;
}

export interface TasksUpdateTaskApiV1TasksTaskIdPatchOperationRequest {
    /**
     * 
     */
    taskId: string;
    /**
     * 
     */
    tasksUpdateTaskApiV1TasksTaskIdPatchRequest: TasksUpdateTaskApiV1TasksTaskIdPatchRequest;
}

/**
 * 
 */
export class TasksApi extends runtime.BaseAPI {

    /**
     * Creates request options for tasksCreateTaskApiV1ProjectsProjectIdTasksPost without sending the request
     */
    async tasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestOpts(requestParameters: TasksCreateTaskApiV1ProjectsProjectIdTasksPostOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling tasksCreateTaskApiV1ProjectsProjectIdTasksPost().'
            );
        }

        if (requestParameters['tasksCreateTaskApiV1ProjectsProjectIdTasksPostRequest'] == null) {
            throw new runtime.RequiredError(
                'tasksCreateTaskApiV1ProjectsProjectIdTasksPostRequest',
                'Required parameter "tasksCreateTaskApiV1ProjectsProjectIdTasksPostRequest" was null or undefined when calling tasksCreateTaskApiV1ProjectsProjectIdTasksPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/projects/{project_id}/tasks`;
        urlPath = urlPath.replace('{project_id}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestToJSON(requestParameters['tasksCreateTaskApiV1ProjectsProjectIdTasksPostRequest']),
        };
    }

    /**
     * Creates a task for the specified project.
     * Create a project task
     */
    async tasksCreateTaskApiV1ProjectsProjectIdTasksPostRaw(requestParameters: TasksCreateTaskApiV1ProjectsProjectIdTasksPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse>> {
        const requestOptions = await this.tasksCreateTaskApiV1ProjectsProjectIdTasksPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseFromJSON(jsonValue));
    }

    /**
     * Creates a task for the specified project.
     * Create a project task
     */
    async tasksCreateTaskApiV1ProjectsProjectIdTasksPost(requestParameters: TasksCreateTaskApiV1ProjectsProjectIdTasksPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse> {
        const response = await this.tasksCreateTaskApiV1ProjectsProjectIdTasksPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for tasksDeleteTaskApiV1TasksTaskIdDelete without sending the request
     */
    async tasksDeleteTaskApiV1TasksTaskIdDeleteRequestOpts(requestParameters: TasksDeleteTaskApiV1TasksTaskIdDeleteOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling tasksDeleteTaskApiV1TasksTaskIdDelete().'
            );
        }

        if (requestParameters['tasksDeleteTaskApiV1TasksTaskIdDeleteRequest'] == null) {
            throw new runtime.RequiredError(
                'tasksDeleteTaskApiV1TasksTaskIdDeleteRequest',
                'Required parameter "tasksDeleteTaskApiV1TasksTaskIdDeleteRequest" was null or undefined when calling tasksDeleteTaskApiV1TasksTaskIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/tasks/{task_id}`;
        urlPath = urlPath.replace('{task_id}', encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
            body: TasksDeleteTaskApiV1TasksTaskIdDeleteRequestToJSON(requestParameters['tasksDeleteTaskApiV1TasksTaskIdDeleteRequest']),
        };
    }

    /**
     * Deletes the task identified by the task ID.
     * Delete a task
     */
    async tasksDeleteTaskApiV1TasksTaskIdDeleteRaw(requestParameters: TasksDeleteTaskApiV1TasksTaskIdDeleteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.tasksDeleteTaskApiV1TasksTaskIdDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes the task identified by the task ID.
     * Delete a task
     */
    async tasksDeleteTaskApiV1TasksTaskIdDelete(requestParameters: TasksDeleteTaskApiV1TasksTaskIdDeleteOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.tasksDeleteTaskApiV1TasksTaskIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for tasksGetTaskApiV1TasksTaskIdGet without sending the request
     */
    async tasksGetTaskApiV1TasksTaskIdGetRequestOpts(requestParameters: TasksGetTaskApiV1TasksTaskIdGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling tasksGetTaskApiV1TasksTaskIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/tasks/{task_id}`;
        urlPath = urlPath.replace('{task_id}', encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the task identified by the task ID.
     * Get a task
     */
    async tasksGetTaskApiV1TasksTaskIdGetRaw(requestParameters: TasksGetTaskApiV1TasksTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse>> {
        const requestOptions = await this.tasksGetTaskApiV1TasksTaskIdGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseFromJSON(jsonValue));
    }

    /**
     * Returns the task identified by the task ID.
     * Get a task
     */
    async tasksGetTaskApiV1TasksTaskIdGet(requestParameters: TasksGetTaskApiV1TasksTaskIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse> {
        const response = await this.tasksGetTaskApiV1TasksTaskIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for tasksListTasksApiV1ProjectsProjectIdTasksGet without sending the request
     */
    async tasksListTasksApiV1ProjectsProjectIdTasksGetRequestOpts(requestParameters: TasksListTasksApiV1ProjectsProjectIdTasksGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['projectId'] == null) {
            throw new runtime.RequiredError(
                'projectId',
                'Required parameter "projectId" was null or undefined when calling tasksListTasksApiV1ProjectsProjectIdTasksGet().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/projects/{project_id}/tasks`;
        urlPath = urlPath.replace('{project_id}', encodeURIComponent(String(requestParameters['projectId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the tasks associated with the specified project.
     * List project tasks
     */
    async tasksListTasksApiV1ProjectsProjectIdTasksGetRaw(requestParameters: TasksListTasksApiV1ProjectsProjectIdTasksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TasksListTasksApiV1ProjectsProjectIdTasksGetResponse>> {
        const requestOptions = await this.tasksListTasksApiV1ProjectsProjectIdTasksGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TasksListTasksApiV1ProjectsProjectIdTasksGetResponseFromJSON(jsonValue));
    }

    /**
     * Returns the tasks associated with the specified project.
     * List project tasks
     */
    async tasksListTasksApiV1ProjectsProjectIdTasksGet(requestParameters: TasksListTasksApiV1ProjectsProjectIdTasksGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TasksListTasksApiV1ProjectsProjectIdTasksGetResponse> {
        const response = await this.tasksListTasksApiV1ProjectsProjectIdTasksGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for tasksReplaceTaskApiV1TasksTaskIdPut without sending the request
     */
    async tasksReplaceTaskApiV1TasksTaskIdPutRequestOpts(requestParameters: TasksReplaceTaskApiV1TasksTaskIdPutOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling tasksReplaceTaskApiV1TasksTaskIdPut().'
            );
        }

        if (requestParameters['tasksReplaceTaskApiV1TasksTaskIdPutRequest'] == null) {
            throw new runtime.RequiredError(
                'tasksReplaceTaskApiV1TasksTaskIdPutRequest',
                'Required parameter "tasksReplaceTaskApiV1TasksTaskIdPutRequest" was null or undefined when calling tasksReplaceTaskApiV1TasksTaskIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/tasks/{task_id}`;
        urlPath = urlPath.replace('{task_id}', encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TasksReplaceTaskApiV1TasksTaskIdPutRequestToJSON(requestParameters['tasksReplaceTaskApiV1TasksTaskIdPutRequest']),
        };
    }

    /**
     * Replaces the task identified by the task ID.
     * Replace a task
     */
    async tasksReplaceTaskApiV1TasksTaskIdPutRaw(requestParameters: TasksReplaceTaskApiV1TasksTaskIdPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse>> {
        const requestOptions = await this.tasksReplaceTaskApiV1TasksTaskIdPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseFromJSON(jsonValue));
    }

    /**
     * Replaces the task identified by the task ID.
     * Replace a task
     */
    async tasksReplaceTaskApiV1TasksTaskIdPut(requestParameters: TasksReplaceTaskApiV1TasksTaskIdPutOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse> {
        const response = await this.tasksReplaceTaskApiV1TasksTaskIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for tasksUpdateTaskApiV1TasksTaskIdPatch without sending the request
     */
    async tasksUpdateTaskApiV1TasksTaskIdPatchRequestOpts(requestParameters: TasksUpdateTaskApiV1TasksTaskIdPatchOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['taskId'] == null) {
            throw new runtime.RequiredError(
                'taskId',
                'Required parameter "taskId" was null or undefined when calling tasksUpdateTaskApiV1TasksTaskIdPatch().'
            );
        }

        if (requestParameters['tasksUpdateTaskApiV1TasksTaskIdPatchRequest'] == null) {
            throw new runtime.RequiredError(
                'tasksUpdateTaskApiV1TasksTaskIdPatchRequest',
                'Required parameter "tasksUpdateTaskApiV1TasksTaskIdPatchRequest" was null or undefined when calling tasksUpdateTaskApiV1TasksTaskIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/tasks/{task_id}`;
        urlPath = urlPath.replace('{task_id}', encodeURIComponent(String(requestParameters['taskId'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: TasksUpdateTaskApiV1TasksTaskIdPatchRequestToJSON(requestParameters['tasksUpdateTaskApiV1TasksTaskIdPatchRequest']),
        };
    }

    /**
     * Updates the task identified by the task ID.
     * Update a task
     */
    async tasksUpdateTaskApiV1TasksTaskIdPatchRaw(requestParameters: TasksUpdateTaskApiV1TasksTaskIdPatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse>> {
        const requestOptions = await this.tasksUpdateTaskApiV1TasksTaskIdPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponseFromJSON(jsonValue));
    }

    /**
     * Updates the task identified by the task ID.
     * Update a task
     */
    async tasksUpdateTaskApiV1TasksTaskIdPatch(requestParameters: TasksUpdateTaskApiV1TasksTaskIdPatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TasksCreateTaskApiV1ProjectsProjectIdTasksPostResponse> {
        const response = await this.tasksUpdateTaskApiV1TasksTaskIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const TasksListTasksApiV1ProjectsProjectIdTasksGetStatusEnum = {
    Todo: 'todo',
    InProgress: 'in_progress',
    Done: 'done',
} as const;
export type TasksListTasksApiV1ProjectsProjectIdTasksGetStatusEnum = typeof TasksListTasksApiV1ProjectsProjectIdTasksGetStatusEnum[keyof typeof TasksListTasksApiV1ProjectsProjectIdTasksGetStatusEnum];
